### ISSUE TITLE
UnboundLocalError thrown for certain timeout values

### ISSUE THREAD

**Issue by oscarbatori** [dpkp/kafka-python#1028]
Folks - quick question about some strange behavior we are seeing on the consumer side.

We made the following change, in particular dropping out `session_time_ms`:
```bash
@@ -44,7 +44,7 @@ def get_kafka_consumer(topic,group_id):
                              api_version=KAFKA_API_VERSION,
                              auto_offset_reset='latest',
                              enable_auto_commit=False,
-                             session_timeout_ms=300000)
+                             session_timeout_ms=5000)
     return consumer
```

Which resulted in our code throwing the following error:
```bash
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 380, in _handle_results
    task = get()
  File "<...>/venv/local/lib/python2.7/site-packages/kafka/protocol/pickle.py", line 32, in _unpickle_method
    return func.__get__(obj, cls)
UnboundLocalError: <unprintable UnboundLocalError object>
```

Looking at the code that throws the error:
```python
def _unpickle_method(func_name, obj, cls):
    for cls in cls.mro():
        try:
            func = cls.__dict__[func_name]
        except KeyError:
            pass
        else:
            break
        return func.__get__(obj, cls)
````

I assume that a `KeyError` causes execution to fall through without binding a value for `func`. Why does a timeout, or setting a time value too low, cause an `UnboundLocalError`?

I would like to help fix, but not sure what the cause is.

-Oscar

**Comment by dpkp** [comment]
What version of kafka-python are you using?

**Comment by oscarbatori** [comment]
`1.3.1` - is this fixed in `1.3.2`?

**Comment by dpkp** [comment]
It looks like you are using multiprocessing and/or threading -- can you provide any code snippet to help reproduce your setup?

**Comment by timkpaine** [comment]
@oscarbatori what code produced this error?
