### ISSUE TITLE
Kafka-Python returning object has no attribute '__code__' when writing to Spark Context Checkpoint

### ISSUE THREAD

**Issue by marcjimz** [dpkp/kafka-python#1114]
Hello, when I am calling checkpointing functions in PySpark, the one line of code that does not "checkpoint" is this:

producerDelay.send('delayed-Kafka', str(record))

where I have narrowed it down to the specific object created by: 

producerDelay = KafkaProducer(bootstrap_servers='localhost:9092')

I get the following error:

PicklingError: Could not serialize object: AttributeError: 'builtin_function_or_method' object has no attribute '__code__'

	at org.apache.spark.streaming.api.python.PythonTransformFunctionSerializer$.serialize(PythonDStream.scala:144)
	at org.apache.spark.streaming.api.python.TransformFunction$$anonfun$writeObject$1.apply$mcV$sp(PythonDStream.scala:101)
	at org.apache.spark.streaming.api.python.TransformFunction$$anonfun$writeObject$1.apply(PythonDStream.scala:100)
	at org.apache.spark.streaming.api.python.TransformFunction$$anonfun$writeObject$1.apply(PythonDStream.scala:100)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1269)
	... 63 more
Traceback (most recent call last):
  File "/Users/v523043/Documents/Eclipse-workspace/MyPythonSparkProject/src/delayKafkaQueue.py", line 136, in <module>
    ssc.start()
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/pyspark/streaming/context.py", line 196, in start
    self._jssc.start()
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o20.start.
: java.io.IOException: org.apache.spark.SparkException: An exception was raised by Python:
Traceback (most recent call last):
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/pyspark/streaming/util.py", line 105, in dumps
    func.func, func.rdd_wrap_func, func.deserializers)))
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/pyspark/serializers.py", line 460, in dumps
    return cloudpickle.dumps(obj, 2)
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/pyspark/cloudpickle.py", line 703, in dumps
    cp.dump(obj)
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/pyspark/cloudpickle.py", line 160, in dump
    raise pickle.PicklingError(msg)
PicklingError: Could not serialize object: AttributeError: 'builtin_function_or_method' object has no attribute '__code__'

	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1276)
	at org.apache.spark.streaming.api.python.TransformFunction.writeObject(PythonDStream.scala:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$writeObject$1.apply$mcV$sp(DStreamGraph.scala:182)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$writeObject$1.apply(DStreamGraph.scala:177)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$writeObject$1.apply(DStreamGraph.scala:177)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1269)
	at org.apache.spark.streaming.DStreamGraph.writeObject(DStreamGraph.scala:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.spark.streaming.Checkpoint$$anonfun$serialize$1.apply$mcV$sp(Checkpoint.scala:144)
	at org.apache.spark.streaming.Checkpoint$$anonfun$serialize$1.apply(Checkpoint.scala:144)
	at org.apache.spark.streaming.Checkpoint$$anonfun$serialize$1.apply(Checkpoint.scala:144)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1303)
	at org.apache.spark.streaming.Checkpoint$.serialize(Checkpoint.scala:145)
	at org.apache.spark.streaming.StreamingContext.validate(StreamingContext.scala:524)
	at org.apache.spark.streaming.StreamingContext.liftedTree1$1(StreamingContext.scala:572)
	at org.apache.spark.streaming.StreamingContext.start(StreamingContext.scala:571)
	at org.apache.spark.streaming.api.java.JavaStreamingContext.start(JavaStreamingContext.scala:556)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: An exception was raised by Python:
Traceback (most recent call last):
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/pyspark/streaming/util.py", line 105, in dumps
    func.func, func.rdd_wrap_func, func.deserializers)))
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/pyspark/serializers.py", line 460, in dumps
    return cloudpickle.dumps(obj, 2)
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/pyspark/cloudpickle.py", line 703, in dumps
    cp.dump(obj)
  File "/Users/v523043/Documents/SPDev/spark-2.1.1-bin-hadoop2.7/python/pyspark/cloudpickle.py", line 160, in dump
    raise pickle.PicklingError(msg)
PicklingError: Could not serialize object: AttributeError: 'builtin_function_or_method' object has no attribute '__code__'

	at org.apache.spark.streaming.api.python.PythonTransformFunctionSerializer$.serialize(PythonDStream.scala:144)
	at org.apache.spark.streaming.api.python.TransformFunction$$anonfun$writeObject$1.apply$mcV$sp(PythonDStream.scala:101)
	at org.apache.spark.streaming.api.python.TransformFunction$$anonfun$writeObject$1.apply(PythonDStream.scala:100)
	at org.apache.spark.streaming.api.python.TransformFunction$$anonfun$writeObject$1.apply(PythonDStream.scala:100)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1269)
	... 63 more

How can one define the attribute properly for __code__ here?

**Comment by dpkp** [comment]
kafka producers are not currently designed for pickling...  you should be able to use kafka-python if you ship the python code directly to spark. But from a pyspark shell you may have problems if it tries to pickle your data structures.
