### ISSUE TITLE
fail to run example.py

### ISSUE THREAD

**Issue by zhihongzeng** [dpkp/kafka-python#1117]
The working environment:
OS: ubuntu 16.04 LTS
kafka version: 1.3.4.dev (I just installed today: pip install kafka-python)

Results:
python example.py 
2017-06-08 14:55:59,356.356.653928757:kafka.client:140059700999936:INFO:16275:Bootstrapping cluster metadata from [('localhost', 9092, 0)]
2017-06-08 14:55:59,359.359.05790329:kafka.client:140059621717760:INFO:16275:Bootstrapping cluster metadata from [('localhost', 9092, 0)]
2017-06-08 14:55:59,359.359.755039215:kafka.conn:140059700999936:INFO:16275:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: connecting to 127.0.0.1:9092
2017-06-08 14:55:59,359.359.962940216:kafka.conn:140059621717760:INFO:16275:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: connecting to 127.0.0.1:9092
2017-06-08 14:55:59,360.360.085010529:kafka.conn:140059700999936:ERROR:16275:Connect attempt to <BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092> returned error 111. Disconnecting.
2017-06-08 14:55:59,360.360.183954239:kafka.conn:140059700999936:INFO:16275:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: Closing connection. ConnectionError: 111
2017-06-08 14:55:59,360.360.29291153:kafka.conn:140059621717760:ERROR:16275:Connect attempt to <BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092> returned error 111. Disconnecting.
2017-06-08 14:55:59,360.360.378026962:kafka.client:140059700999936:ERROR:16275:Unable to bootstrap from [('localhost', 9092, 0)]
2017-06-08 14:55:59,360.360.459089279:kafka.conn:140059621717760:INFO:16275:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: Closing connection. ConnectionError: 111
2017-06-08 14:55:59,360.360.549926758:kafka.client:140059700999936:ERROR:16275:No nodes found in metadata -- retrying bootstrap
2017-06-08 14:55:59,360.360.697031021:kafka.client:140059621717760:ERROR:16275:Unable to bootstrap from [('localhost', 9092, 0)]
2017-06-08 14:55:59,360.360.764980316:kafka.client:140059700999936:INFO:16275:Bootstrapping cluster metadata from [('localhost', 9092, 0)]
2017-06-08 14:55:59,360.360.853910446:kafka.client:140059621717760:ERROR:16275:No nodes found in metadata -- retrying bootstrap
2017-06-08 14:55:59,360.360.986948013:kafka.client:140059621717760:INFO:16275:Bootstrapping cluster metadata from [('localhost', 9092, 0)]
2017-06-08 14:55:59,457.457.247972488:kafka.conn:140059700999936:INFO:16275:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: connecting to 127.0.0.1:9092
2017-06-08 14:55:59,457.457.47590065:kafka.conn:140059700999936:ERROR:16275:Connect attempt to <BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092> returned error 111. Disconnecting.
2017-06-08 14:55:59,457.457.546949387:kafka.conn:140059700999936:INFO:16275:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: Closing connection. ConnectionError: 111
2017-06-08 14:55:59,457.457.673072815:kafka.client:140059700999936:ERROR:16275:Unable to bootstrap from [('localhost', 9092, 0)]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "example.py", line 11, in run
    producer = KafkaProducer(bootstrap_servers='localhost:9092')
  File "/home/zhihong/dev/kafka-python/kafka/producer/kafka.py", line 335, in __init__
    **self.config)
  File "/home/zhihong/dev/kafka-python/kafka/client_async.py", line 211, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/zhihong/dev/kafka-python/kafka/client_async.py", line 827, in check_version
    raise Errors.NoBrokersAvailable()
NoBrokersAvailable: NoBrokersAvailable

2017-06-08 14:55:59,458.458.259105682:kafka.producer.kafka:140059700999936:INFO:16275:Kafka producer closed
2017-06-08 14:55:59,459.459.420919418:kafka.conn:140059621717760:INFO:16275:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: connecting to 127.0.0.1:9092
2017-06-08 14:55:59,459.459.568023682:kafka.conn:140059621717760:ERROR:16275:Connect attempt to <BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092> returned error 111. Disconnecting.
2017-06-08 14:55:59,459.459.636926651:kafka.conn:140059621717760:INFO:16275:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: Closing connection. ConnectionError: 111
2017-06-08 14:55:59,459.459.760904312:kafka.client:140059621717760:ERROR:16275:Unable to bootstrap from [('localhost', 9092, 0)]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "example.py", line 24, in run
    auto_offset_reset='earliest')
  File "/home/zhihong/dev/kafka-python/kafka/consumer/group.py", line 314, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/zhihong/dev/kafka-python/kafka/client_async.py", line 211, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/zhihong/dev/kafka-python/kafka/client_async.py", line 827, in check_version
    raise Errors.NoBrokersAvailable()
NoBrokersAvailable: NoBrokersAvailable

**Comment by jeffwidman** [comment]
You need to run a Kafka broker for this to work.
