### ISSUE TITLE
MultiProcessConsumer: AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

### ISSUE THREAD

**Issue by avinash-mishra** [dpkp/kafka-python#1143]
I am trying to use kafka MultiProcessConsumer and I got following error. It seems like error is related to multithreading in python 

Here is the code which I am using.

`simple.py`

```
from kafka import SimpleProducer, SimpleClient, SimpleConsumer, MultiProcessConsumer

# To consume messages
client = SimpleClient('localhost:9092')
consumer = MultiProcessConsumer(client, "my-group", "testing_topic", num_procs=3)
for message in consumer:
    # message is raw byte string -- decode if necessary!
    # e.g., for unicode: `message.decode('utf-8')`
    print(message)

client.close()
```
Error while running above code.

`$ python simple.py `

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/managers.py", line 749, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by tvoinarovskyi** [comment]
That one is quite old code, and basically only there for backward compatibility. It's recommended to use a [KafkaConsumer](http://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html) per process for consuming messages in multiprocess setup. You would do something like:

```python
from concurrent import futures
from kafka import KafkaConsumer
import os
import logging


def init_and_consume():
    try:
        print("start consuming on pid={}".format(os.getpid()))
        # To consume latest messages and auto-commit offsets
        consumer = KafkaConsumer(
            'my-topic',
            group_id='multiprocess-group',
            bootstrap_servers=['localhost:9092'])
        for message in consumer:
            # message value and key are raw bytes -- decode if necessary!
            # e.g., for unicode: `message.value.decode('utf-8')`
            print ("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                                  message.offset, message.key,
                                                  message.value))
    except Exception:
        import logging
        logging.exception("Worker process failed", exc_info=True)


def main():
    logging.basicConfig()
    NUM_PROC = 4
    with futures.ProcessPoolExecutor(max_workers=NUM_PROC) as executor:
        futs = [executor.submit(init_and_consume) for _ in range(NUM_PROC)]

        futures.wait(futs)


if __name__ == '__main__':
    main()

```

**Comment by jeffwidman** [comment]
I'm going to close this as `MultiProcessConsumer` is deprecated and will likely be removed in a future release. Please use `KafkaConsumer` instead.
