### ISSUE TITLE
Error Decompressing message LZ4

### ISSUE THREAD

**Issue by philmadden83** [dpkp/kafka-python#1180]
We're using a library from Yelp (https://github.com/Yelp/kafka-utils)  which has a dependency on this lib. When attempting to issue commands using the above util the below error is produced if the cluster has been configured to use LZ4 compression.

### Steps to reproduce:
```
kafka-consumer-manager --cluster-type={file-name-of-config} list_groups
```

### Source
https://github.com/dpkp/kafka-python/blob/master/kafka/protocol/message.py#L130

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kafka/future.py", line 79, in _call_backs
    f(value)
  File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/fetcher.py", line 760, in _handle_fetch_response
    unpacked = list(self._unpack_message_set(tp, messages))
  File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/fetcher.py", line 482, in _unpack_message_set
    inner_mset = msg.decompress()
  File "/usr/local/lib/python2.7/dist-packages/kafka/protocol/message.py", line 129, in decompress
    assert has_lz4(), 'LZ4 decompression unsupported'
AssertionError: LZ4 decompression unsupported
ERROR:kafka.future:Error processing callback
```

**Comment by dpkp** [comment]
http://kafka-python.readthedocs.io/en/master/install.html#optional-lz4-install
