### ISSUE TITLE
OffsetOutOfRange error after seek (by @muhammadomair)

### ISSUE THREAD

**Issue by rdiomar** [dpkp/kafka-python#120]
@muhammadomair wrote:

At the moment the producer script had produced only three messages. Every time I run my consumer script I want to consume only the newer message. I tried to use consumer.seek (2, 0) but I get an exception in the for loop because consumer.seek(2,0) moves the offset three messages forward. 
How can I ensure that I am only able to consume the newer messages. I write the latest offset to a local text file and can resume from there.

consumer = SimpleConsumer(mq.getkafkaserver(), mq.getproducergroup(), mq.getproducer(), auto_commit = False)
consumer.seek(2, 0)

for message in consumer:
print (message.message)
print('offset is {0}'.format(consumer.offsets))

Traceback (most recent call last):
File "fronter_consumer.py", line 47, in 
fronterconsumer = fronter_consumers("config/consumer_config.ini")
File "fronter_consumer.py", line 26, in init
for message in consumer:
File "/usr/local/lib/python2.7/dist-packages/kafka_python-0.9.0-py2.7.egg/kafka/consumer.py", line 394, in iter
message = self.get_message(True, timeout)
File "/usr/local/lib/python2.7/dist-packages/kafka_python-0.9.0-py2.7.egg/kafka/consumer.py", line 353, in get_message
return self.getmessage(block, timeout, get_partition_info)
File "/usr/local/lib/python2.7/dist-packages/kafka_python-0.9.0-py2.7.egg/kafka/consumer.py", line 366, in getmessage
self.fetch()
File "/usr/local/lib/python2.7/dist-packages/kafkapython-0.9.0-py2.7.egg/kafka/consumer.py", line 418, in fetch
minbytes=self.fetch_min_bytes)
File "/usr/local/lib/python2.7/dist-packages/kafka_python-0.9.0-py2.7.egg/kafka/client.py", line 316, in send_fetch_request
self.raiseon_response_error(resp)
File "/usr/local/lib/python2.7/dist-packages/kafka_python-0.9.0-py2.7.egg/kafka/client.py", line 178, in raiseon_response_error
(TopicAndPartition(resp.topic, resp.partition), resp.error))
kafka.common.BrokerResponseError: Request for TopicAndPartition(topic='kafka-producer-100', partition=1) failed with errorcode=1

**Comment by dpkp** [comment]
wontfix -- SimpleConsumer deprecated in favor of KafkaConsumer
