### ISSUE TITLE
Consumer read single entry and exit

### ISSUE THREAD

**Issue by aaronbartell** [dpkp/kafka-python#1207]
I am attempting to write a simple consumer and can't seem to get it working.  My goal is to `seek()` to a specific topic entry, read the next available entry if any, and close the connection.

```py
import sys
from kafka import KafkaConsumer
from kafka.structs import TopicPartition

topic = sys.argv[1]
print(topic)
consumer = KafkaConsumer(topic, bootstrap_servers=['locahost:9092']

consumer.seek( TopicPartition(topic, 0) ,1)
print( consumer.poll(timeout_ms=5000, max_records=1) )
consumer.close()
```

I get the following error.
```
$ python3 /tmp/kafka_consumer.py test
test
Traceback (most recent call last):
  File "/tmp/kafka_consumer.py", line 15, in <module>
    consumer.seek( TopicPartition(topic, 0) ,1)
  File ".../lib/python3.4/site-packages/kafka/consumer/group.py", line 724, in seek
    assert partition in self._subscription.assigned_partitions(), 'Unassigned partition'
AssertionError: Unassigned partition
```

**Comment by dpkp** [comment]
use `consumer.assign` instead of passing the topic to the KafkaConsumer constructor (which is shorthand for `subscribe([topic])`)
