### ISSUE TITLE
Error On Unknown Host Name

### ISSUE THREAD

**Issue by jorgii** [dpkp/kafka-python#1250]
While trying to handle NoBrokersAvailable error I noticed the a threading error thrown in case the hostname that has been provided cannot be resolved.

The following code tries to connect to localhost kafka broker:
```
In [17]: producer = KafkaProducer(bootstrap_servers='localhost:9091')
---------------------------------------------------------------------------
NoBrokersAvailable                        Traceback (most recent call last)
<ipython-input-17-5fe170788885> in <module>()
----> 1 producer = KafkaProducer(bootstrap_servers='localhost:9091')

~/.virtualenvs/website/lib/python3.6/site-packages/kafka/producer/kafka.py in __init__(self, **configs)
    345 
    346         client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
--> 347                              **self.config)
    348 
    349         # Get auto-discovered version from client if necessary

~/.virtualenvs/website/lib/python3.6/site-packages/kafka/client_async.py in __init__(self, **configs)
    218         if self.config['api_version'] is None:
    219             check_timeout = self.config['api_version_auto_timeout_ms'] / 1000
--> 220             self.config['api_version'] = self.check_version(timeout=check_timeout)
    221 
    222     def _bootstrap(self, hosts):

~/.virtualenvs/website/lib/python3.6/site-packages/kafka/client_async.py in check_version(self, node_id, timeout, strict)
    839             try_node = node_id or self.least_loaded_node()
    840             if try_node is None:
--> 841                 raise Errors.NoBrokersAvailable()
    842             self._maybe_connect(try_node)
    843             conn = self._conns[try_node]

NoBrokersAvailable: NoBrokersAvailable
```

But when you provide a hostname that does not exist you get additional trace stack (here I am using ipython for demonstration):
```
In [16]: producer = KafkaProducer(bootstrap_servers='kafka:9091')
  File "/home/ggoranov/.virtualenvs/website/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 480, in mainloop
    self.interact()
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 471, in interact
    self.run_cell(code, store_history=True)
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-840dcb690229>", line 1, in <module>
    producer = KafkaProducer(bootstrap_servers='kafka:9091')
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/kafka/producer/kafka.py", line 347, in __init__
    **self.config)
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/kafka/client_async.py", line 215, in __init__
    self._bootstrap(collect_hosts(self.config['bootstrap_servers']))
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/kafka/client_async.py", line 246, in _bootstrap
    bootstrap.connect()
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/kafka/conn.py", line 287, in connect
    self.close(Errors.ConnectionError(error))
  File "/home/ggoranov/.virtualenvs/website/lib/python3.6/site-packages/kafka/conn.py", line 619, in close
    traceback.print_stack()
---------------------------------------------------------------------------
NoBrokersAvailable                        Traceback (most recent call last)
<ipython-input-16-840dcb690229> in <module>()
----> 1 producer = KafkaProducer(bootstrap_servers='kafka:9091')

~/.virtualenvs/website/lib/python3.6/site-packages/kafka/producer/kafka.py in __init__(self, **configs)
    345 
    346         client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
--> 347                              **self.config)
    348 
    349         # Get auto-discovered version from client if necessary

~/.virtualenvs/website/lib/python3.6/site-packages/kafka/client_async.py in __init__(self, **configs)
    218         if self.config['api_version'] is None:
    219             check_timeout = self.config['api_version_auto_timeout_ms'] / 1000
--> 220             self.config['api_version'] = self.check_version(timeout=check_timeout)
    221 
    222     def _bootstrap(self, hosts):

~/.virtualenvs/website/lib/python3.6/site-packages/kafka/client_async.py in check_version(self, node_id, timeout, strict)
    839             try_node = node_id or self.least_loaded_node()
    840             if try_node is None:
--> 841                 raise Errors.NoBrokersAvailable()
    842             self._maybe_connect(try_node)
    843             conn = self._conns[try_node]

NoBrokersAvailable: NoBrokersAvailable
```

And it seems that even if I try to handle `NoBrokersAvailable` error I still get the upper stack trace.

**Comment by jorgii** [comment]
Hm, looks like the `traceback.print_stack()` prints the error. I am on 1.3.4 whereas the latest is 1.3.5
This fixed the issue for me!
