### ISSUE TITLE
KakfaConsumer is not rebalancing as expected.

### ISSUE THREAD

**Issue by samarendra-fissionhq** [dpkp/kafka-python#1285]
I have the below consumer code and executing the same consumer in parallel,
topicName: "my-topic"
partitions: 3
kafka: 0.11
kafka-python: 1.3.5

```
from kafka import KafkaProducer, KafkaConsumer, TopicPartition, OffsetAndMetadata
import logging
import time
import sys

logger = logging.getLogger()
logger.setLevel(logging.INFO)
ch = logging.StreamHandler(sys.stdout)
ch.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

def kafka_cons():
    con = KafkaConsumer('my-topic', bootstrap_servers='localhost:9092',
                        enable_auto_commit=False, group_id = 'cons2', auto_offset_reset = 'earliest'
                        , session_timeout_ms = 39000, heartbeat_interval_ms=7000)

    for message in con:
        logger.info(message)
        topic_partition = TopicPartition(message.topic, message.partition)
        # partition_list = []
        # partition_list.append(topic_partition)
        # con.assign(partition_list)
        time.sleep(25)
        options = {}
        logger.info(message.offset)
        options[topic_partition] = OffsetAndMetadata(message.offset+1, 0)
        con.commit(options)
        logger.info("---------- commiting offset")
kafka_cons()
```
i am receiving from one of the consumer when i start or stop other consumer(s)

Consumer logs:
```
2017-10-31 21:12:14,677 - root - INFO - ConsumerRecord(topic='my-topic', partition=1, offset=247, timestamp=1509459389882, timestamp_type=0, key=None, value=b'test', checksum=1233756955, serialized_key_size=-1, serialized_value_size=4)
2017-10-31 21:12:39,678 - root - INFO - 247
2017-10-31 21:12:39,683 - root - INFO - ---------- commiting offset
2017-10-31 21:12:39,683 - root - INFO - ConsumerRecord(topic='my-topic', partition=1, offset=248, timestamp=1509459389895, timestamp_type=0, key=None, value=b'test', checksum=-1269710879, serialized_key_size=-1, serialized_value_size=4)
2017-10-31 21:13:04,685 - root - INFO - 248
2017-10-31 21:13:04,689 - root - INFO - ---------- commiting offset
2017-10-31 21:13:04,690 - root - INFO - ConsumerRecord(topic='my-topic', partition=1, offset=249, timestamp=1509459426268, timestamp_type=0, key=None, value=b'test', checksum=-90423648, serialized_key_size=-1, serialized_value_size=4)
2017-10-31 21:13:29,691 - root - INFO - 249
2017-10-31 21:13:29,692 - kafka.coordinator - WARNING - Heartbeat failed for group cons2 because it is rebalancing
2017-10-31 21:13:29,692 - kafka.coordinator - WARNING - Heartbeat failed ([Error 27] RebalanceInProgressError); retrying
Traceback (most recent call last):
  File "test_kafka.py", line 48, in <module>
    kafka_cons()
  File "test_kafka.py", line 29, in kafka_cons
    con.commit(options)
  File "/usr/local/lib/python3.6/site-packages/kafka/consumer/group.py", line 472, in commit
    self._coordinator.commit_offsets_sync(offsets)
  File "/usr/local/lib/python3.6/site-packages/kafka/coordinator/consumer.py", line 398, in commit_offsets_sync
    raise future.exception # pylint: disable-msg=raising-bad-type
kafka.errors.CommitFailedError: CommitFailedError: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session.timeout.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
```

Kafka broker logs:

```
[2017-10-31 21:11:43,469] INFO [GroupCoordinator 0]: Member kafka-python-1.3.5-5e604a2f-742b-4f5e-b46b-f34b29074061 in group cons2 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2017-10-31 21:12:14,562] INFO [GroupCoordinator 0]: Stabilized group cons2 generation 118 (__consumer_offsets-5) (kafka.coordinator.group.GroupCoordinator)
[2017-10-31 21:12:14,567] INFO [GroupCoordinator 0]: Assignment received from leader for group cons2 for generation 118 (kafka.coordinator.group.GroupCoordinator)
[2017-10-31 21:12:43,481] INFO [GroupCoordinator 0]: Preparing to rebalance group cons2 with old generation 118 (__consumer_offsets-5) (kafka.coordinator.group.GroupCoordinator)
[2017-10-31 21:13:22,485] INFO [GroupCoordinator 0]: Stabilized group cons2 generation 119 (__consumer_offsets-5) (kafka.coordinator.group.GroupCoordinator)
[2017-10-31 21:13:22,488] INFO [GroupCoordinator 0]: Assignment received from leader for group cons2 for generation 119 (kafka.coordinator.group.GroupCoordinator)
```

After seeing the logs i feel kafka-python library is not properly listening the rebalancing request.
if you see the broker logs Preparing to rebalance group cons2 happens at 2017-10-31 21:12:43,481
so it issues a rebalancing request to consumer but if you see the consumer logs it still reading the message at 2017-10-31 21:13:04,690, i am expecting it to rebalance instead of reading new message, due to which broker is unable to receive the hear-beat before session timeout time and when its assigning the partition to new consumer which started and commit is getting failed.
Is my understanding correct? i need to resolve this, the commit called is getting failed most of the times when i added a new consumer or removed one consumer while rebalancing. i am using time.sleep() just to illustrate i have long running process.

**Comment by dpkp** [comment]
All group functions happen during the internal poll / iteration step. That means that if you sleep for 25 seconds in the middle of your consumer loop -- which your code above does -- it will generally prevent you from sending heartbeats every 5 seconds and responding to rebalance messages before the session timeout.

**Comment by kostyrev** [comment]
@dpkp where this `5 seconds` setting comes from?

**Comment by dpkp** [comment]
I was referring to `heartbeat_interval_ms`, which actually defaults to 3 secs not 5. But the sleep issue remains.
