### ISSUE TITLE
producer.flush() hangs when request_timeout_ms is given as float

### ISSUE THREAD

**Issue by shimilrahman** [dpkp/kafka-python#1300]
from kafka import KafkaProducer

    producer = KafkaProducer(bootstrap_servers=['localhost:9092'],request_timeout_ms=1200.55)
    producer.send('a',b'b')
    producer.flush()

This will hang indefinitely.
Better option will be to raise an AssertionError at the time of initialization itself

**Comment by jeffwidman** [comment]
I spent some time looking at this. 

`request_timeout_ms` is used to construct the `ProduceRequest` that's sent to the broker. This is encoded into bytes using python structs here: https://github.com/dpkp/kafka-python/blob/master/kafka/protocol/types.py

When I enable debug logging, you can clearly see that the struct is complaining that the value is not an integer:

    2017-12-07 16:29:50,449 - DEBUG - Sending Produce Request: ProduceRequest_v2(required_acks=1, timeout=1200.55, topics=[(topic='a', partitions=[(partition=0, messages=['(offset=0, message=23)'])])])
    2017-12-07 16:29:50,450 - ERROR - Uncaught error in kafka producer I/O thread
    Traceback (most recent call last):
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/protocol/types.py", line 10, in _pack
        return pack(f, value)
    struct.error: required argument is not an integer

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/producer/sender.py", line 60, in run
        self.run_once()
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/producer/sender.py", line 147, in run_once
        (self._client.send(node_id, request)
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/client_async.py", line 497, in send
        return self._conns[node_id].send(request)
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/conn.py", line 663, in send
        return self._send(request)
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/conn.py", line 672, in _send
        message = b''.join([header.encode(), request.encode()])
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/util.py", line 153, in __call__
        return self.method()(self.target(), *args, **kwargs)
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/protocol/struct.py", line 42, in _encode_self
        [self.__dict__[name] for name in self.SCHEMA.names]
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/protocol/types.py", line 124, in encode
        for i, field in enumerate(self.fields)
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/protocol/types.py", line 124, in <listcomp>
        for i, field in enumerate(self.fields)
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/protocol/types.py", line 46, in encode
        return _pack('>i', value)
    File "/Users/jeffwidman/.virtualenvs/kp-jupyter/lib/python3.6/site-packages/kafka/protocol/types.py", line 12, in _pack
        raise ValueError(error)
    ValueError: <class 'struct.error'>

This logging seems a bit confusing, filed #1318 to re-examine that.

I'm also confused why this is hanging--it should fail and either blow up the foreground or mark that particular message as failed and move on. I file #1319 for that.

The error message is unfortunately a bit cryptic as struct is just complaining that an argument is invalid type. 

The best solution here would be if the error message specified which argument specifically was the source of the problem. That would cover errors with many other arguments. I don't know if that's possible.

Additionally, for this particular issue, we could add a check when the `KafkaProducer` is instantiated. That way you don't have to wait to send a message to realize you have a problem. However, my memory is hazy, but I think `request_timeout_ms` is also used in `KafkaConsumer`/`KafkaClient`. If so, we'd probably want to add the check to the `KafkaClient` and not at the consumer/producer layer. I don't have time to finish checking into that right now.

**Comment by jeffwidman** [comment]
Silly silly me, I forgot to test master with this. It's actually fixed there already, looking at wireshark it looks like the `request_timeout_ms` is already cast to an int.

**Comment by jeffwidman** [comment]
Dupe of #1271
