### ISSUE TITLE
kafka-python with kerberos kafka.

### ISSUE THREAD

**Issue by rambai** [dpkp/kafka-python#1336]
Hello everyone!!!
**Confluent 3.0.1 - Kafka and kafka-python-3.0.1
When I use python code:**
```
#!/opt/distr/confluent-3.0.1/venv/bin/python3.4
# coding: utf8

from kafka import KafkaProducer
from kafka import KafkaClient
import logging


logging.basicConfig(filename='example.log',level=logging.DEBUG)
params = {
  'bootstrap_servers': ['<hostname>:9092'],
  'security_protocol': 'SASL_PLAINTEXT',
  'sasl_mechanism': 'GSSAPI',
}

producer = KafkaProducer(**params)
producer.send('testsasl', b'this working code')
producer.flush()
producer.close()
```

**I get following error:**
```
INFO:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: connecting to Server_IP:9092
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: established TCP connection
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: initiating SASL authentication
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092> Request 1: SaslHandShakeRequest_v0(mechanism='GSSAPI')
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092> Response 1: SaslHandShakeResponse_v0(error_code=0, enabled_mechanisms=['PLAIN', 'GSSAPI'])
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: canonical Servicename: kafka/Server_Name@Kerberos_DOMAIN
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: Security Context complete
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: Successful GSSAPI handshake for client@Kerberos_DOMAIN
INFO:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: Authenticated as kafka@Server_Name
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: Connection complete.
DEBUG:kafka.client:Node bootstrap connected
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092> Request 2: MetadataRequest_v0(topics=[])
ERROR:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: socket disconnected
INFO:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: Closing connection. ConnectionError: socket disconnected
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=Server_Name/Server_IP port=9092>: reconnect backoff 0.04484597723684187 after 1 failures
ERROR:kafka.client:Unable to bootstrap from [('Server_Name', 9092, <AddressFamily.AF_UNSPEC: 0>)]
INFO:kafka.producer.kafka:Kafka producer closed
```

**In Kafka logs I see following:**
```
[2018-01-07 21:24:36,475] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:36,488] DEBUG Set SASL server state to HANDSHAKE_REQUEST (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:36,489] DEBUG Handle Kafka request SASL_HANDSHAKE (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:36,489] DEBUG Using SASL mechanism 'GSSAPI' provided by client (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:36,489] DEBUG Creating SaslServer for kafka/Server_Name@Kerberos_DOMAIN with mechanism GSSAPI (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:36,491] DEBUG Set SASL server state to AUTHENTICATE (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:36,521] INFO Successfully authenticated client: authenticationID=client@Kerberos_DOMAIN; authorizationID=client@Kerberos_DOMAIN. (org.apache.kafka.common.security.authenticator.SaslServerCallbackHandler)
[2018-01-07 21:24:36,521] INFO Setting authorizedID: client (org.apache.kafka.common.security.authenticator.SaslServerCallbackHandler)
[2018-01-07 21:24:36,521] DEBUG Set SASL server state to COMPLETE (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:37,612] DEBUG Set SASL server state to HANDSHAKE_REQUEST (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:37,612] DEBUG Handle Kafka request SASL_HANDSHAKE (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:37,612] DEBUG Using SASL mechanism 'GSSAPI' provided by client (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:37,612] DEBUG Creating SaslServer for kafka/Server_Name@Kerberos_DOMAIN with mechanism GSSAPI (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:37,613] DEBUG Set SASL server state to AUTHENTICATE (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:37,620] INFO Successfully authenticated client: authenticationID=client@Kerberos_DOMAIN; authorizationID=client@Kerberos_DOMAIN. (org.apache.kafka.common.security.authenticator.SaslServerCallbackHandler)
[2018-01-07 21:24:37,620] INFO Setting authorizedID: client (org.apache.kafka.common.security.authenticator.SaslServerCallbackHandler)
[2018-01-07 21:24:37,620] DEBUG Set SASL server state to COMPLETE (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:24:37,643] DEBUG Added sensor with name ProduceThrottleTime-console-producer (org.apache.kafka.common.metrics.Metrics)
[2018-01-07 21:24:37,643] DEBUG Added sensor with name Produce-console-producer (org.apache.kafka.common.metrics.Metrics)
[2018-01-07 21:24:38,478] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:40,479] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:42,481] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:44,484] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:46,486] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:48,489] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:50,491] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:52,494] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:54,495] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:56,498] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:24:58,499] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:25:00,501] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:25:02,504] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:25:02,605] DEBUG Set SASL server state to HANDSHAKE_REQUEST (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:25:02,605] DEBUG Handle Kafka request SASL_HANDSHAKE (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:25:02,605] DEBUG Using SASL mechanism 'GSSAPI' provided by client (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:25:02,605] DEBUG Creating SaslServer for kafka/Server_Name@Kerberos_DOMAIN with mechanism GSSAPI (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:25:02,606] DEBUG Set SASL server state to AUTHENTICATE (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:25:02,609] DEBUG Set SASL server state to FAILED (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2018-01-07 21:25:02,609] DEBUG Connection with /Server_IP disconnected (org.apache.kafka.common.network.Selector)
java.io.IOException: javax.security.sasl.SaslException: Handshake expecting no response data from server
        at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:243)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:64)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:318)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:283)
        at kafka.network.Processor.poll(SocketServer.scala:472)
        at kafka.network.Processor.run(SocketServer.scala:412)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.security.sasl.SaslException: Handshake expecting no response data from server
        at com.sun.security.sasl.gsskerb.GssKrb5Server.doHandshake1(GssKrb5Server.java:209)
        at com.sun.security.sasl.gsskerb.GssKrb5Server.evaluateResponse(GssKrb5Server.java:158)
        at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:228)
        ... 6 more
[2018-01-07 21:25:04,506] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:25:06,509] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
[2018-01-07 21:25:08,510] DEBUG Got ping response for sessionid: 0x160c74c65dd0000 after 0ms (org.apache.zookeeper.ClientCnxn)
```
**Please help to solve this issue.**

**Comment by dpkp** [comment]
have you tried the latest `master`? There are critical patches to kerberos that have not been released to pypi yet.

**Comment by rambai** [comment]
Hi, thank You for advice, I think the problem was that we haven't installed librdkafka, we solved the issue installing librdkafka and confluent-kafka package, and used it in our project.

**Comment by jeffwidman** [comment]
I think you might have `kafka-python` confused with `confluent-kafka-python`... they are different projects with different goals.

**Comment by dpkp** [comment]
Nonetheless, I'm glad you found a solution to your problem!

**Comment by ravikiranks** [comment]
@jeffwidman  Could you please elaborate on this? both seems to be client packages for consumption and production of messages into kafka, isn't it?

 "I think you might have kafka-python confused with confluent-kafka-python... they are different projects with different goals."

**Comment by jeffwidman** [comment]
Yes, they are both python libraries used to create kafka consumers/producers.

`kafka-python` is pure python, so will be slower to produce / consume, although it send / pre-fetches messages using a buffer so unless your business logic is super fast this shouldn't matter much. It will be faster to debug in production since it's pure python. And it is basically a port of the Java reference implementation so it will generally be faster for someone comfortable with Kafka to understand what's happening because the semantics are consistent.

The `confluent-kafka-python` wraps `librdkafka` which is C-based. So message throughput will be faster by a huge margin, as long as your business logic isn't the bottleneck. Many languages have `librdkafka` wrappers, so if you're supporting multiple languages, this can be useful to have only one core piece of code to understand. Because it's C, sometimes there can be packaging issues. Also more difficult to debug sometimes because you can't just drop into `pdb` willy-nilly to examine stuff.

There are pros/cons to both. The feature comparison shows each library is ahead/behind in different areas. This library is maintained by volunteers, whereas `confluent-kafka-python` is maintained by two really nice guys (hi @edenhill / @mhowlett) who are paid by confluent so they may pull ahead on features over time, although their time is divided among several different clients so they can't move as fast as they'd like. Really depends what you're looking for, how many teams/services you're supporting, how you want to handle production emergencies, etc.

HTH!

**Comment by Sudheer312** [comment]
Is it possible to connect a kerberized kafka cluster with keytab from python using kafka-python 1.4.6 or should i move to confluent-kafka-python.

**Comment by Sudheer312** [comment]
> Hi, thank You for advice, I think the problem was that we haven't installed librdkafka, we solved the issue installing librdkafka and confluent-kafka package, and used it in our project.

HI, could you please provide some refernces on how to connect kerberized kafka from python with some examples.

**Comment by amritanshu-pandey** [comment]
Hi guys, can someone please answer @Sudheer312 questions. We are also looking for a python based solution to connect to a Kerberos and TLS enabled Kafka cluster.

> Is it possible to connect a kerberized kafka cluster with keytab from python using kafka-python 1.4.6 or should i move to confluent-kafka-python

**Comment by thomasthebaker** [comment]
You can use kafka-python with a kerberised Kafka cluster, I've managed to do it using version 1.4.3. Here are the steps for anyone else wanting to try it out:

1. Install gssapi python module which is a wrapper for the gssapi C libraries: https://pypi.org/project/gssapi/
2. Create a kerberos keytab for your Kerberos server.
3. Set KRB5_CLIENT_KTNAME environment variable to point to your new keytab
4. Make sure you have a certificate file to verify the SSL certificates you've installed on the Kafka cluster. In my case the Kafka TLS connection required verification with a local certificate authority file that has my organisations sigining certificate authority.

```
# Note, you must have the keytab env variable set, e.g.:
# KRB5_CLIENT_KTNAME=/home/myuser/some_kerberos.keytab
from kafka import KafkaProducer
from datetime import datetime as dt
import ssl
 
broker='<your broker>:9092'
 
# point ssl lib to a certificate file that will work for your Kafka cluster
ssl_context = ssl.create_default_context(cafile='/etc/pki/tls/certs/ca-bundle.crt')
 
producer = KafkaProducer(bootstrap_servers=broker,
                        security_protocol='SASL_SSL',
                        sasl_mechanism='GSSAPI',
                        ssl_context=ssl_context)
msg = f'test-{dt.utcnow().isoformat()}'
meta = producer.send(topic='some-topic', value=msg.encode('utf-8'))
```

I also found it quite useful to use the Kafka shell scripts to test things out, so I had a consumer for the same topic using a command line like this:
```
kafka-console-consumer.sh --topic some-topic --from-beginning --consumer.config ~/kafka-jaas.conf --bootstrap-server <your broker>:9092
```

Which used the following kafka-jaas.conf file (note you have to create the ssl truststore from the same certificate as used in the python version):
```
ssl.truststore.location=/truststorefile
ssl.truststore.password=password
 
sasl.mechanism=GSSAPI
# Configure SASL_SSL if SSL encryption is enabled, otherwise configure SASL_PLAINTEXT
security.protocol=SASL_SSL
 
sasl.kerberos.service.name=kafka
 
sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required \
    useKeyTab=true \
    storeKey=false \
    debug=true \
    keyTab="local_kerberos.keytab" \
    principal="user@DOMAIN.COM";
```

**Comment by chan71** [comment]
Thanks @thomasthebaker for your answer. I tried step 1-3 without 4 as our's doesn't use TLS. It doesn't however work.
Env:
kafka-python 2.0.2
python 2.7
HDF 3.5.2 (HDP 3.1)
As pet this post (bit old though) one has to kinit with keytab before running the script. https://community.cloudera.com/t5/Community-Articles/Running-a-producer-in-a-kerberized-HDP-3-1-Kafka-2-0-0/ta-p/244205
But I am exploring the possibility of using the kerberos keytab programatically in kafka-python to avoid having to call kinit every time the script is run.
