### ISSUE TITLE
socket disconnected with SSL listener

### ISSUE THREAD

**Issue by geez** [dpkp/kafka-python#1355]
Hi all,

Currently testing the datadog kafka_consumer check which uses kafka-python.
When specifying "kafka_connect_str" to host:9093, I end up with `socket disconnected`.
Port connectivity is ok, wondering if something is missing when connecting to SSL listeners.

```
2018-01-24 18:27:05 UTC | INFO | dd.collector | kafka.client(client_async.py:223) | Bootstrapping cluster metadata from [('kafka-infra-1.domain', 9093, 0)]
2018-01-24 18:27:05 UTC | INFO | dd.collector | kafka.conn(conn.py:306) | <BrokerConnection node_id=bootstrap host=kafka-infra-1.domain/10.104.50.99 port=9093>: connecting to 10.104.50.99:9093
2018-01-24 18:27:05 UTC | ERROR | dd.collector | kafka.conn(conn.py:781) | <BrokerConnection node_id=bootstrap host=kafka-infra-1.domain/10.104.50.99 port=9093>: socket disconnected
2018-01-24 18:27:05 UTC | INFO | dd.collector | kafka.conn(conn.py:622) | <BrokerConnection node_id=bootstrap host=kafka-infra-1.domain/10.104.50.99 port=9093>: Closing connection. ConnectionError: socket disconnected
2018-01-24 18:27:05 UTC | ERROR | dd.collector | kafka.client(client_async.py:274) | Unable to bootstrap from [('kafka-infra-1.domain', 9093, 0)]
2018-01-24 18:27:05 UTC | ERROR | dd.collector | checks.kafka_consumer(__init__.py:812) | Check 'kafka_consumer' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 795, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/kafka_consumer.py", line 99, in check
    cli = self._get_kafka_client(instance)
  File "/opt/datadog-agent/agent/checks.d/kafka_consumer.py", line 177, in _get_kafka_client
    cli = KafkaClient(bootstrap_servers=kafka_conn_str, client_id='dd-agent')
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/kafka/client_async.py", line 220, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/kafka/client_async.py", line 841, in check_version
    raise Errors.NoBrokersAvailable()
NoBrokersAvailable: NoBrokersAvailable
# nc -zv 10.104.50.99 9093
ip-10-104-50-99.domain [10.104.50.99] 9093 (?) open
```

Thanks in advance,
G.

**Comment by dpkp** [comment]
Are you also setting `security_protocol='SSL'` ?

**Comment by geez** [comment]
@dpkp Many thanks for the prompt reply mate, apparently SSL is not handled by the kafka datadog check yet, there's a pending PR for it (https://github.com/DataDog/integrations-core/pull/1001).

Cheers,
G.
