### ISSUE TITLE
Kafka Consumer tries to pop from empty deque

### ISSUE THREAD

**Issue by sarimak** [dpkp/kafka-python#1377]
After upgrading from python-kafka 1.3.5 to 1.4.0 we observed the following unhandled exception. The exception occured only randomly and not too often and was observed only under a production load, not under automated functional tests of our application.

```
Traceback (most recent call last):
...
File "<our app>.py", line 44, in <our method>
    for event in kafka_consumer:
File "/usr/local/lib/python2.7/site-packages/kafka/vendor/six.py", line 561, in next
    return type(self).__next__(self)
File "/usr/local/lib/python2.7/site-packages/kafka/consumer/group.py", line 1117, in __next__
    return next(self._iterator)
File "/usr/local/lib/python2.7/site-packages/kafka/consumer/group.py", line 1061, in _message_generator
    self._client.poll(timeout_ms=poll_ms)
File "/usr/local/lib/python2.7/site-packages/kafka/client_async.py", line 577, in poll
    responses.extend(self._fire_pending_completed_requests())
File "/usr/local/lib/python2.7/site-packages/kafka/client_async.py", line 669, in _fire_pending_completed_requests
    response, future = self._pending_completion.popleft()
IndexError: pop from an empty deque
```

**Comment by dpkp** [comment]
Dup of #1371 (please upgrade to 1.4.1)
