### ISSUE TITLE
RuntimeError: deque mutated during iteration

### ISSUE THREAD

**Issue by aptiko** [dpkp/kafka-python#1399]
This is 1.4.1. It's been busy for several hours and at some point it terminated with this:

```
Traceback (most recent call last):
[...]
  File "[...]/kafka/consumer/group.py", line 603, in poll
    records = self._poll_once(remaining, max_records)
  File "[...]/kafka/consumer/group.py", line 643, in _poll_once
    self._fetcher.send_fetches()
  File "[...]/kafka/consumer/fetcher.py", line 131, in send_fetches
    for node_id, request in six.iteritems(self._create_fetch_requests()):
  File "[...]/kafka/consumer/fetcher.py", line 652, in _create_fetch_requests
    for partition in self._fetchable_partitions():
  File "[...]/kafka/consumer/fetcher.py", line 636, in _fetchable_partitions
    for fetch in self._completed_fetches:
RuntimeError: deque mutated during iteration
```

(Ubuntu 16.04 amd64, Python 3.5.2)

**Comment by dpkp** [comment]
This appears to be another thread coordination bug. The code in fetcher.py in your traceback should always run in the main thread. But it is possible that the new heartbeat thread could end up processing a `_handle_fetch_response`, and that callback will mutate self._completed_fetches, which could lead to this exception. Thank you for the bug report -- will fix!

**Comment by dpkp** [comment]
Fix merged to master.
