### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by vineetgoel** [dpkp/kafka-python#1409]
I am getting the following error on a given offset. Note that even if I keep seeking ahead, I keep getting the same error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/foo/env/lib/python3.6/site-packages/kafka/consumer/group.py", line 1075, in __next__
    return next(self._iterator)
  File "/home/foo/env/lib/python3.6/site-packages/kafka/consumer/group.py", line 1013, in _message_generator
    self._client.poll(timeout_ms=poll_ms)
  File "/home/foo/env/lib/python3.6/site-packages/kafka/client_async.py", line 554, in poll
    responses.extend(self._poll(timeout))
  File "/home/foo/env/lib/python3.6/site-packages/kafka/client_async.py", line 603, in _poll
    responses.extend(conn.recv()) # Note: conn.recv runs callbacks / errbacks
  File "/home/foo/env/lib/python3.6/site-packages/kafka/conn.py", line 730, in recv
    response = self._recv()
  File "/home/foo/env/lib/python3.6/site-packages/kafka/conn.py", line 755, in _recv
    responses.extend(self.receive_bytes(data))
  File "/home/foo/env/lib/python3.6/site-packages/kafka/conn.py", line 813, in receive_bytes
    resp = self._process_response(self._rbuffer)
  File "/home/foo/env/lib/python3.6/site-packages/kafka/conn.py", line 861, in _process_response
    response = ifr.response_type.decode(read_buffer)
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/struct.py", line 49, in decode
    return cls(*[field.decode(data) for field in cls.SCHEMA.fields])
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/struct.py", line 49, in <listcomp>
    return cls(*[field.decode(data) for field in cls.SCHEMA.fields])
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/types.py", line 169, in decode
    return [self.array_of.decode(data) for _ in range(length)]
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/types.py", line 169, in <listcomp>
    return [self.array_of.decode(data) for _ in range(length)]
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/types.py", line 128, in decode
    return tuple([field.decode(data) for field in self.fields])
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/types.py", line 128, in <listcomp>
    return tuple([field.decode(data) for field in self.fields])
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/types.py", line 169, in decode
    return [self.array_of.decode(data) for _ in range(length)]
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/types.py", line 169, in <listcomp>
    return [self.array_of.decode(data) for _ in range(length)]
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/types.py", line 128, in decode
    return tuple([field.decode(data) for field in self.fields])
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/types.py", line 128, in <listcomp>
    return tuple([field.decode(data) for field in self.fields])
  File "/home/foo/env/lib/python3.6/site-packages/kafka/protocol/message.py", line 192, in decode
    bytes_to_read -= 8 + 4 + len(msg_bytes)
TypeError: object of type 'NoneType' has no len()
```

Wonder what could be the cause and if there is a way to move forward?

**Comment by dpkp** [comment]
That is a very strange error. It seems as if the message you are receiving is not structured properly. Are you able to read this message via the java client and/or the apache console consumer script?

**Comment by vineetgoel** [comment]
I was able to read this message using the confluent kafka python library

**Comment by dpkp** [comment]
Is the topic compressed? Is it compacted? Any other details you can provide?

**Comment by tvoinarovskyi** [comment]
@vineetgoel What version of `kafka-python` did you use? Seems like `kafka-python==1.3.5`, is that correct?

**Comment by vineetgoel** [comment]
I noticed that the error was reproducible upon using a confluent-kafka-python library too. So it is unlikely this is a kafka-python library thing. But I have seen the errors go up considerably. I am using log compacted topics.

**Comment by jeffwidman** [comment]
What broker version?

**Comment by vineetgoel** [comment]
Broker 0.10.2.1-2

**Comment by dpkp** [comment]
A "message" in kafka is encoded as an (Int64 offset, Bytes payload). The v0 payload is encoded as (Int32 crc, Int8 magic, Int8 attributes_flags, Bytes key, Bytes value). v1 payload adds an Int64 timestamp. There is also a newer v2 format, but it is not used by 0.10 brokers.

In your case we are able to decode the offset but the payload is empty -- it is a 0-length byte field. As far as I know that is not supposed to ever happen in data coming back from a kafka broker. Every payload should decode into the full field list above w/ keys and values. So we could improve the error message here, but it does seem like this is a bug in the data returned by the kafka 0.10 broker.

**Comment by jeffwidman** [comment]
Given that this was observed under both `kafka-python` and `confluent-kafka-python`, I think it's safe to say that it's a bug in the broker... I'm going to close this. Happy to re-open if it's a library issue.
