### ISSUE TITLE
Help: kafka.errors.NoBrokersAvailable: NoBrokersAvailable on centos

### ISSUE THREAD

**Issue by shiv-shankar** [dpkp/kafka-python#1431]
Running a single node kafka cluster on localhost:2181 centos OS
Invoking KafkaProducer for the server
producer = KafkaProducer(bootstrap_servers='localhost:2181')
when i execute it i get a No broker available issue

Kafka seems to be working with the KAFKA CLI without python program and i am able to send and receive message. But when i use Python this error comes.

Enabled debugging logs and have the below logs when i start the producer
2018-03-09 11:42:35,967.967.98491478:kafka.producer.kafka:140425784379200:DEBUG:32054:Starting the Kafka producer
2018-03-09 11:42:35,968.968.45293045:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name connections-closed
2018-03-09 11:42:35,968.968.631029129:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name connections-created
2018-03-09 11:42:35,968.968.82891655:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name select-time
2018-03-09 11:42:35,969.969.044923782:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name io-time
2018-03-09 11:42:35,969.969.269990921:kafka.client:140425784379200:INFO:32054:Bootstrapping cluster metadata from [('localhost', 2181, 0)]
2018-03-09 11:42:35,969.969.403982162:kafka.client:140425784379200:DEBUG:32054:Attempting to bootstrap via node at localhost:2181
2018-03-09 11:42:35,969.969.542980194:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name bytes-sent-received
2018-03-09 11:42:35,969.969.686985016:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name bytes-sent
2018-03-09 11:42:35,969.969.918966293:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name bytes-received
2018-03-09 11:42:35,970.970.227003098:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name request-latency
2018-03-09 11:42:35,970.970.380067825:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name node-bootstrap.bytes-sent
2018-03-09 11:42:35,970.970.576047897:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name node-bootstrap.bytes-received
2018-03-09 11:42:35,970.970.748901367:kafka.metrics.metrics:140425784379200:DEBUG:32054:Added sensor with name node-bootstrap.latency
2018-03-09 11:42:35,971.971.342086792:kafka.conn:140425784379200:DEBUG:32054:<BrokerConnection node_id=bootstrap host=localhost/localhost port=2181>: creating new socket
2018-03-09 11:42:35,971.971.504926682:kafka.conn:140425784379200:DEBUG:32054:<BrokerConnection node_id=bootstrap host=localhost/::1 port=2181>: setting socket option (6, 1, 1)
2018-03-09 11:42:35,971.971.632003784:kafka.conn:140425784379200:INFO:32054:<BrokerConnection node_id=bootstrap host=localhost/::1 port=2181>: connecting to ::1:2181
2018-03-09 11:42:35,971.971.923112869:kafka.conn:140425784379200:DEBUG:32054:<BrokerConnection node_id=bootstrap host=localhost/::1 port=2181>: established TCP connection
2018-03-09 11:42:35,972.972.07403183:kafka.conn:140425784379200:DEBUG:32054:<BrokerConnection node_id=bootstrap host=localhost/::1 port=2181>: Connection complete.
2018-03-09 11:42:35,972.972.225904465:kafka.client:140425784379200:DEBUG:32054:Node bootstrap connected
2018-03-09 11:42:35,972.972.467899323:kafka.protocol.parser:140425784379200:DEBUG:32054:Sending request MetadataRequest_v0(topics=[])
2018-03-09 11:42:35,972.972.872972488:kafka.conn:140425784379200:DEBUG:32054:<BrokerConnection node_id=bootstrap host=localhost/::1 port=2181> Request 1: MetadataRequest_v0(topics=[])
2018-03-09 11:42:35,973.973.078966141:kafka.conn:140425784379200:ERROR:32054:<BrokerConnection node_id=bootstrap host=localhost/::1 port=2181>: socket disconnected
2018-03-09 11:42:35,973.973.170995712:kafka.conn:140425784379200:INFO:32054:<BrokerConnection node_id=bootstrap host=localhost/::1 port=2181>: Closing connection. ConnectionError: socket disconnected
2018-03-09 11:42:35,973.973.321914673:kafka.conn:140425784379200:DEBUG:32054:<BrokerConnection node_id=bootstrap host=localhost/::1 port=2181>: reconnect backoff 0.0420615814743 after 1 failures
2018-03-09 11:42:35,973.973.470926285:kafka.conn:140425784379200:INFO:32054:<BrokerConnection node_id=bootstrap host=localhost/::1 port=2181>: Closing connection.
2018-03-09 11:42:35,973.973.550081253:kafka.conn:140425784379200:DEBUG:32054:<BrokerConnection node_id=bootstrap host=localhost/::1 port=2181>: reconnect backoff 0.102721924163 after 2 failures
2018-03-09 11:42:35,973.973.680019379:kafka.client:140425784379200:ERROR:32054:Unable to bootstrap from [('localhost', 2181, 0)]
Traceback (most recent call last):
  File "./ka_prod.py", line 34, in <module>
    main()
  File "./ka_prod.py", line 25, in main
    connect_producer(connect_list)
  File "./ka_prod.py", line 11, in connect_producer
    producer = KafkaProducer(bootstrap_servers='localhost:2181')
  File "/usr/lib/python2.7/kafka/producer/kafka.py", line 363, in __init__
    **self.config)
  File "/usr/lib/python2.7/kafka/client_async.py", line 234, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/lib/python2.7/kafka/client_async.py", line 836, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
2018-03-09 11:42:35,977.977.602005005:kafka.producer.kafka:140425784379200:INFO:32054:Kafka producer closed

The hosts file on the box has the following interface
/etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 test131163
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 test131163

Not sure if the issue is same as the one discussed below
https://github.com/dpkp/kafka-python/issues/1308

Tried the api_version workaround but the issue did not go away. However, i do not know how to get fix 1411 suggested by dpkp and check if things work out.
Steps i have followed to get the fix.
- took the code drop containing the fix
- make and make install
- copied the kafka folder into the library path indicated by sys.path
Not sure if i performed the right or all steps 

Could someone help to get this issue fixed?

Thanks in advance
Shiv

**Comment by tvoinarovskyi** [comment]
As it seems to me you are trying to connect via `zookeeper` port. Try `localhost:9092`

**Comment by dpkp** [comment]
Agree -- 2181 is almost certainly not the port you want.
