### ISSUE TITLE
NoBrokersAvailable when using bootstrap_server list

### ISSUE THREAD

**Issue by thspinto** [dpkp/kafka-python#1440]
I'm getting the `kafka.errors.NoBrokersAvailable: NoBrokersAvailable` specifically when I use an URL list on the bootstrap_server configuration (e.g. kb1.server:9092,kb2.server:9092,kb3.server:9092).

Version Info:
Kafka: 1.0.1
kafka-python: 1.4.2
 
```
03/12/2018 19:15:29 - kafka.protocol.parser - DEBUG - Sending request FetchRequest_v4(replica_id=-1, max_wait_time=500, min_bytes=1, max_bytes=52428800, isolation_level=0, topics=[(topic='ModelEvent', partitions=[(partition=0, offset=0, max_bytes=1048576)]), (topic='Inspection', partitions=[(partition=0, offset=0, max_bytes=1048576)]), (topic='InspectionDumperTriggerTopic', partitions=[(partition=0, offset=0, max_bytes=1048576)])])
03/12/2018 19:15:29 - kafka.conn - DEBUG - <BrokerConnection node_id=0 host=10.6.3.105:9092 <connected> [IPv4 ('10.6.3.105', 9092)]> Request 8: FetchRequest_v4(replica_id=-1, max_wait_time=500, min_bytes=1, max_bytes=52428800, isolation_level=0, topics=[(topic='ModelEvent', partitions=[(partition=0, offset=0, max_bytes=1048576)]), (topic='Inspection', partitions=[(partition=0, offset=0, max_bytes=1048576)]), (topic='InspectionDumperTriggerTopic', partitions=[(partition=0, offset=0, max_bytes=1048576)])])
03/12/2018 19:15:29 - kafka.consumer.fetcher - DEBUG - Sending FetchRequest to node 1
03/12/2018 19:15:29 - kafka.protocol.parser - DEBUG - Sending request FetchRequest_v4(replica_id=-1, max_wait_time=500, min_bytes=1, max_bytes=52428800, isolation_level=0, topics=[(topic='UserEntity', partitions=[(partition=0, offset=0, max_bytes=1048576)]), (topic='OnboardingDumperTriggerTopic', partitions=[(partition=0, offset=1, max_bytes=1048576)])])
03/12/2018 19:15:29 - kafka.conn - DEBUG - <BrokerConnection node_id=1 host=10.6.3.56:9092 <connected> [IPv4 ('10.6.3.56', 9092)]> Request 5: FetchRequest_v4(replica_id=-1, max_wait_time=500, min_bytes=1, max_bytes=52428800, isolation_level=0, topics=[(topic='UserEntity', partitions=[(partition=0, offset=0, max_bytes=1048576)]), (topic='OnboardingDumperTriggerTopic', partitions=[(partition=0, offset=1, max_bytes=1048576)])])
03/12/2018 19:15:29 - kafka.consumer.fetcher - DEBUG - Sending FetchRequest to node 2
03/12/2018 19:15:29 - kafka.protocol.parser - DEBUG - Sending request FetchRequest_v4(replica_id=-1, max_wait_time=500, min_bytes=1, max_bytes=52428800, isolation_level=0, topics=[(topic='Onboarding', partitions=[(partition=0, offset=0, max_bytes=1048576)]), (topic='ContractDumperTriggerTopic', partitions=[(partition=0, offset=1, max_bytes=1048576)])])
03/12/2018 19:15:30 - kafka.conn - DEBUG - <BrokerConnection node_id=2 host=10.6.2.68:9092 <connected> [IPv4 ('10.6.2.68', 9092)]> Request 2: FetchRequest_v4(replica_id=-1, max_wait_time=500, min_bytes=1, max_bytes=52428800, isolation_level=0, topics=[(topic='Onboarding', partitions=[(partition=0, offset=0, max_bytes=1048576)]), (topic='ContractDumperTriggerTopic', partitions=[(partition=0, offset=1, max_bytes=1048576)])])
03/12/2018 19:15:30 - missioncontrolsonar.worker_manager - INFO - Return: start_shutdown(WorkerManager,<Task finished coro=<worker_loop() done, defined at /app/missioncontrolsonar/worker_manager.py:73> result=None>) = WorkerManager
03/12/2018 19:15:30 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<worker_loop() done, defined at /app/missioncontrolsonar/worker_manager.py:73> exception=NoBrokersAvailable()>
Traceback (most recent call last):
  File "/app/missioncontrolsonar/worker_manager.py", line 80, in worker_loop
    await task
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/missioncontrol/services/kafka/message_producer.py", line 32, in process
    return self.kafka_producer.flush(self.flush_timeout_secs)
  File "/app/missioncontrol/services/kafka/message_producer.py", line 44, in kafka_producer
    retries=3
  File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 362, in __init__
    **self.config)
  File "/usr/local/lib/python3.6/site-packages/kafka/client_async.py", line 219, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/local/lib/python3.6/site-packages/kafka/client_async.py", line 819, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

**Comment by tvoinarovskyi** [comment]
Did it work properly with kafka-python==1.4.1? Can you check?

**Comment by thspinto** [comment]
Same error on `1.4.1`. I was using version `1.3.5` before and also got this error.

**Comment by tvoinarovskyi** [comment]
Then you just don't have connection to the cluster. Even telneting to those ports should not work.

**Comment by HansG89** [comment]
Same problem here when using kafka-python consumer in docker container.
On the host system everything is fine. But when running in docker python:3.6 container the connection fails with exactly the same error message.
I'm using the brokers IP address in bootstrap_servers parameter.
Pinging this address from within the container works. Also a telnet connection to the required port is possible.

**Comment by ox123** [comment]
So, is anybody who knows this reason and have any ideas to resolve it?

**Comment by HansG89** [comment]
Which OS your docker is running on? I'm using Ubuntu 18.04 and I figured out that the problem has something to do with dockers bridged network mode. So basically it looks like a routing problem.
When I start my container in host network mode, everything works like a charm.

**Comment by bmamouri** [comment]
The error message is very misguiding. You need to specify the api_version in your consumer connection:

```
consumer = KafkaConsumer(
    bootstrap_servers=settings.message_hub.brokers,
    api_version=(0, 11, 5),  # MUST be specified or NoBrokersAvailable error would be raised
)
```

**Comment by jeffwidman** [comment]
@bmamouri there is more context in https://github.com/dpkp/kafka-python/issues/1308#issuecomment-365378462 and the rest of that ticket...

**Comment by bmamouri** [comment]
@jeffwidman Actually, you are quite right. Specifying the api_version resolve the connection problem, but the consumer does not work. I read the ticket you provided, and although I am using 1.4.4 I still can't consume any messages.

**Comment by Hassan-404** [comment]
@jeffwidman, by using your fix I run the consumer but it stuck on fetching records from specified topic, What can I do?
