### ISSUE TITLE
NameError: name 'memoryview' is not defined

### ISSUE THREAD

**Issue by axil76** [dpkp/kafka-python#1465]
Hello ,
I am in python 2.6.6 and I installed kafka-python, I use a python script that uses the KafkaConsumer, KafkaProducer, KafkaError, TopicPartition libraries .
I have the following error message 

Traceback (most recent call last):

  File "./check_kafka.py", line 49, in <module>
    from kafka import KafkaConsumer, KafkaProducer
  File "/usr/lib/python2.6/site-packages/kafka_python-1.4.3.dev-py2.6.egg/kafka/__init__.py", line 21, in <module>
    from kafka.consumer import KafkaConsumer
  File "/usr/lib/python2.6/site-packages/kafka_python-1.4.3.dev-py2.6.egg/kafka/consumer/__init__.py", line 5, in <module>
    from kafka.consumer.group import KafkaConsumer
  File "/usr/lib/python2.6/site-packages/kafka_python-1.4.3.dev-py2.6.egg/kafka/consumer/group.py", line 13, in <module>
    from kafka.consumer.fetcher import Fetcher
  File "/usr/lib/python2.6/site-packages/kafka_python-1.4.3.dev-py2.6.egg/kafka/consumer/fetcher.py", line 19, in <module>
    from kafka.record import MemoryRecords
  File "/usr/lib/python2.6/site-packages/kafka_python-1.4.3.dev-py2.6.egg/kafka/record/__init__.py", line 1, in <module>
    from kafka.record.memory_records import MemoryRecords
  File "/usr/lib/python2.6/site-packages/kafka_python-1.4.3.dev-py2.6.egg/kafka/record/memory_records.py", line 27, in <module>
    from kafka.record.default_records import DefaultRecordBatch, DefaultRecordBatchBuilder
  File "/usr/lib/python2.6/site-packages/kafka_python-1.4.3.dev-py2.6.egg/kafka/record/default_records.py", line 338, in <module>
    class DefaultRecordBatchBuilder(DefaultRecordBase, ABCRecordBatchBuilder):
  File "/usr/lib/python2.6/site-packages/kafka_python-1.4.3.dev-py2.6.egg/kafka/record/default_records.py", line 378, in DefaultRecordBatchBuilder
    byte_like=(bytes, bytearray, memoryview),
 
what is the problem?
Thanks .

**Comment by dpkp** [comment]
python 2.6 is no longer supported as of 1.4. You will need to stay at 1.3.5
or upgrade. Hopefully you can get to py3 soon!
