### ISSUE TITLE
Not able to consume messages within Airflow environment

### ISSUE THREAD

**Issue by WesleyBatista** [dpkp/kafka-python#1484]
Hi everybody!

I am currently trying to write a Airflow Operator, which the main idea is to consume some messages and send them to S3.

Unfortunately, I am not able to do it because I got stuck with this problem today, that I am not sure what it is.

The application reachs the kafka cluster, join to the proper consumer group, but them it leaves the group.

I'd like to share here, and hopefully get some help on figuring out what is happening.

```
Starting attempt 2 of 3
--------------------------------------------------------------------------------

[2018-05-02 05:09:03,914] {models.py:1342} INFO - Executing <Task(KafkaToS3Operator): kafka_consumer> on 2018-05-01 00:00:00
[2018-05-02 05:09:03,951] {client_async.py:222} INFO - Bootstrapping cluster metadata from [(u'kafka-01.easyservices.net.co', 9092, 0), (u'kafka-05.easyservices.net.co', 9092, 0), (u'kafka-02.easyservices.net.co', 9092, 0), (u'kafka-03.easyservices.net.co', 9092, 0), (u'kafka-04.easyservices.net.co', 9092, 0)]
[2018-05-02 05:09:03,958] {conn.py:350} INFO - <BrokerConnection node_id=bootstrap host=kafka-01.easyservices.net.co:9092 <connecting> [IPv4 ('x.x.x.x', 9092)]>: connecting to kafka-01.easyservices.net.co:9092 [('x.x.x.x', 9092) IPv4]
[2018-05-02 05:09:03,960] {conn.py:373} INFO - <BrokerConnection node_id=bootstrap host=kafka-01.easyservices.net.co:9092 <connecting> [IPv4 ('x.x.x.x', 9092)]>: Connection complete.
[2018-05-02 05:09:03,964] {client_async.py:258} INFO - Bootstrap succeeded: found 5 brokers and 15 topics.
[2018-05-02 05:09:03,965] {conn.py:710} INFO - <BrokerConnection node_id=bootstrap host=kafka-01.easyservices.net.co:9092 <connected> [IPv4 ('x.x.x.x', 9092)]>: Closing connection. 
[2018-05-02 05:09:03,981] {conn.py:350} INFO - <BrokerConnection node_id=12 host=kafka-02.easyservices.net.co:9092 <connecting> [IPv4 ('x.x.x.x', 9092)]>: connecting to kafka-02.easyservices.net.co:9092 [('x.x.x.x', 9092) IPv4]
[2018-05-02 05:09:04,002] {conn.py:906} INFO - Probing node 12 broker version
[2018-05-02 05:09:04,004] {conn.py:373} INFO - <BrokerConnection node_id=12 host=kafka-02.easyservices.net.co:9092 <connecting> [IPv4 ('x.x.x.x', 9092)]>: Connection complete.
[2018-05-02 05:09:05,109] {conn.py:963} INFO - Broker version identifed as 0.11.0
[2018-05-02 05:09:05,110] {conn.py:965} INFO - Set configuration api_version=(0, 11, 0) to skip auto check_version requests on startup
[2018-05-02 05:09:05,111] {subscription_state.py:171} INFO - Updating subscribed topics to: [u'drivers']
[2018-05-02 05:09:05,129] {conn.py:350} INFO - <BrokerConnection node_id=14 host=kafka-04.easyservices.net.co:9092 <connecting> [IPv4 ('x.x.x.x', 9092)]>: connecting to kafka-04.easyservices.net.co:9092 [('x.x.x.x', 9092) IPv4]
[2018-05-02 05:09:05,130] {cluster.py:349} INFO - Group coordinator for airflow_kick_off_dag is BrokerMetadata(nodeId=14, host=u'kafka-04.easyservices.net.co', port=9092, rack=None)
[2018-05-02 05:09:05,130] {base.py:676} INFO - Discovered coordinator 14 for group airflow_kick_off_dag
[2018-05-02 05:09:05,130] {base.py:724} INFO - Starting new heartbeat thread
[2018-05-02 05:09:05,130] {consumer.py:341} INFO - Revoking previously assigned partitions set([]) for group airflow_kick_off_dag
[2018-05-02 05:09:05,130] {conn.py:373} INFO - <BrokerConnection node_id=14 host=kafka-04.easyservices.net.co:9092 <connecting> [IPv4 ('x.x.x.x', 9092)]>: Connection complete.
[2018-05-02 05:09:05,130] {base.py:434} INFO - (Re-)joining group airflow_kick_off_dag
[2018-05-02 05:09:05,133] {base.py:504} INFO - Elected group leader -- performing partition assignments using range
[2018-05-02 05:09:05,135] {base.py:333} INFO - Successfully joined group airflow_kick_off_dag with generation 6
[2018-05-02 05:09:05,135] {subscription_state.py:257} INFO - Updated partition assignment: [TopicPartition(topic=u'drivers', partition=0), TopicPartition(topic=u'drivers', partition=1), TopicPartition(topic=u'drivers', partition=2)]
[2018-05-02 05:09:05,135] {consumer.py:238} INFO - Setting newly assigned partitions set([TopicPartition(topic=u'drivers', partition=0), TopicPartition(topic=u'drivers', partition=1), TopicPartition(topic=u'drivers', partition=2)]) for group airflow_kick_off_dag
[2018-05-02 05:09:05,189] {conn.py:350} INFO - <BrokerConnection node_id=11 host=kafka-01.easyservices.net.co:9092 <connecting> [IPv4 ('x.x.x.x', 9092)]>: connecting to kafka-01.easyservices.net.co:9092 [('x.x.x.x', 9092) IPv4]
[2018-05-02 05:09:05,198] {conn.py:350} INFO - <BrokerConnection node_id=15 host=kafka-05.easyservices.net.co:9092 <connecting> [IPv4 ('x.x.x.x', 9092)]>: connecting to kafka-05.easyservices.net.co:9092 [('x.x.x.x', 9092) IPv4]
[2018-05-02 05:09:05,198] {conn.py:373} INFO - <BrokerConnection node_id=11 host=kafka-01.easyservices.net.co:9092 <connecting> [IPv4 ('x.x.x.x', 9092)]>: Connection complete.
[2018-05-02 05:09:05,200] {conn.py:373} INFO - <BrokerConnection node_id=15 host=kafka-05.easyservices.net.co:9092 <connecting> [IPv4 ('x.x.x.x', 9092)]>: Connection complete.
[2018-05-02 05:09:05,234] {base.py:731} INFO - Stopping heartbeat thread
[2018-05-02 05:09:05,234] {base.py:757} INFO - Leaving consumer group (airflow_kick_off_dag).
[2018-05-02 05:09:05,237] {conn.py:710} INFO - <BrokerConnection node_id=11 host=kafka-01.easyservices.net.co:9092 <connected> [IPv4 ('x.x.x.x', 9092)]>: Closing connection. 
[2018-05-02 05:09:05,237] {conn.py:710} INFO - <BrokerConnection node_id=12 host=kafka-02.easyservices.net.co:9092 <connected> [IPv4 ('x.x.x.x', 9092)]>: Closing connection. 
[2018-05-02 05:09:05,237] {conn.py:710} INFO - <BrokerConnection node_id=14 host=kafka-04.easyservices.net.co:9092 <connected> [IPv4 ('x.x.x.x', 9092)]>: Closing connection. 
[2018-05-02 05:09:05,238] {conn.py:710} INFO - <BrokerConnection node_id=15 host=kafka-05.easyservices.net.co:9092 <connected> [IPv4 ('x.x.x.x', 9092)]>: Closing connection. 
[2018-05-02 05:09:05,239] {base.py:699} WARNING - Marking the coordinator dead (node 14) for group airflow_kick_off_dag: Node Disconnected.
[2018-05-02 05:09:05,239] {models.py:1417} ERROR - I/O operation on closed epoll fd
Traceback (most recent call last):
  File "/home/airflow/et_airflow/airflow/models.py", line 1374, in run
    result = task_copy.execute(context=context)
  File "/home/airflow/bigdata/bigdata_plugin/operators/kafka_to_s3_operator.py", line 106, in execute
    self.time_limit)
  File "/home/airflow/bigdata/bigdata_plugin/hooks/kafka_hook.py", line 44, in consume_messages
    for message in self.consumer:
  File "/usr/local/lib/python2.7/dist-packages/kafka/vendor/six.py", line 561, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/group.py", line 1118, in __next__
    return next(self._iterator)
  File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/group.py", line 1052, in _message_generator
    self._coordinator.poll()
  File "/usr/local/lib/python2.7/dist-packages/kafka/coordinator/consumer.py", line 262, in poll
    self.ensure_coordinator_ready()
  File "/usr/local/lib/python2.7/dist-packages/kafka/coordinator/base.py", line 259, in ensure_coordinator_ready
    future = self.lookup_coordinator()
  File "/usr/local/lib/python2.7/dist-packages/kafka/coordinator/base.py", line 284, in lookup_coordinator
    self._find_coordinator_future = self._send_group_coordinator_request()
  File "/usr/local/lib/python2.7/dist-packages/kafka/coordinator/base.py", line 648, in _send_group_coordinator_request
    elif not self._client.ready(node_id, metadata_priority=False):
  File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 382, in ready
    self._maybe_connect(node_id)
  File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 368, in _maybe_connect
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/kafka/conn.py", line 348, in connect
    self.config['state_change_callback'](self)
  File "/usr/local/lib/python2.7/dist-packages/kafka/util.py", line 159, in __call__
    return self.method()(self.target(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 289, in _conn_state_change
    self._selector.register(conn._sock, selectors.EVENT_WRITE)
  File "/usr/local/lib/python2.7/dist-packages/kafka/vendor/selectors34.py", line 436, in register
    self._epoll.register(key.fd, epoll_events)
ValueError: I/O operation on closed epoll fd
[2018-05-02 05:09:05,244] {models.py:1433} INFO - Marking task as UP_FOR_RETRY
```

My guess was that it could be something related with how Airflow manage to create the process, with the subprocess. In our Airflow installation, the part that starts the process is like this:
```python
         proc = subprocess.Popen(
             full_cmd,
             stdout=subprocess.PIPE,
             stderr=subprocess.STDOUT
         )
```
I tried to set the `close_fds` flag to `True`, but it didn't worked...
```python
         proc = subprocess.Popen(
             full_cmd,
             close_fds=True,
             stdout=subprocess.PIPE,
             stderr=subprocess.STDOUT
         )
```

**Comment by dpkp** [comment]
See also #1666
