### ISSUE TITLE
Handling commits with manual assignment

### ISSUE THREAD

**Issue by ColonelLanda** [dpkp/kafka-python#1582]
Hi, 
I want to use the partitioning capabilities of Kafka by specifying a predefined partition for every process (due to internal buisness logic). I also want to commit the offsets after processing several messages successfully.
The following code illustrates the problem and throws an exception (kafka-python 1.4.2) :

```
import kafka

consumer = kafka.KafkaConsumer(bootstrap_servers='172.16.123.1:9092',
                               enable_auto_commit=False)
consumer.assign([kafka.TopicPartition("test1", i) for i in range(3)])
for i in range(5):
    print("got ", next(consumer))
consumer.commit() # an exception is thrown here
print("finished")
```

Is there  a work around for this issue?

Thanks,
Alex

**Comment by tvoinarovskyi** [comment]
What exception is it?

**Comment by ColonelLanda** [comment]
```Traceback (most recent call last):
  File ".../landa/kafka_test.py", line 8, in <module>
    consumer.commit()
  File "/Users/landa/.pyenv/versions/3.5.4/lib/python3.5/site-packages/kafka/consumer/group.py", line 504, in commit
    assert self.config['group_id'] is not None, 'Requires group_id'
AssertionError: Requires group_id
```

**Comment by tvoinarovskyi** [comment]
The error implies you initialized your consumer with `group_id=None`, which is the default. To support commits you have to pass `group_id` so that the consumer can save that offset to some name. 
example:
```
import kafka

consumer = kafka.KafkaConsumer(bootstrap_servers='localhost:9092',
                               enable_auto_commit=False,
                               group_id="my_group")
consumer.assign([kafka.TopicPartition("test1", i) for i in [0]])
for i in range(5):
    print("got ", next(consumer))
consumer.commit() # an exception is thrown here
print("finished")

```

**Comment by ColonelLanda** [comment]
Thank you.
