### ISSUE TITLE
Getting error ValueError: <class 'struct.error'> while iterating over consumer kafka-1.3.5

### ISSUE THREAD

**Issue by pprasadk** [dpkp/kafka-python#1601]
Iterating over below line gives error
for consumer_message in self.consumer :

ERROR: ValueError: <class 'struct.error'>
Build:kafka-**1.3.5**   https://pypi.org/project/kafka/1.3.5/

Kafka version used: **kafka_2.12-2.0.0**

_Strangely I see the below error message in kafka server log(in **DEBUG** mode) when the above mentioned  error is encountered_ 

[2018-10-15 18:03:51,269] DEBUG Processor 0 listening to new connection from /0:0:0:0:0:0:0:1:58932 (kafka.network.Processor)
[2018-10-15 18:03:51,282] DEBUG [SocketServer brokerId=0] Connection with /0:0:0:0:0:0:0:1 disconnected (org.apache.kafka.common.network.Selector)
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:96)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:335)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:296)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:560)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:496)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:425)
        at kafka.network.Processor.poll(SocketServer.scala:678)
        at kafka.network.Processor.run(SocketServer.scala:583)
        at java.lang.Thread.run(Thread.java:748)
[2018-10-15 18:03:51,309] DEBUG Accepted connection from /xxx.xxx.xx.x:58933 on /xxx.xxx.xx.x:9092 and assigned it to processor 1, sendBufferSize [actual|requested]: [102400|102400] recvBufferSize [actual|requested]: [102400|102400] (kafka.network.Acceptor)
[2018-10-15 18:03:51,311] DEBUG Processor 1 listening to new connection from /xxx.xxx.xx.x:58933 (kafka.network.Processor)
[2018-10-15 18:03:51,682] DEBUG [SocketServer brokerId=0] Connection with /xxx.xxx.xx.x disconnected

**Comment by jeffwidman** [comment]
There's been multiple releases since `1.3.5`... can you try with `master` (preferably) or `1.4.3` and see if you still hit this?
