### ISSUE TITLE
kafka-python 1.4.3 Exception ignored under Pypi

### ISSUE THREAD

**Issue by javixeneize** [dpkp/kafka-python#1632]
Hi

I have downloaded the newer version (1.4.3) and, when running my tests where i am using this package as a dependency, i have the following message

```Exception ignored in: <bound method KafkaProducer.__del__ of <kafka.producer.kafka.KafkaProducer object at 0x1044b66d8>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kafka/producer/kafka.py", line 424, in __del__
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kafka/producer/kafka.py", line 437, in close
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1305, in info
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1546, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```

It is an ignored exception, the tests work fine, but it needs attention. Apparently somewhere you are comparing an int with NoneType

Thanks

**Comment by Federico-Comesana** [comment]
Why did you closed this? This error is still happening on v2.0.1

**Comment by javixeneize** [comment]
Nobody answered in more than 2 years

**Comment by Federico-Comesana** [comment]
@javixeneize okay. I still have the same issue under version 2.0.1. Any reason why is this happening?

> Exception ignored in: <bound method KafkaProducer.__del__ of <kafka.producer.kafka.KafkaProducer object at 0x7f968daf5940>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 448, in __del__
  File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 461, in close
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1305, in info
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1546, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
Exception ignored in: <bound method KafkaProducer.__del__ of <kafka.producer.kafka.KafkaProducer object at 0x7f968ccb70f0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 448, in __del__
  File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 461, in close
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1305, in info
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1546, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
`

**Comment by jpribyl** [comment]
https://github.com/dpkp/kafka-python/pull/2043/files

in case anyone else stumbles across this
