### ISSUE TITLE
Using create_topics

### ISSUE THREAD

**Issue by mooperd** [dpkp/kafka-python#1665]
I'm trying to get my head around creating topics programatically but I'm struggling somewhat:

```
from kafka import KafkaAdminClient
from kafka.protocol.admin import (
    CreateTopicsRequest, DeleteTopicsRequest, DescribeConfigsRequest, AlterConfigsRequest, CreatePartitionsRequest,
    ListGroupsRequest, DescribeGroupsRequest)

topic_name = "foo"
num_partitions = "1"
replication_factor = None
timeout_ms = "500"

request = CreateTopicsRequest[0]([(topic_name, num_partitions,
                replication_factor, [], [])], timeout_ms)

adminclient = KafkaAdminClient(
    bootstrap_servers="kafka-317b40d8-andrew-e213.aivencloud.com:18224",
    security_protocol="SSL",
    ssl_cafile="kafka-317b40d8/ca.pem",
    ssl_certfile="kafka-317b40d8/service.cert",
    ssl_keyfile="kafka-317b40d8/service.key",
)

adminclient.create_topics([request], timeout_ms=None, validate_only=False)
```

Gives me error:

```
Traceback (most recent call last):
  File "ensure-kafka-topic.py", line 25, in <module>
    adminclient.create_topics([request], timeout_ms=None, validate_only=False)
  File "/Users/andrew/dev/aiven/kafka/admin/client.py", line 388, in create_topics
    create_topic_requests=[self._convert_new_topic_request(new_topic) for new_topic in new_topics],
  File "/Users/andrew/dev/aiven/kafka/admin/client.py", line 388, in <listcomp>
    create_topic_requests=[self._convert_new_topic_request(new_topic) for new_topic in new_topics],
  File "/Users/andrew/dev/aiven/kafka/admin/client.py", line 354, in _convert_new_topic_request
    new_topic.name,
AttributeError: 'CreateTopicsRequest_v0' object has no attribute 'name'
```

Can anyone point me in the right direction?

**Comment by ulrikjohansson** [comment]
The problem is that you're trying to supply the wrong objects to `KafkaAdminClient.create_topics`.
The `create_topics` method expects a list of `NewTopic` objects.

So, for your use case something like this should work instead of the raw CreateTopicsRequest:
topic = NewTopic(name="foo", num_partitions=1, replication_factor=1)
result = admin_client.create_topics([topic])

**Comment by mooperd** [comment]
Thanks! I tried a couple of ways of instantiating NewTopic() but I'm seeing the following error.
```
topic = kafka.admin.NewTopic(name="foo", num_partitions=1, replication_factor=1)
topic = kafka.admin.NewTopic('bar', -1, -1, {1: [1, 2, 3]}, {'key': 'value'})
adminclient.create_topics([topic])
```
error:
```
Traceback (most recent call last):
  File "ensure-kafka-topic.py", line 26, in <module>
    adminclient.create_topics([topic])
  File "/Users/andrew/dev/aiven/kafka/admin/client.py", line 398, in create_topics
    return self._send_request_to_controller(request)
  File "/Users/andrew/dev/aiven/kafka/admin/client.py", line 335, in _send_request_to_controller
    for topic, error_code in getattr(response, "topic_errors", response.topic_error_codes):
ValueError: too many values to unpack (expected 2)
```

**Comment by mooperd** [comment]
https://github.com/dpkp/kafka-python/issues/1657

**Comment by mooperd** [comment]
Duplicate of https://github.com/dpkp/kafka-python/issues/1657

**Comment by mooperd** [comment]
Duplicate of https://github.com/dpkp/kafka-python/issues/1657
