### ISSUE TITLE
Cannot import KafkaProducer

### ISSUE THREAD

**Issue by steve-heslouin** [dpkp/kafka-python#1721]
`virtualenv kafka-test`

` .  kafka-test/bin/activate `
` pip install kafka-python `

` pip freeze `
kafka-python==1.4.4

(kafka-test) router:Desktop me$ python
Python 2.7.10 (default, Aug 17 2018, 19:45:58)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kafka import KafkaProducer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "kafka.py", line 5, in <module>
    from kafka import KafkaProducer
ImportError: cannot import name KafkaProducer

**Comment by steve-heslouin** [comment]
my program was also called kafka.py
