### ISSUE TITLE
Cannot connect with SASL_PLAINTEXT using kafka-python 1.4.5

### ISSUE THREAD

**Issue by ingwinlu** [dpkp/kafka-python#1743]
Hi,

since updating to 1.4.5 I can no longer connect to our Kafka Cluster:

```
2019-03-18 09:27:27.924 | INFO     | __main__:main:18 - Startup KafkaConsumer
Traceback (most recent call last):
  File "wrapper/wrapper.py", line 101, in <module>
    main()
  File "wrapper/wrapper.py", line 27, in main
    consumer_timeout_ms=5000,  # Remove for production
  File "/usr/local/lib/python3.7/dist-packages/kafka/consumer/group.py", line 344, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/usr/local/lib/python3.7/dist-packages/kafka/client_async.py", line 230, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/local/lib/python3.7/dist-packages/kafka/client_async.py", line 865, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "/usr/local/lib/python3.7/dist-packages/kafka/conn.py", line 990, in check_version
    if not self.connect_blocking(timeout_at - time.time()):
  File "/usr/local/lib/python3.7/dist-packages/kafka/conn.py", line 321, in connect_blocking
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/kafka/conn.py", line 425, in connect
    if self._try_authenticate():
  File "/usr/local/lib/python3.7/dist-packages/kafka/conn.py", line 500, in _try_authenticate
    assert self.config['api_version'] is None or self.config['api_version'] >= (0, 10)
AssertionError
```

the code itself is fairly basic:
```
consumer = KafkaConsumer(
    target_topic,
    bootstrap_servers=['url:9092'],
    value_deserializer=lambda m: json.loads(m.decode('ascii')),
    sasl_plain_username="user",
    sasl_plain_password="pass",
    sasl_mechanism="PLAIN",
    security_protocol='SASL_PLAINTEXT',
    consumer_timeout_ms=5000,  # Remove for production
)
```

Kafka Version is 1.0.1.

**Comment by adiosjerry** [comment]
I got the same assert info, I print the self.config['api_version'], the value is (0, 8, 2), I found commit 703f06590be2daa7e4592b3d82df6d719a6829bb set self.config['api_version'] as default, that will make assert fail.

 [conn.py:500 _try_authenticate] api_version = (0, 8, 2)
Traceback (most recent call last):
  File "consumer.py", line 151, in <module>
    servers = server(parser)
  File "consumer.py", line 118, in __init__
    sasl_plain_password="X1M7ylc59lPMNCN8PA+")
  File "/usr/lib/python2.7/site-packages/kafka_python-1.4.5-py2.7.egg/kafka/consumer/group.py", line 344, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/usr/lib/python2.7/site-packages/kafka_python-1.4.5-py2.7.egg/kafka/client_async.py", line 230, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/lib/python2.7/site-packages/kafka_python-1.4.5-py2.7.egg/kafka/client_async.py", line 865, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "/usr/lib/python2.7/site-packages/kafka_python-1.4.5-py2.7.egg/kafka/conn.py", line 994, in check_version
    if not self.connect_blocking(timeout_at - time.time()):
  File "/usr/lib/python2.7/site-packages/kafka_python-1.4.5-py2.7.egg/kafka/conn.py", line 321, in connect_blocking
    self.connect()
  File "/usr/lib/python2.7/site-packages/kafka_python-1.4.5-py2.7.egg/kafka/conn.py", line 425, in connect
    if self._try_authenticate():
  File "/usr/lib/python2.7/site-packages/kafka_python-1.4.5-py2.7.egg/kafka/conn.py", line 502, in _try_authenticate
    assert self.config['api_version'] is None or self.config['api_version'] >= (0, 10)
AssertionError

**Comment by kiblik** [comment]
Same problem: #1747 but with kafka 2.1.1

**Comment by dpkp** [comment]
Workaround here is to set your api_version explicitly and not rely on
broker probes.

**Comment by kiblik** [comment]
When I add `'api_version': (2,1,1)` to `config`, KafkaAdminClient fails on this error:
```python
Traceback (most recent call last):
  File "test.py", line 50, in setUp
    self.clients.append( KafkaAdminClient(**config) )
  File "/usr/local/lib/python3.5/dist-packages/kafka/admin/client.py", line 202, in __init__
    self._refresh_controller_id()
  File "/usr/local/lib/python3.5/dist-packages/kafka/admin/client.py", line 246, in _refresh_controller_id
    version = self._matching_api_version(MetadataRequest)
  File "/usr/local/lib/python3.5/dist-packages/kafka/admin/client.py", line 227, in _matching_api_version
    self._client.get_api_versions()[operation[0].API_KEY][1])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dpkp** [comment]
This should be fixed on master. Please reopen if the issue persists.
