### ISSUE TITLE
assert self.config['api_version'] is None or self.config['api_version'] >= (0, 10) after upgrade

### ISSUE THREAD

**Issue by kiblik** [dpkp/kafka-python#1747]
Hi,

I have used `kafka-python==1.4.4`. After upgrade to `1.4.5` I have received:
```python
Traceback (most recent call last):
  File "test.py", line 97, in setUp
    self.clients.append( KafkaConsumer(**ssl_sasl_ro_config, **consumer_config) )
  File "/usr/local/lib/python3.5/dist-packages/kafka/consumer/group.py", line 344, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/usr/local/lib/python3.5/dist-packages/kafka/client_async.py", line 230, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/local/lib/python3.5/dist-packages/kafka/client_async.py", line 865, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "/usr/local/lib/python3.5/dist-packages/kafka/conn.py", line 991, in check_version
    if not self.connect_blocking(timeout_at - time.time()):
  File "/usr/local/lib/python3.5/dist-packages/kafka/conn.py", line 321, in connect_blocking
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/kafka/conn.py", line 425, in connect
    if self._try_authenticate():
  File "/usr/local/lib/python3.5/dist-packages/kafka/conn.py", line 501, in _try_authenticate
    assert self.config['api_version'] is None or self.config['api_version'] >= (0, 10)
```
My configs:
```python
            config = {
                'max_in_flight_requests_per_connection': 1,
            }
            consumer_config = {
                'exclude_internal_topics': False,
                'auto_offset_reset': 'earliest',
                'auto_commit_interval_ms': 1000
            }
            ssl_only_ro_config = {
              **config,
              'bootstrap_servers': host+":9093",
              'security_protocol': 'SSL',
              'ssl_certfile': param.certfilero,
              'ssl_keyfile': param.keyfilero,
            }
```
I also tried add one line to `kafka/conn.py:500`
```python
     def _try_authenticate(self):
+        print("api_version:", self.config['api_version'])
         assert self.config['api_version'] is None or self.config['api_version'] >= (0, 10)
```
This is output: `api_version: (0, 8, 2)`

I use kafka 2.1.1.

Why `api_version` was overridden by value `(0, 8, 2)` when I use kafka 2.1.1?

Thank you.

**Comment by kiblik** [comment]
Duplicate of #1743
