### ISSUE TITLE
Broker does not support KIP-62 with kafka when using Kafka version 0.9.0

### ISSUE THREAD

**Issue by dvhh** [dpkp/kafka-python#1786]
Version 1.46 introduce breaking change when using Kafka version 0.9.0 

```
Consumer({
        'bootstrap.servers': brokers,
        'group.id': group,
        'auto.offset.reset': 'earliest',
        'api.version.request': False,
        'broker.version.fallback': '0.9.0'
    })
```

```
%5|1554770547.333|MAXPOLL|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/506: Broker does not support KIP-62 (requires Apache Kafka >= v0.10.1.0): consumer configuration `max.poll.interval.ms` (300000) is effectively limited by `session.timeout.ms` (10000) with this broker version
Traceback (most recent call last):
  File "/usr/src/app/kafka/kafka_read_topic.py", line 109, in <module>
    main()
  File "/usr/src/app/kafka/kafka_read_topic.py", line 102, in main
    print(message.value().decode('utf-8'), file=sys.stdout)
BrokenPipeError: [Errno 32] Broken pipe
I0409 00:42:29.103595 32116 process.cpp:1068] Failed to accept socket: future discarded
```

What configuration should be used to avoid this error ?

**Comment by dvhh** [comment]
Misfiled
