### ISSUE TITLE
Heartbeat failed on idle Consumer [1.4.6]

### ISSUE THREAD

**Issue by artemistomaras** [dpkp/kafka-python#1787]
I am having the same issue as referenced in #1418 

I launch my consumers inside a ConsumerGroup with the default provided settings. If in the topic partition that they are assigned, no messages are sent, the following happens ( single consumer log attached here)

```
2019 Apr 10 06:22:03  | 2019-04-10 06:22:02,491 - kafka.coordinator - INFO - (Re-)joining group NSFW_CONSUMER
2019 Apr 10 06:22:06  | 2019-04-10 06:22:05,582 - kafka.coordinator - INFO - Successfully joined group NSFW_CONSUMER with generation 220
2019 Apr 10 06:22:06  | 2019-04-10 06:22:05,583 - kafka.consumer.subscription_state - INFO - Updated partition assignment: [TopicPartition(topic='request_for_analyze', partition=3)]
2019 Apr 10 06:22:06  | 2019-04-10 06:22:05,583 - kafka.coordinator.consumer - INFO - Setting newly assigned partitions {TopicPartition(topic='request_for_analyze', partition=3)} for group NSFW_CONSUMER
2019 Apr 10 06:27:12  | 2019-04-10 06:25:37,880 - kafka.coordinator - WARNING - Heartbeat session expired, marking coordinator dead
2019 Apr 10 06:27:12  | 2019-04-10 06:25:37,880 - kafka.coordinator - WARNING - Marking the coordinator dead (node 0) for group NSFW_CONSUMER: Heartbeat session expired.
2019 Apr 10 06:27:12  | 2019-04-10 06:25:37,889 - kafka.cluster - INFO - Group coordinator for NSFW_CONSUMER is BrokerMetadata(nodeId=0, host='tot-kafka-0.tot-kafka-headless.tot', port=9092, rack=None)
2019 Apr 10 06:27:12  | 2019-04-10 06:25:42,893 - kafka.coordinator - WARNING - Marking the coordinator dead (node 0) for group NSFW_CONSUMER: [Error 7] RequestTimedOutError.
2019 Apr 10 06:27:12  | 2019-04-10 06:25:37,890 - kafka.coordinator - INFO - Discovered coordinator 0 for group NSFW_CONSUMER
2019 Apr 10 06:27:12  | 2019-04-10 06:25:42,897 - kafka.cluster - INFO - Group coordinator for NSFW_CONSUMER is BrokerMetadata(nodeId=0, host='tot-kafka-0.tot-kafka-headless.tot', port=9092, rack=None)
2019 Apr 10 06:27:12  | 2019-04-10 06:25:42,894 - kafka.coordinator - WARNING - Heartbeat failed for group NSFW_CONSUMER because it is rebalancing
2019 Apr 10 06:27:12  | 2019-04-10 06:25:42,893 - kafka.coordinator.consumer - WARNING - Auto offset commit failed for group NSFW_CONSUMER: [Error 7] RequestTimedOutError: NSFW_CONSUMER
2019 Apr 10 06:27:12  | 2019-04-10 06:25:42,898 - kafka.coordinator - INFO - Discovered coordinator 0 for group NSFW_CONSUMER
2019 Apr 10 06:27:12  | 2019-04-10 06:25:48,003 - kafka.cluster - INFO - Group coordinator for NSFW_CONSUMER is BrokerMetadata(nodeId=0, host='tot-kafka-0.tot-kafka-headless.tot', port=9092, rack=None)
2019 Apr 10 06:27:12  | 2019-04-10 06:25:47,901 - kafka.coordinator - WARNING - Marking the coordinator dead (node 0) for group NSFW_CONSUMER: [Error 7] RequestTimedOutError.
2019 Apr 10 06:27:12  | 2019-04-10 06:25:53,149 - kafka.coordinator - WARNING - Marking the coordinator dead (node 0) for group NSFW_CONSUMER: [Error 7] RequestTimedOutError.
2019 Apr 10 06:27:12  | 2019-04-10 06:25:48,003 - kafka.coordinator - INFO - Discovered coordinator 0 for group NSFW_CONSUMER
2019 Apr 10 06:27:12  | 2019-04-10 06:25:53,252 - kafka.cluster - INFO - Group coordinator for NSFW_CONSUMER is BrokerMetadata(nodeId=0, host='tot-kafka-0.tot-kafka-headless.tot', port=9092, rack=None)
2019 Apr 10 06:27:12  | 2019-04-10 06:25:58,254 - kafka.coordinator - WARNING - Marking the coordinator dead (node 0) for group NSFW_CONSUMER: [Error 7] RequestTimedOutError.
2019 Apr 10 06:27:12  | 2019-04-10 06:25:53,252 - kafka.coordinator - INFO - Discovered coordinator 0 for group NSFW_CONSUMER
2019 Apr 10 06:27:12  | 2019-04-10 06:25:58,358 - kafka.coordinator - INFO - Discovered coordinator 0 for group NSFW_CONSUMER
2019 Apr 10 06:27:12  | 2019-04-10 06:25:58,358 - kafka.cluster - INFO - Group coordinator for NSFW_CONSUMER is BrokerMetadata(nodeId=0, host='tot-kafka-0.tot-kafka-headless.tot', port=9092, rack=None)
2019 Apr 10 06:27:12  | 2019-04-10 06:26:00,382 - kafka.coordinator - INFO - (Re-)joining group NSFW_CONSUMER
2019 Apr 10 06:27:12  | 2019-04-10 06:26:00,485 - kafka.coordinator - INFO - Successfully joined group NSFW_CONSUMER with generation 221
2019 Apr 10 06:27:12  | 2019-04-10 06:26:00,381 - kafka.coordinator.consumer - INFO - Revoking previously assigned partitions {TopicPartition(topic='request_for_analyze', partition=3)} for group NSFW_CONSUMER
2019 Apr 10 06:27:12  | 2019-04-10 06:26:00,486 - kafka.coordinator.consumer - INFO - Setting newly assigned partitions {TopicPartition(topic='request_for_analyze', partition=3)} for group NSFW_CONSUMER
2019 Apr 10 06:27:12  | 2019-04-10 06:26:00,486 - kafka.consumer.subscription_state - INFO - Updated partition assignment: [TopicPartition(topic='request_for_analyze', partition=3)]
2019 Apr 10 06:34:42  | 2019-04-10 06:34:42,897 - kafka.client - INFO - Closing idle connection 2, last active 540000 ms ago
2019 Apr 10 06:34:42  | 2019-04-10 06:34:42,898 - kafka.conn - INFO - <BrokerConnection node_id=2 host=tot-kafka-2.tot-kafka-headless.tot:9092 <connected> [IPv4 ('10.244.3.12', 9092)]>: Closing connection. 
2019 Apr 10 07:21:58  | 2019-04-10 07:21:57,707 - kafka.coordinator - WARNING - Heartbeat failed for group NSFW_CONSUMER because it is rebalancing
2019 Apr 10 07:21:58  | 2019-04-10 07:21:57,717 - kafka.coordinator.consumer - INFO - Revoking previously assigned partitions {TopicPartition(topic='request_for_analyze', partition=3)} for group NSFW_CONSUMER
2019 Apr 10 07:21:58  | 2019-04-10 07:21:57,718 - kafka.coordinator - INFO - (Re-)joining group NSFW_CONSUMER
2019 Apr 10 07:21:58  | 2019-04-10 07:21:57,990 - kafka.coordinator - INFO - Successfully joined group NSFW_CONSUMER with generation 222
2019 Apr 10 07:21:58  | 2019-04-10 07:21:57,994 - kafka.consumer.subscription_state - INFO - Updated partition assignment: [TopicPartition(topic='request_for_analyze', partition=3)]
2019 Apr 10 07:21:58  | 2019-04-10 07:21:57,996 - kafka.coordinator.consumer - INFO - Setting newly assigned partitions {TopicPartition(topic='request_for_analyze', partition=3)} for group NSFW_CONSUMER
2019 Apr 10 07:26:02  | 2019-04-10 07:26:02,457 - kafka.coordinator - WARNING - Heartbeat failed for group NSFW_CONSUMER because it is rebalancing
2019 Apr 10 07:26:02  | 2019-04-10 07:26:02,483 - kafka.coordinator - INFO - (Re-)joining group NSFW_CONSUMER
2019 Apr 10 07:26:02  | 2019-04-10 07:26:02,482 - kafka.coordinator.consumer - INFO - Revoking previously assigned partitions {TopicPartition(topic='request_for_analyze', partition=3)} for group NSFW_CONSUMER
2019 Apr 10 07:26:02  | 2019-04-10 07:26:02,802 - kafka.coordinator - INFO - Successfully joined group NSFW_CONSUMER with generation 223
2019 Apr 10 07:26:02  | 2019-04-10 07:26:02,802 - kafka.consumer.subscription_state - INFO - Updated partition assignment: [TopicPartition(topic='request_for_analyze', partition=2)]
2019 Apr 10 07:26:02  | 2019-04-10 07:26:02,803 - kafka.coordinator.consumer - INFO - Setting newly assigned partitions {TopicPartition(topic='request_for_analyze', partition=2)} for group NSFW_CONSUMER
2019 Apr 10 07:36:02  | 2019-04-10 07:36:02,635 - kafka.coordinator - WARNING - Heartbeat session expired, marking coordinator dead
2019 Apr 10 07:36:02  | 2019-04-10 07:36:02,635 - kafka.coordinator - WARNING - Marking the coordinator dead (node 0) for group NSFW_CONSUMER: Heartbeat session expired.
2019 Apr 10 07:36:02  | 2019-04-10 07:36:02,643 - kafka.cluster - INFO - Group coordinator for NSFW_CONSUMER is BrokerMetadata(nodeId=0, host='tot-kafka-0.tot-kafka-headless.tot', port=9092, rack=None)
2019 Apr 10 07:36:02  |             rebalanced and assigned the partitions to another member.
2019 Apr 10 07:36:02  | 2019-04-10 07:36:02,644 - kafka.coordinator - INFO - Discovered coordinator 0 for group NSFW_CONSUMER
2019 Apr 10 07:36:02  | 2019-04-10 07:36:02,648 - kafka.coordinator.consumer - WARNING - Auto offset commit failed for group NSFW_CONSUMER: CommitFailedError: Commit cannot be completed since the group has already
2019 Apr 10 07:36:02  |             This means that the time between subsequent calls to poll()
2019 Apr 10 07:36:02  |             typically implies that the poll loop is spending too much
2019 Apr 10 07:36:02  |             was longer than the configured max_poll_interval_ms, which
2019 Apr 10 07:36:02  |             increasing the rebalance timeout with max_poll_interval_ms,
2019 Apr 10 07:36:02  |             time message processing. You can address this either by
2019 Apr 10 07:36:02  |             with max_poll_records.
2019 Apr 10 07:36:02  |             or by reducing the maximum size of batches returned in poll()
2019 Apr 10 07:36:02  |             
2019 Apr 10 07:36:02  | 2019-04-10 07:36:02,649 - kafka.coordinator.consumer - ERROR - Offset commit failed: This is likely to cause duplicate message delivery
2019 Apr 10 07:36:02  | Traceback (most recent call last):
  File "/opt/app/.venv/lib/python3.6/site-packages/kafka/coordinator/consumer.py", line 521, in _maybe_auto_commit_offsets_sync
    self.commit_offsets_sync(self._subscription.all_consumed_offsets())
  File "/opt/app/.venv/lib/python3.6/site-packages/kafka/coordinator/consumer.py", line 514, in commit_offsets_sync
    raise future.exception # pylint: disable-msg=raising-bad-type
kafka.errors.CommitFailedError: CommitFailedError: Commit cannot be completed since the group has already
2019 Apr 10 07:36:02  |             rebalanced and assigned the partitions to another member.
2019 Apr 10 07:36:02  |             This means that the time between subsequent calls to poll()
2019 Apr 10 07:36:02  |             was longer than the configured max_poll_interval_ms, which
2019 Apr 10 07:36:02  |             typically implies that the poll loop is spending too much
2019 Apr 10 07:36:02  |             time message processing. You can address this either by
2019 Apr 10 07:36:02  |             or by reducing the maximum size of batches returned in poll()
2019 Apr 10 07:36:02  |             increasing the rebalance timeout with max_poll_interval_ms,
2019 Apr 10 07:36:02  |             
2019 Apr 10 07:36:02  |             with max_poll_records.
2019 Apr 10 07:36:02  | 2019-04-10 07:36:02,649 - kafka.coordinator.consumer - INFO - Revoking previously assigned partitions {TopicPartition(topic='request_for_analyze', partition=2)} for group NSFW_CONSUMER
2019 Apr 10 07:36:02  | 2019-04-10 07:36:02,650 - kafka.coordinator - INFO - (Re-)joining group NSFW_CONSUMER
2019 Apr 10 07:36:03  | 2019-04-10 07:36:03,920 - kafka.coordinator - INFO - Successfully joined group NSFW_CONSUMER with generation 225
2019 Apr 10 07:36:03  | 2019-04-10 07:36:03,921 - kafka.coordinator.consumer - INFO - Setting newly assigned partitions {TopicPartition(topic='request_for_analyze', partition=4)} for group NSFW_CONSUMER
2019 Apr 10 07:36:03  | 2019-04-10 07:36:03,920 - kafka.consumer.subscription_state - INFO - Updated partition assignment: [TopicPartition(topic='request_for_analyze', partition=4)]
2019 Apr 10 07:36:04  | 2019-04-10 07:36:03,989 - kafka.conn - INFO - <BrokerConnection node_id=2 host=tot-kafka-2.tot-kafka-headless.tot:9092 <connecting> [IPv4 ('10.244.3.12', 9092)]>: connecting to tot-kafka-2.tot-kafka-headless.tot:9092 [('10.244.3.12', 9092) IPv4]
2019 Apr 10 07:36:04  | 2019-04-10 07:36:03,991 - kafka.conn - INFO - <BrokerConnection node_id=2 host=tot-kafka-2.tot-kafka-headless.tot:9092 <connecting> [IPv4 ('10.244.3.12', 9092)]>: Connection complete.
2019 Apr 10 07:43:54  | 2019-04-10 07:43:54,668 - kafka.coordinator - WARNING - Heartbeat failed for group NSFW_CONSUMER because it is rebalancing
2019 Apr 10 07:43:54  | 2019-04-10 07:43:54,677 - kafka.coordinator.consumer - INFO - Revoking previously assigned partitions {TopicPartition(topic='request_for_analyze', partition=4)} for group NSFW_CONSUMER
2019 Apr 10 07:43:54  | 2019-04-10 07:43:54,700 - kafka.coordinator - INFO - Successfully joined group NSFW_CONSUMER with generation 226
2019 Apr 10 07:43:54  | 2019-04-10 07:43:54,684 - kafka.coordinator - INFO - Elected group leader -- performing partition assignments using range
2019 Apr 10 07:43:54  | 2019-04-10 07:43:54,678 - kafka.coordinator - INFO - (Re-)joining group NSFW_CONSUMER
2019 Apr 10 07:43:54  | 2019-04-10 07:43:54,701 - kafka.coordinator.consumer - INFO - Setting newly assigned partitions {TopicPartition(topic='request_for_analyze', partition=4)} for group NSFW_CONSUMER
2019 Apr 10 07:43:54  | 2019-04-10 07:43:54,700 - kafka.consumer.subscription_state - INFO - Updated partition assignment: [TopicPartition(topic='request_for_analyze', partition=4)]
```

I have managed to mitigate this problem by setting the ```metadata_max_age_ms=4000``` while keeping the ```heartbeat_interval_ms=3000``` as per the approach mentioned by @dpkp in  #1418

**Comment by jeffwidman** [comment]
Closing in favor of #1418 (which I have re-opened)
