### ISSUE TITLE
Truststore-Only Connection Failure - Support Requested

### ISSUE THREAD

**Issue by jbailey38** [dpkp/kafka-python#1839]
Hello,

I'm trying to publish messages via python to a Kafka topic and am receiving an error. 

I **CAN** connect and publish via the CLI as well as with Kafka Tool. 

Hoping for some guidance. I've googled and read the docs. I'm including the command which allows for a successful connection and subsequent publish via the console-publisher. These servers don't require client-side certification so there is no keystore, only the truststore.

I'm on a windows box and using Python 3.7 and Kafka 0.11

Thanks for your time!!

### **Successful CLI command:**

```
kafka-console-producer 
--broker-list 123.45.67.891:1234,123.45.67.892:1234,123.45.67.893:1234
--producer.config C:\Users\fake_user\Kafka\client-ssl.properties 
--topic FakeTopic
```
**Contents of client-ssl.properties:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;security.protocol = SSL
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ssl.truststore.location = C:/Users/fake_user/Kafka/kafka-truststore
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ssl.truststore.password = fakepass

### **Unsuccessful Code:**
```
from kafka import KafkaProducer

producer = KafkaProducer(bootstrap_servers=['123.45.67.891:1234', '123.45.67.892:1234', '123.45.67.893:1234'],  
security_protocol='SSL',  
ssl_certfile=r'C:\Users\fake_user\Kafka\kafka-truststore',  
ssl_password='fakepass')

producer.send('FakeTopic', value='python_test', key='test')
```
### **Resultant Error:**
```
Traceback (most recent call last):
  File "kafka_post_test.py", line 6, in <module>
    ssl_password='fakepass')
  File "C:\Users\fake_user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kafka\producer\kafka.py", line 381, in __init__
    **self.config)
  File "C:\Users\fake_user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kafka\client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "C:\Users\fake_user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kafka\client_async.py", line 874, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "C:\Users\fake_user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kafka\conn.py", line 1078, in check_version
    if not self.connect_blocking(timeout_at - time.time()):
  File "C:\Users\fake_user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kafka\conn.py", line 331, in connect_blocking
    self.connect()
  File "C:\Users\fake_user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kafka\conn.py", line 420, in connect
    if self._try_handshake():
  File "C:\Users\fake_user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kafka\conn.py", line 496, in _try_handshake
    self._sock.do_handshake()
  File "C:\Users\fake_user\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051)
```

**Comment by jeffwidman** [comment]
Sorry, none of the current maintainers actively use SSL functionality, so we don't have easily available testbeds for this... the initial support for it was all community-driven.

If you do find any bugs, we would welcome PRs.

**Comment by prabodhm** [comment]
Has anyone found a solution or a workaround for this?

**Comment by dpkp** [comment]
You should be able to use the `ssl_context` configuration parameter to customize your client ssl settings / adjust verification etc.
