### ISSUE TITLE
when use ssl and monkey_patch,it cannot connect 

### ISSUE THREAD

**Issue by zhgjun** [dpkp/kafka-python#1850]
my test code like :
```
#!/usr/bin/env python
# encoding: utf-8
import ssl
import logging
from kafka import KafkaConsumer
from kafka.client_async import selectors
import eventlet
eventlet.monkey_patch() 
context = ssl.create_default_context()
context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
 
from eventlet.green import select
selectors.SelectSelector._select = staticmethod(select.select)

# Force to use the select selectors
KAFKA_SELECTOR = selectors.SelectSelector
 
def log_init(log_name="test", filemode='w'):
    logging.basicConfig(filename="test.log", level=logging.DEBUG, filemode=filemode,
                        format='%(asctime)s - %(levelname)s: %(message)s')
 
 
def comsum():
    log_init()
    consumer = KafkaConsumer("test",
                             bootstrap_servers=["1.11.12.201:9093"],
                            group_id="mygroup",
                            sasl_mechanism="PLAIN",
                            ssl_context=context,
                            security_protocol='SASL_SSL',
                            sasl_plain_username="test",
                            sasl_plain_password="test",
                            selector=KAFKA_SELECTOR)
 
    try:
        for message in consumer:
            msg = "key=%s,value=%s" % (message.key, message.value)
            print msg
    except KeyboardInterrupt:
        if consumer:
            consumer.close()
            print "stoped"
 
comsum()
```

and the part log is 

```

2019-06-27 17:34:40,965 - DEBUG: <BrokerConnection node_id=bootstrap host=1.11.12.201:9093 <connecting> [IPv4 ('1.11.12.201', 9093)]>: established TCP connection
2019-06-27 17:34:40,965 - DEBUG: <BrokerConnection node_id=bootstrap host=1.11.12.201:9093 <connecting> [IPv4 ('1.11.12.201', 9093)]>: initiating SSL handshake
2019-06-27 17:34:41,076 - DEBUG: <BrokerConnection node_id=bootstrap host=1.11.12.201:9093 <handshake> [IPv4 ('1.11.12.201', 9093)]>: completed SSL handshake.
2019-06-27 17:34:41,077 - DEBUG: <BrokerConnection node_id=bootstrap host=1.11.12.201:9093 <handshake> [IPv4 ('1.11.12.201', 9093)]>: initiating SASL authentication
2019-06-27 17:34:41,077 - DEBUG: Sending request SaslHandShakeRequest_v0(mechanism='PLAIN')
2019-06-27 17:34:41,077 - DEBUG: <BrokerConnection node_id=bootstrap host=1.11.12.201:9093 <authenticating> [IPv4 ('1.11.12.201', 9093)]> Request 1: SaslHandShakeRequest_v0(mechanism='PLAIN')
2019-06-27 17:34:41,078 - DEBUG: Received correlation id: 1
2019-06-27 17:34:41,078 - DEBUG: Processing response SaslHandShakeResponse_v0
2019-06-27 17:34:41,079 - DEBUG: <BrokerConnection node_id=bootstrap host=1.11.12.201:9093 <authenticating> [IPv4 ('1.11.12.201', 9093)]> Response 1 (1.37996673584 ms): SaslHandShakeResponse_v0(error_code=0, enabled_mechanisms=[u'PLAIN'])
2019-06-27 17:34:41,079 - ERROR: <BrokerConnection node_id=bootstrap host=1.11.12.201:9093 <authenticating> [IPv4 ('1.11.12.201', 9093)]>: Error receiving reply from server
Traceback (most recent call last):
  File "/opt/cloud/services/cascading-neutron/venv/lib/python2.7/site-packages/kafka/conn.py", line 572, in _try_authenticate_plain
    data = self._recv_bytes_blocking(4)
  File "/opt/cloud/services/cascading-neutron/venv/lib/python2.7/site-packages/kafka/conn.py", line 548, in _recv_bytes_blocking
    fragment = self._sock.recv(n - len(data))
  File "/opt/cloud/services/cascading-neutron/venv/lib/python2.7/site-packages/eventlet/green/ssl.py", line 198, in recv
    read = self.read(buflen)
  File "/opt/cloud/services/cascading-neutron/venv/lib/python2.7/site-packages/eventlet/green/ssl.py", line 138, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/opt/cloud/services/cascading-neutron/venv/lib/python2.7/site-packages/eventlet/green/ssl.py", line 108, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib64/python2.7/ssl.py", line 658, in read
    v = self._sslobj.read(len or 1024)
SSLWantReadError: The operation did not complete (read) (_ssl.c:1787)
2019-06-27 17:34:41,080 - INFO: <BrokerConnection node_id=bootstrap host=1.11.12.201:9093 <authenticating> [IPv4 ('1.11.12.201', 9093)]>: Closing connection. ConnectionError: <BrokerConnection node_id=bootstrap host=1.11.12.201:9093 <authenticating> [IPv4 ('1.11.12.201', 9093)]>: The operation did not complete (read) (_ssl.c:1787)

```

**Comment by zhgjun** [comment]
As it is say in python [docs](https://docs.python.org/2/library/socket.html#socket.socket.settimeout), I just add self._sock.setblocking(True) and  self._sock.setblocking(False) in conn.py.  As result it is works.

```
    def _recv_bytes_blocking(self, n):
        **self._sock.setblocking(True)**
        self._sock.settimeout(self.config['request_timeout_ms'] / 1000)
        try:
            data = b''
            while len(data) < n:
                fragment = self._sock.recv(n - len(data))
                if not fragment:
                    raise ConnectionError('Connection reset during recv')
                data += fragment
            return data
        finally:
            **self._sock.setblocking(False)**
            self._sock.settimeout(0.0)

```
when use monkey_patch, it changes the rule in the python docs. **so can we and the code i put in  conn.py? since it is followed the rules in python docs**

@dpkp @tvoinarovskyi @jeffwidman , any ideas?
