### ISSUE TITLE
Failed to init client over kafka-python-1.4.6

### ISSUE THREAD

**Issue by zzxwill** [dpkp/kafka-python#1859]
```
[root@iZrj9dz4q8arthcipd3zymZ ~]# pip3 install kafka-python-1.4.6.tar.gz
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Processing ./kafka-python-1.4.6.tar.gz
Installing collected packages: kafka-python
  Running setup.py install for kafka-python ... done
Successfully installed kafka-python-1.4.6

[root@iZrj9dz4q8arthcipd3zymZ ~]# python3.6
Python 3.6.6 (default, Jan 26 2019, 16:53:05)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kafka
>>> print(kafka.version.__version__)
1.4.6
>>> from kafka.admin.client import KafkaAdminClient
>>>     kafka_admin_client = KafkaAdminClient(bootstrap_servers='xxx:9092', client_id='1')
  File "<stdin>", line 1
    kafka_admin_client = KafkaAdminClient(bootstrap_servers='xxx:9092', client_id='1')
    ^
IndentationError: unexpected indent
>>> afka_admin_client = KafkaAdminClient(bootstrap_servers='xxx:9092', client_id='1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/kafka/admin/client.py", line 198, in __init__
    **self.config)
  File "/usr/local/lib/python3.6/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/local/lib/python3.6/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

It worked in version v1.4.4

**Comment by mariomtzjr** [comment]
Maybe you needed to add the `api_version` parameter for working on with te latest version.
