### ISSUE TITLE
kafka.errors.NodeNotReadyError: NodeNotReadyError

### ISSUE THREAD

**Issue by zzxwill** [dpkp/kafka-python#1861]
```
>>> afka_admin_client = KafkaAdminClient(bootstrap_servers='xxx.com:9092', client_id='1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kafka/admin/client.py", line 205, in __init__
    self._refresh_controller_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kafka/admin/client.py", line 255, in _refresh_controller_id
    controller_version = self._client.check_version(controller_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kafka/client_async.py", line 874, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kafka/conn.py", line 1079, in check_version
    raise Errors.NodeNotReadyError()
kafka.errors.NodeNotReadyError: NodeNotReadyError
```

It worked by testing in the Kafka server machine.

**Comment by jeffwidman** [comment]
What version are you using? 

There have been some changes to `master` that may affect this, for example whenc I check current source I see this note: https://github.com/dpkp/kafka-python/blob/fb87a353d99b3271105d0941f39ee64bf2ab6858/kafka/admin/client.py#L326-L329 which suggests that it should `poll()` until the node is ready rather than throwing this...

**Comment by zzxwill** [comment]
Sorry, it seems that it's not the issue of client. I added `advertised.host.name` in `server.properties` and it worked. Thanks.

**Comment by StudyForZX** [comment]
NOTE: `advertised.host.name` and `advertised.port` still work as expected, but should not be used if configuring the listeners.

If I config `listeners`, It always report this error.

I think it would be a bug.

**Comment by runkecheng** [comment]
same configuration in golang is ok
