### ISSUE TITLE
Got SyntaxError around self.async while import KafkaProducer on python 3.7.4

### ISSUE THREAD

**Issue by dynax60** [dpkp/kafka-python#1906]
I'm using Python 3.7.4 in PyCharm 2019.1.4 (PY-191.8026.44). I have installed kafka-1.3.5. When I import KafkaProducer, I get an error:

```
(venv-py) D:\PycharmProjects\FCOP>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from kafka import KafkaProducer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\PycharmProjects\FCOP\venv-py\lib\site-packages\kafka\__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "D:\PycharmProjects\FCOP\venv-py\lib\site-packages\kafka\producer\__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "D:\PycharmProjects\FCOP\venv-py\lib\site-packages\kafka\producer\simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                                  ^
SyntaxError: invalid syntax
>>>
```

**Comment by dynax60** [comment]
As I guess `async` is a keyword beginning from Python 3.7.

**Comment by dynax60** [comment]
Sorry. It was already fixed in new versions.
Duplicate of #1451

**Comment by theabhisheksinha** [comment]
I am presently running on:

PS C:\Apache\Kafka\kafka_2.13-2.4.0\bin\windows> pip install kafka-python
Requirement already satisfied: kafka-python in c:\python3.8.1\lib\site-packages (2.0.1)

yet I face this issue :

PS C:\Apache\Kafka\kafka_2.13-2.4.0\bin\windows> python .\test.py
Traceback (most recent call last):
File ".\test.py", line 5, in
from kafka import KafkaConsumer
File "C:\python3.8.1\lib\site-packages\kafka_init_.py", line 23, in
from kafka.producer import KafkaProducer
File "C:\python3.8.1\lib\site-packages\kafka\producer_init_.py", line 4, in
from .simple import SimpleProducer
File "C:\python3.8.1\lib\site-packages\kafka\producer\simple.py", line 54
return '' % self.async
^

Any thoughts on how to fix this?

**Comment by akashhotwani9** [comment]
Hi guys, i am also getting the same issue. Does anyone have any idea on how to resolve the issue?

 File "D:\OBP-Kafka-Python-master\server.py", line 21, in <module>
    from kafka import KeyedProducer, KafkaConsumer, KafkaClient
  File "C:\Users\T03160\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kafka\__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "C:\Users\T03160\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kafka\producer\__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "C:\Users\T03160\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kafka\producer\simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax

**Comment by tvoinarovskyi** [comment]
The issue is fixed in the new version of kafka-python, please update using `pip install -U kafka-python` or `conda update`, depending on what you are using.

**Comment by tvoinarovskyi** [comment]
Ohh, sorry, I get the issue. You seem to have `kafka` package installed, that is a forbidden package and is not updated. Please:
* remove both `kafka` and `kafka-python` packages using `pip uninstall` command
* Reinstall only `kafka-python` package. 

You need to remove both packages to ensure python loads the `kafka` module properly. Sorry for the trouble.
Relates to https://github.com/dpkp/kafka-python/issues/1253

**Comment by PriyaranjanMaratheDish** [comment]
Get the same issue after doing this. Do I need to restart my laptop?
