### ISSUE TITLE
Kafka write Error in Linux

### ISSUE THREAD

**Issue by Laurel-rao** [dpkp/kafka-python#1952]
# send_message Error

- Environment : Redhat 7
- producer : SimpleProducer
- client : SimpleClient
- kafka-python: 1.4.4

> The following is log.
```

2019-11-13 16:23:16 -[/usr/local/src/development/SNO_collection_plat/project_dir/app/Operater/views.py:174] - ERROR - Traceback (most recent call last):
  File "/usr/local/src/development/SNO_collection_plat/project_dir/app/Operater/views.py", line 172, in handle_device
    self.write_to_db(result, device_login_msg.get("login_data"))
  File "/usr/local/src/development/SNO_collection_plat/project_dir/app/Operater/views.py", line 183, in write_to_db
    kafka.produce(json.dumps(data))
  File "/usr/local/src/development/SNO_collection_plat/project_dir/app/Persistence/kafka_producer.py", line 24, in produce
    self._producer.send_messages(self._topic, msg.encode('utf-8'))
  File "/usr/local/lib/python3.6/site-packages/kafka/producer/simple.py", line 50, in send_messages
    topic, partition, *msg
  File "/usr/local/lib/python3.6/site-packages/kafka/producer/base.py", line 387, in send_messages
    return self._send_messages(topic, partition, *msg)
  File "/usr/local/lib/python3.6/site-packages/kafka/producer/base.py", line 430, in _send_messages
    fail_on_error=self.sync_fail_on_error
  File "/usr/local/lib/python3.6/site-packages/kafka/client.py", line 643, in send_produce_request
    resps = self._send_broker_aware_request(payloads, encoder, decoder)
  File "/usr/local/lib/python3.6/site-packages/kafka/client.py", line 276, in _send_broker_aware_request
    read_socks, _, _ = select.select(sockets, [], [])
ValueError: filedescriptor out of range in select(）
```

- I had seen the issue #613 #640，but they both use the client_async. Because of the data was important, I afraid the data was lost.
- I have google the select function in Linux was limited by 1024, should we upgrade the select to 
the selectors.
- And so when i use the Windows, there's no error comes up.

**Comment by dpkp** [comment]
SimpleConsumer was deprecated some time ago and has recently been removed from the kafka-python codebase. You should upgrade to KafkaConsumer as soon as possible. KafkaConsumer uses `selectors` and will not have this problem.
