### ISSUE TITLE
do_handshake error appearing randomly

### ISSUE THREAD

**Issue by FrancoisFerrariKpler** [dpkp/kafka-python#2098]
Hi,

We keep having issues while writing messages to Kafka and we don't understand why, this issues do not happen too frequently but they are causing troubles, here is the stack trace for the error we have. Would you have an idea from what this error can come ?

We use the version 2.0.0 of the library,

Thank you

Traceback (most recent call last):
File "/home/XXXXXXXX/.virtualenvs/YYYY/lib/python3.7/site-packages/kafka/producer/sender.py", line 74, in run self.run_once()
File "/home/XXXXXXXX/.virtualenvs/YYYY/lib/python3.7/site-packages/kafka/producer/sender.py", line 160, in run_once self._client.poll(timeout_ms=poll_timeout_ms)
File "/home/XXXXXXXX/.virtualenvs/YYYY/lib/python3.7/site-packages/kafka/client_async.py", line 580, in poll self._maybe_connect(node_id)
File "/home/XXXXXXXX/.virtualenvs/YYYY/lib/python3.7/site-packages/kafka/client_async.py", line 390, in _maybe_connect conn.connect()
File "/home/XXXXXXXX/.virtualenvs/YYYY/lib/python3.7/site-packages/kafka/conn.py", line 426, in connect if self._try_handshake():
File "/home/XXXXXXXX/.virtualenvs/YYYY/lib/python3.7/site-packages/kafka/conn.py", line 505, in _try_handshake self._sock.do_handshake()
File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake self._sslobj.do_handshake()
OSError: [Errno 0] Error

**Comment by ErikBrewster** [comment]
OSError 0 appears to be a Python bug on how it handles TLS handshakes with a bad EOF. https://bugs.python.org/issue31122

The OSError 0 just gets kafka-python into an endless loop of exceptions, like you show above. Moving to Python >=3.9 gets a fix where Python will report the same as ssl.SSLEOFError, which kafka-python handles better. Better to me means trying to reconnect constantly, but will get out of the exception / retry loop when the network behaves better. In Python 3.9.6, instead of OSError 0, I see this log entry

WARNING:2021-09-03 07:14:06,325:kafka.conn:514:SSL connection closed by server during handshake.

I think some back off time for reconnect would be good, but at least not getting trapped in an endless loop is an improvement.
