### ISSUE TITLE
Exception in thread kafka-python-producer-XXX (most likely raised during interpreter shutdown)

### ISSUE THREAD

**Issue by huqd** [dpkp/kafka-python#2103]
This sometimes happened on our server.
Thanks

Exception in thread kafka-python-producer-1-network-thread (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/kafka/producer/sender.py", line 60, in run
  File "/usr/local/lib/python2.7/dist-packages/kafka/producer/sender.py", line 160, in run_once
  File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 600, in poll
  File "/usr/lib/python2.7/threading.py", line 216, in __exit__
  File "/usr/lib/python2.7/threading.py", line 203, in release

**Comment by jeffwidman** [comment]
What version of `kafka-python` / python 2? 

Can you run this under python 3 and see if you still hit it? Others may feel differently, but I'm not interested in spending time supporting python 2 given that it's EOL'd and the threading implementation has changed a bit under python 3.
