### ISSUE TITLE
KafkaAdminClient gives NodeNotReady error whereas KafkaConsumer works fine

### ISSUE THREAD

**Issue by sherry-ummen** [dpkp/kafka-python#2135]
Hello,
Using the latest version 2.0.2
Trying to understand why KafkaAdminClient fails but KafkaConsumer works fine. I have tried like this

```
>>> client = KafkaAdminClient(bootstrap_servers=['some-address:9093'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kafka/admin/client.py", line 218, in __init__
    self._refresh_controller_id()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kafka/admin/client.py", line 278, in _refresh_controller_id
    controller_version = self._client.check_version(controller_id, timeout=(self.config['api_version_auto_timeout_ms'] / 1000))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kafka/client_async.py", line 909, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kafka/conn.py", line 1240, in check_version
    raise Errors.NodeNotReadyError()
kafka.errors.NodeNotReadyError: NodeNotReadyError
```

```
>>> consumer = KafkaConsumer(bootstrap_servers=['some-address:9093'])
>>> consumer.topics()
```

**Comment by Mostafa-Elmenbawy** [comment]
Duplicate https://github.com/dpkp/kafka-python/issues/2093

**Comment by sherry-ummen** [comment]
yeah .. i did set the KAFKA_ADVERTISED_LISTENERS env variable .. but apparently the confluent helm chart has a small quirk that you need to set the configurationOverrides.advertised.listeners then its templating works correctly ...anyway adding that fixed the issue. closing it
