### ISSUE TITLE
"unpack requires a buffer of 4 bytes" exception encountered in 2.0.2 release

### ISSUE THREAD

**Issue by indywidualny** [dpkp/kafka-python#2170]
I'm posting logs from our test instance. We never seen those on production, probably due to a different log level. It doesn't prevent Kafka Consumer from running properly.

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/types.py", line 20, in _unpack
    (value,) = f(data)
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/kafka/coordinator/assignors/sticky/sticky_assignor.py", line 633, in parse_member_metadata
    decoded_user_data = StickyAssignorUserDataV1.decode(user_data)
  File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/struct.py", line 50, in decode
    return cls(*[field.decode(data) for field in cls.SCHEMA.fields])
  File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/struct.py", line 50, in <listcomp>
    return cls(*[field.decode(data) for field in cls.SCHEMA.fields])
  File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/types.py", line 193, in decode
    return [self.array_of.decode(data) for _ in range(length)]
  File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/types.py", line 193, in <listcomp>
    return [self.array_of.decode(data) for _ in range(length)]
  File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/types.py", line 152, in decode
    return tuple([field.decode(data) for field in self.fields])
  File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/types.py", line 152, in <listcomp>
    return tuple([field.decode(data) for field in self.fields])
  File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/types.py", line 190, in decode
    length = Int32.decode(data)
  File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/types.py", line 64, in decode
    return _unpack(cls._unpack, data.read(4))
  File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/types.py", line 23, in _unpack
    raise ValueError("Error encountered when attempting to convert value: "
ValueError: Error encountered when attempting to convert value: b'\x017' to struct format: '<built-in method unpack of Struct object at 0x7f5b4fdaca70>', hit error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/crawlinski/worker/utils/jobs.py", line 50, in get_messages
    data = self.consumer.poll(timeout_ms=self.timeout, max_records=max_records)
  File "/usr/local/lib/python3.8/dist-packages/kafka/consumer/group.py", line 655, in poll
    records = self._poll_once(remaining, max_records, update_offsets=update_offsets)
  File "/usr/local/lib/python3.8/dist-packages/kafka/consumer/group.py", line 675, in _poll_once
    self._coordinator.poll()
  File "/usr/local/lib/python3.8/dist-packages/kafka/coordinator/consumer.py", line 289, in poll
    self.ensure_active_group()
  File "/usr/local/lib/python3.8/dist-packages/kafka/coordinator/base.py", line 407, in ensure_active_group
    self._client.poll(future=future)
  File "/usr/local/lib/python3.8/dist-packages/kafka/client_async.py", line 606, in poll
    responses.extend(self._fire_pending_completed_requests())
  File "/usr/local/lib/python3.8/dist-packages/kafka/client_async.py", line 738, in _fire_pending_completed_requests
    future.success(response)
  File "/usr/local/lib/python3.8/dist-packages/kafka/future.py", line 36, in success
    self._call_backs('callback', self._callbacks, self.value)
  File "/usr/local/lib/python3.8/dist-packages/kafka/future.py", line 79, in _call_backs
    f(value)
  File "/usr/local/lib/python3.8/dist-packages/kafka/coordinator/base.py", line 523, in _handle_join_group_response
    self._on_join_leader(response).chain(future)
  File "/usr/local/lib/python3.8/dist-packages/kafka/coordinator/base.py", line 587, in _on_join_leader
    group_assignment = self._perform_assignment(response.leader_id,
  File "/usr/local/lib/python3.8/dist-packages/kafka/coordinator/consumer.py", line 334, in _perform_assignment
    assignments = assignor.assign(self._cluster, member_metadata)
  File "/usr/local/lib/python3.8/dist-packages/kafka/coordinator/assignors/sticky/sticky_assignor.py", line 597, in assign
    members_metadata[consumer] = cls.parse_member_metadata(member_metadata)
  File "/usr/local/lib/python3.8/dist-packages/kafka/coordinator/assignors/sticky/sticky_assignor.py", line 636, in parse_member_metadata
    log.error("Could not parse member data", e)     # pylint: disable=logging-too-many-args
Message: 'Could not parse member data'
Arguments: (ValueError("Error encountered when attempting to convert value: b'\\x017' to struct format: '<built-in method unpack of Struct object at 0x7f5b4fdaca70>', hit error: unpack requires a buffer of 4 bytes"),)
```

**Comment by dpkp** [comment]
Looks like this is being caused by the new StickyAssignor feature decoding user-data. This feels like it may be related to KIP-482, which modifies binary encodings for some messages. What version of kafka broker are you using? Are you mixing kafka-python consumers with java consumers in the same group? Are you specifying `partition_assignment_strategy` in your KafkaConsumer configuration? I think if you are able to disable the StickyPartitionAssignor then this error would not be triggered.

**Comment by indywidualny** [comment]
True, we use StickyPartitionAssignor in all our consumers since recently. Your library only, no Java used whatsoever. Kafka Broker is the one from Docker image `confluentinc/cp-kafka:5.5.1` so our version is `confluent-kafka-2.12, 5.5.1-1`.

After few restarts of the consumer the error is gone - weird. When I'm able to reproduce it I will update the issue.

**Comment by jeffwidman** [comment]
It'd be helpful if you were able to find out exactly what's being sent over the wire here so that we can see the specific bytes that aren't being properly unpacked.

**Comment by indywidualny** [comment]
Got it solved. Apparently you cannot use the same consumer group in 2 or more consumers within the same process no matter what separate topics are assigned to those consumers. My latest pull request fixes the issue to the state when you get only a warning about partition being assigned to 2 consumers instead of the error above and constant rebalance happens. No matter what topics you consume on the same process you cannot use the same groups. Different groups and my fix solved this for good.

**Comment by jeffwidman** [comment]
> Apparently you cannot use the same consumer group in 2 or more consumers within the same process no matter what separate topics are assigned to those consumers

Per the KIP, you should be able to have two consumers, distinct assignments, same group, and it should work. If not, that's probably a bug.

I'm not understanding how whether or not they share the same process space would affect things? Is there some state that is shared but shouldn't be?

**Comment by indywidualny** [comment]
Yes, probably a bug. I created 2 separate consumer instances with different topics but with the same group id. This caused the problem I was talking about. Changing groups globally is a workaround I believe but we needed this working ASAP so we did this.

To provide more info we use the same event asyncio and the same event loop for two separate consumer objects with Sticky Partition Assignment enabled only.

App uses multiprocessing (spawn mode, so separate interpreters) and separate processes didn't cause the issue. Possibly there's some interference within the same one.

**Comment by dpkp** [comment]
Do you mean literally the solution was to change your group of? If so, this
suggests that some previous consumer commit data to the group with bytes
that we can't don't understand. It would still be great to see those bytes.
My hunch is that they were sent by a Java consumer that uses kip 482
encoding. Did you ever use a console consumer in that group?

**Comment by indywidualny** [comment]
We only use this library exclusively. We used Java console consumer a month ago for testing but definitely not recently. Before changing the groups do be different ones we encountered this:

```.[WARNING 2020-11-19 11:39:40,392 sticky_assignor:200] [139737690318592] Partition TopicPartition(topic='data-any', partition=98) is assigned to multiple consumers following sticky assignment generation 2026.
[WARNING 2020-11-19 11:39:40,392 sticky_assignor:200] [139737690318592] Partition TopicPartition(topic='data-any', partition=99) is assigned to multiple consumers following sticky assignment generation 2026.
```

+ Heartbeat failed, the group is rebalancing every second or so on both consumers.

The ultimate solution was different group id for 2 separate consumers. Literally. Then the problem was gone. I can provide some more input but I also don't understand the exact reasons and how to debug it properly.

**Comment by indywidualny** [comment]
Important: the problem with unpack was only present while this applied: https://github.com/dpkp/kafka-python/pull/2167/commits/3c7449971cdd7731ce1421cca7869a8b7afe97bc

Final commit in the pull request changed the behavior to the one from my post above: https://github.com/dpkp/kafka-python/pull/2167/commits/6c20db681ab57f94fb1627424d79983605b94ddd
