### ISSUE TITLE
kafka-python 2.0.1 Exception ignored under Pypi

### ISSUE THREAD

**Issue by Federico-Comesana** [dpkp/kafka-python#2220]
Following this [issue from 2018](https://github.com/dpkp/kafka-python/issues/1632). It was closed but it seems to continue appearing in v2.0.1

Any idea what is happening here?

> Exception ignored in: <bound method KafkaProducer.del of <kafka.producer.kafka.KafkaProducer object at 0x7f968daf5940>>
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 448, in del
File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 461, in close
File "/usr/local/lib/python3.6/logging/init.py", line 1305, in info
File "/usr/local/lib/python3.6/logging/init.py", line 1546, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
Exception ignored in: <bound method KafkaProducer.del of <kafka.producer.kafka.KafkaProducer object at 0x7f968ccb70f0>>
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 448, in del
File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 461, in close
File "/usr/local/lib/python3.6/logging/init.py", line 1305, in info
File "/usr/local/lib/python3.6/logging/init.py", line 1546, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'

**Comment by jpribyl** [comment]
https://github.com/dpkp/kafka-python/pull/2043/files

in case anyone else stumbles across this
