### ISSUE TITLE
UnrecognizedBrokerVersion error for Kafka 2.6.2 running on AWS MSK

### ISSUE THREAD

**Issue by AndrewHannigan** [dpkp/kafka-python#2279]
Running Kafka 2.6.2 on AWS MSK, and getting an UnrecognizedBrokerVersion error

```
Traceback (most recent call last):
  File "/home/ubuntu/repos/confluent-relay/confluent_relay.py", line 3, in <module>
    consumer = kafka.KafkaConsumer(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 358, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kafka/client_async.py", line 909, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kafka/conn.py", line 1298, in check_version
    raise Errors.UnrecognizedBrokerVersion()
kafka.errors.UnrecognizedBrokerVersion: UnrecognizedBrokerVersion
```

**Comment by AndrewHannigan** [comment]
Resolved by specifying api version manually via the `api_version` argument to `KafkaConsumer`.  Still puzzled why it couldn't infer this automatically though.
