### ISSUE TITLE
Kafka-python doens't recognize cafile with Kafka SSL enabled

### ISSUE THREAD

**Issue by GiuseppePegasus** [dpkp/kafka-python#2280]
I try to implement a Kafka producer with Kafka SSL enabled.
When I launch the producer I receive the error of No such file o directory.
My producer.py:

`from kafka import KafkaProducer

kafkaBrokers='localhost:9092'
caRootLocation='/home/kafka/ssl2/pem_producer/CARoote.pem' 
certLocation='/home/kafka/ssl2/pem_producer/CARoote.pemcertificate.pem'
keyLocation='/home/kafka/ssl2/pem_producer/CARoote.pemkey.pem'
topic='ssl-topic'
password='secret'

producer = KafkaProducer(bootstrap_servers=kafkaBrokers,
                         security_protocol='SSL',
                         ssl_check_hostname=True,
                         ssl_cafile=caRootLocation,
                         ssl_certfile=certLocation,
                         ssl_keyfile=keyLocation,
                         ssl_password=password)

producer.send(topic, bytes('Hello Kafka!','utf-8'))
`

The traceback:

`Traceback (most recent call last):
  File "producer.py", line 22, in <module>
    producer = KafkaProducer(bootstrap_servers=kafkaBrokers,
  File "/home/kafka/anaconda3/envs/kafka/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/kafka/anaconda3/envs/kafka/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/kafka/anaconda3/envs/kafka/lib/python3.8/site-packages/kafka/client_async.py", line 909, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "/home/kafka/anaconda3/envs/kafka/lib/python3.8/site-packages/kafka/conn.py", line 1238, in check_version
    if not self.connect_blocking(timeout_at - time.time()):
  File "/home/kafka/anaconda3/envs/kafka/lib/python3.8/site-packages/kafka/conn.py", line 340, in connect_blocking
    self.connect()
  File "/home/kafka/anaconda3/envs/kafka/lib/python3.8/site-packages/kafka/conn.py", line 401, in connect
    self._wrap_ssl()
  File "/home/kafka/anaconda3/envs/kafka/lib/python3.8/site-packages/kafka/conn.py", line 473, in _wrap_ssl
    self._ssl_context.load_verify_locations(self.config['ssl_cafile'])
FileNotFoundError: [Errno 2] No such file or directory
`

**Comment by GiuseppePegasus** [comment]
This row must be:

caRootLocation='/home/kafka/ssl2/pem_producer/CARoot.pem'
