### ISSUE TITLE
High CPU usage during bootstrapping if broker never accepts tcp connection

### ISSUE THREAD

**Issue by ping235** [dpkp/kafka-python#2299]
This issue has similarities with #1166 which has been fixed, however it represent on latest version(v2.0.2).

### Problem
Shutdown kafka broker or drop all traffic to port 9092
... and then running this python script:

```
import kafka

kafka.KafkaClient(bootstrap_servers='127.0.0.1:9092', api_version_auto_timeout_ms=5000)
```
... it will draw 90~100% cpu for 5 seconds(api_version_auto_timeout_ms reached)

Expected behavior:
Script draws a reasonable amount of CPU

Actual behavior:
Script draws as much cpu as it gets.

### Additional information
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/venvs/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/root/venvs/lib/python3.8/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

### Version used
v2.0.2

**Comment by dpkp** [comment]
You should pass `api_version` to avoid dynamically checking and risking `NoBrokersAvailable` error.
