### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by SmasterZheng** [dpkp/kafka-python#2338]
simple.py  line 54 
self.async

**Comment by oolongtea** [comment]
same error with python 3.10.6 and kafka==1.3.5
```
Traceback (most recent call last):
  File "/home/.../my-script.py", line 7, in <module>
    from kafka import KafkaConsumer, KafkaProducer
  File "/home/.../my-env/lib/python3.10/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/.../my-env/lib/python3.10/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/.../my-env/lib/python3.10/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^^^^^
SyntaxError: invalid syntax
```

**Comment by wbarnha** [comment]
SimpleProducers and other `Simple` classes were removed in https://github.com/dpkp/kafka-python/pull/1196. Upgrading your kafka-python installation is recommended.
