### ISSUE TITLE
Logging in __del__ func causes "NameError: name 'open' is not defined"

### ISSUE THREAD

**Issue by jue-jue-zi** [dpkp/kafka-python#2393]
https://github.com/dpkp/kafka-python/blob/a33fcf4d22bdf34e9660e394a7a6f84225411325/kafka/coordinator/base.py#L748

Exception traceback

```
Exception ignored in: <function ConsumerCoordinator.__del__ at 0x7f43cae47700>
Traceback (most recent call last):
  File "/data/miniconda3/envs/test/lib/python3.8/site-packages/kafka/coordinator/consumer.py", line 132, in __del__
  File "/data/miniconda3/envs/test/lib/python3.8/site-packages/kafka/coordinator/base.py", line 756, in __del__
  File "/data/miniconda3/envs/test/lib/python3.8/site-packages/kafka/coordinator/base.py", line 748, in _close_heartbeat_thread
  File "/data/miniconda3/envs/test/lib/python3.8/logging/__init__.py", line 1446, in info
  File "/data/miniconda3/envs/test/lib/python3.8/logging/__init__.py", line 1589, in _log
  File "/data/miniconda3/envs/test/lib/python3.8/logging/__init__.py", line 1599, in handle
  File "/data/miniconda3/envs/test/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
  File "/data/miniconda3/envs/test/lib/python3.8/logging/__init__.py", line 954, in handle
  File "/data/miniconda3/envs/test/lib/python3.8/logging/__init__.py", line 1186, in emit
  File "/data/miniconda3/envs/test/lib/python3.8/logging/__init__.py", line 1176, in _open
NameError: name 'open' is not defined
```

**Comment by dpkp** [comment]
Exceptions in __del__ are logged only. You can safely ignore.
