### ISSUE TITLE
[Python 3.12.0] ModuleNotFoundError: No module named 'kafka.vendor.six.moves' 

### ISSUE THREAD

**Issue by pawel-swiecki-saucelabs** [dpkp/kafka-python#2401]
## Given

```bash
$ python --version
Python 3.12.0

$ pip freeze
kafka-python==2.0.2
```

my system: `Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 arm64`

## Current behaviour
```python
Python 3.12.0 (main, Oct  9 2023, 10:31:21) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kafka.consumer.group import KafkaConsumer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/[...]/lib/python3.12/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.consumer import KafkaConsumer
  File "/Users/[...]/lib/python3.12/site-packages/kafka/consumer/__init__.py", line 3, in <module>
    from kafka.consumer.group import KafkaConsumer
  File "/Users/[...]/lib/python3.12/site-packages/kafka/consumer/group.py", line 13, in <module>
    from kafka.consumer.fetcher import Fetcher
  File "/Users/[...]/lib/python3.12/site-packages/kafka/consumer/fetcher.py", line 19, in <module>
    from kafka.record import MemoryRecords
  File "/Users/[...]/lib/python3.12/site-packages/kafka/record/__init__.py", line 1, in <module>
    from kafka.record.memory_records import MemoryRecords, MemoryRecordsBuilder
  File "/Users/[...]/lib/python3.12/site-packages/kafka/record/memory_records.py", line 27, in <module>
    from kafka.record.legacy_records import LegacyRecordBatch, LegacyRecordBatchBuilder
  File "/Users/[...]/lib/python3.12/site-packages/kafka/record/legacy_records.py", line 50, in <module>
    from kafka.codec import (
  File "/Users/[...]/lib/python3.12/site-packages/kafka/codec.py", line 9, in <module>
    from kafka.vendor.six.moves import range
ModuleNotFoundError: No module named 'kafka.vendor.six.moves'
>>> 
```

## Expected behaviour
```python
Python 3.12.0 (main, Oct  9 2023, 10:31:21) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kafka.consumer.group import KafkaConsumer
>>>
```
(no error)

**Comment by pawel-swiecki-saucelabs** [comment]
On the latest Python 3.11 it works:

```bash
$ python --version
Python 3.11.6

$ pip freeze
kafka-python==2.0.2

$ python
Python 3.11.6 (main, Oct 10 2023, 17:17:53) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kafka.consumer.group import KafkaConsumer
>>> KafkaConsumer
<class 'kafka.consumer.group.KafkaConsumer'>
>>>
```

**Comment by pawel-swiecki-saucelabs** [comment]
It turns out there already is a relevant [MR waiting for review](https://github.com/dpkp/kafka-python/pull/2398).

**Comment by mnito** [comment]
Until the above PR is merged and a new version of this library is released, running the snippet below before importing kafka-python works around the issue (assuming `six>=1.16.0` is installed):

```python
import six

if sys.version_info >= (3, 12, 0):
    sys.modules['kafka.vendor.six.moves'] = six.moves
```
