### ISSUE TITLE
"import kafka" fails with "ModuleNotFoundError: No module named 'kafka.vendor.six.moves'" under Python 3.12

### ISSUE THREAD

**Issue by gtzampanakis** [dpkp/kafka-python#2412]
I have verified this on Linux and Windows, even though the output below is from Linux:

```
user1@CY1-WL-337:~/dev$ python3.12 -m venv venv
user1@CY1-WL-337:~/dev$ source venv/bin/activate
(venv) user1@CY1-WL-337:~/dev$ pip install kafka-python
Collecting kafka-python
  Using cached kafka_python-2.0.2-py2.py3-none-any.whl (246 kB)
Installing collected packages: kafka-python
Successfully installed kafka-python-2.0.2

(venv) user1@CY1-WL-337:~/dev$ python -c 'import kafka'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user1/dev/venv/lib/python3.12/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.consumer import KafkaConsumer
  File "/home/user1/dev/venv/lib/python3.12/site-packages/kafka/consumer/__init__.py", line 3, in <module>
    from kafka.consumer.group import KafkaConsumer
  File "/home/user1/dev/venv/lib/python3.12/site-packages/kafka/consumer/group.py", line 13, in <module>
    from kafka.consumer.fetcher import Fetcher
  File "/home/user1/dev/venv/lib/python3.12/site-packages/kafka/consumer/fetcher.py", line 19, in <module>
    from kafka.record import MemoryRecords
  File "/home/user1/dev/venv/lib/python3.12/site-packages/kafka/record/__init__.py", line 1, in <module>
    from kafka.record.memory_records import MemoryRecords, MemoryRecordsBuilder
  File "/home/user1/dev/venv/lib/python3.12/site-packages/kafka/record/memory_records.py", line 27, in <module>
    from kafka.record.legacy_records import LegacyRecordBatch, LegacyRecordBatchBuilder
  File "/home/user1/dev/venv/lib/python3.12/site-packages/kafka/record/legacy_records.py", line 50, in <module>
    from kafka.codec import (
  File "/home/user1/dev/venv/lib/python3.12/site-packages/kafka/codec.py", line 9, in <module>
    from kafka.vendor.six.moves import range
ModuleNotFoundError: No module named 'kafka.vendor.six.moves'
```

**Comment by wbarnha** [comment]
This was patched in https://github.com/dpkp/kafka-python/pull/2398 and will be resolved in the next release. I apologize for the delay. Hopefully running `pip install git+https://github.com/dpkp/kafka-python.git` could fulfill your needs in the meantime.

**Comment by simcax** [comment]
> This was patched in #2398 and will be resolved in the next release. I apologize for the delay. Hopefully running `pip install git+https://github.com/dpkp/kafka-python.git` could fulfill your needs in the meantime.
> 
> Please understand that I am doing everything within my means to get a release out to the public.

Is there an idea of when the next release will be out?

**Comment by wbarnha** [comment]
No update, sorry. 😔

**Comment by VishnuBhaarath** [comment]
Hi @wbarnha  ,
  The issue still persists and I am facing the same issue, can you pls provide an update when the fix will be rolloed out.
Thanks

**Comment by wbarnha** [comment]
I am aware of the issue. Please refer to https://github.com/dpkp/kafka-python/issues/2412#issuecomment-1806341342.

**Comment by VishnuBhaarath** [comment]
Thanks for it @wbarnha  , I downgraded my python version and got it rectified.

**Comment by wbarnha** [comment]
> > This was patched in #2398 and will be resolved in the next release. I apologize for the delay. Hopefully running `pip install git+https://github.com/dpkp/kafka-python.git` could fulfill your needs in the meantime.
> > Please understand that I am doing everything within my means to get a release out to the public.
> 
> @wbarnha Thank you William for your support here. Installing `python -m pip install --break-system-packages git+https://github.com/dpkp/kafka-python.git` still is not resolving the issue.
> 
> i can not downgrade python 3.11 due to a HIGH vulnerability with ecdsa pacakge. Any work around solution for this problem at the moment?

The current workaround solution would be to replace your `kafka-python` installation with my fork at `kafka-python-ng` for now.

**Comment by ssbarnea** [comment]
Can we please reopen this bug because a critical bug like this should not be closed until the fix is released.

**Comment by winniegr** [comment]
I also have the same issue

**Comment by pauliverson** [comment]
i meet this problem in python3.12 kafka-python 2.0.2，so how to solve this problem

**Comment by wbarnha** [comment]
> Can we please reopen this bug because a critical bug like this should not be closed until the fix is released. I would even pin it after reopening it, just to remind everyone about it.

It's a fair point, and since there's a demand to reopen this, I'll oblige!

**Comment by Bhargavacharanreddy** [comment]
Hi Everyone, 

I am also facing the same issue.  I am working on a script to publish messages to kafka topic. In my python script, I have below code. 
`from kafka import KafkaProducer`

Whenever I am trying to execute the script, I am facing below error.
`ModuleNotFoundError: No module named 'kafka.vendor.six.moves'`

I have Python 3.12.5 installed.

Let me know how to resolve this. 
Thanks!

**Comment by gwenshap** [comment]
This is still not fixed, and have been open for a year now. 
Does everyone really install from the github repo? Is it so hard to do a release? 

Anyway, commenting to show additional demand. Although demand for "be able to use the library" seems self-explanatory...

**Comment by csharplus** [comment]
Will this fix be released in the near future?

**Comment by HiMyNameIsBoxxy** [comment]
> > > This was patched in #2398 and will be resolved in the next release. I apologize for the delay. Hopefully running `pip install git+https://github.com/dpkp/kafka-python.git` could fulfill your needs in the meantime.
> > > Please understand that I am doing everything within my means to get a release out to the public.
> > 
> > 
> > @wbarnha Thank you William for your support here. Installing `python -m pip install --break-system-packages git+https://github.com/dpkp/kafka-python.git` still is not resolving the issue.
> > i can not downgrade python 3.11 due to a HIGH vulnerability with ecdsa pacakge. Any work around solution for this problem at the moment?
> 
> The current workaround solution would be to replace your `kafka-python` installation with my fork at `kafka-python-ng` for now.

Thank god. The fork version saved the day.

**Comment by BSpendlove** [comment]
rip

**Comment by sfjhu** [comment]
+1 having this issue

**Comment by TarcisioOliveira2021** [comment]
Hey guys, this solved it for me: pip install --break-system-packages git+https://github.com/dpkp/kafka-python.git. 

1- Uninstall kafka-python using: pip uninstall kafka-python
2- Then run: pip install --break-system-packages git+https://github.com/dpkp/kafka-python.git

**Comment by csharplus** [comment]
The following code fix works for me with the current public build of `kafka-python`:

```
import sys

if sys.version_info >= (3, 12, 0):
    import six
    sys.modules['kafka.vendor.six.moves'] = six.moves

.....

from kafka import KafkaConsumer, KafkaProducer
......
```

**Comment by ernestaskardzys** [comment]
@csharplus , can confirm, that your workaround helped me to resolve the issue with kafka-python:2.0.2

**Comment by aHemanth123** [comment]
@csharplus, It is working.

**Comment by ytqxyd** [comment]
> This was patched in #2398 and will be resolved in the next release. I apologize for the delay. Hopefully running `pip install git+https://github.com/dpkp/kafka-python.git` could fulfill your needs in the meantime.
> 
> Please understand that I am doing everything within my means to get a release out to the public.

Is there any scheduled release for this bugfix?

**Comment by palm-octo-chainsaw** [comment]
+1

**Comment by Luonic** [comment]
+1

**Comment by encouver** [comment]
+1

**Comment by davidegdev** [comment]
kafka-python is tested on python 2.7, 3.4, 3.7, and pypy2.7.

**Comment by bfontaine** [comment]
This project has been unmaintained for almost a year; as the README suggests you might have better luck using [kafka-python-ng](https://github.com/wbarnha/kafka-python-ng). As multiple persons have confirmed, [this workaround](https://github.com/dpkp/kafka-python/issues/2412#issuecomment-2394344022) works.

(please stop adding "+1" comments; it’s useless and you’re notifying 20+ accounts for nothing each time)

**Comment by davidegdev** [comment]
Actually, I'm working correctly with the Python 3.7 version. Greetings

**Comment by bfontaine** [comment]
> Actually, I'm working correctly with the Python 3.7 version. Greetings

The issue is about Python 3.12; Python versions up to 3.11.x are fine.

**Comment by Kszajga** [comment]
And still do not work with Python 3.13

**Comment by daiglejacob** [comment]
+1 for issue being present on pthon 3.12.3

**Comment by ishit1011** [comment]
@csharplus Thank you so much ! Working now

**Comment by SatyaRajAwasth1** [comment]
Issue still persists! I was in the very early stage of my project so moved further ahead with **confluent-kafka** package.

**Comment by dpkp** [comment]
This was fixed in #2398 . This issue is a duplicate of #2401
