### ISSUE TITLE
invalid literal for int() with base 10: 'A.B.C.D'

### ISSUE THREAD

**Issue by AgentK9** [dpkp/kafka-python#2427]
Hey everyone,

Trying to use kafka-python to create a topic.

Here's the code I'm using:

```python
from kafka import KafkaProducer
from kafka.admin import KafkaAdminClient, NewTopic

server_ip = "A.B.C.D:9094"
client_id = "populater"

admin_client = KafkaAdminClient(
    bootstrap_servers=server_ip,
    client_id=client_id,
)
```

And the error I'm getting:

```
Traceback (most recent call last):
  File "/home/kgb0110l/pipeline/src/rif_pipeline/other/populate_scaffold.py", line 10, in <module>
    admin_client = KafkaAdminClient(
                   ^^^^^^^^^^^^^^^^^
  File "/home/kgb0110l/.cache/pypoetry/virtualenvs/rif-pipeline-Xe0e8OMc-py3.11/lib/python3.11/site-packages/kafka/admin/client.py", line 218, in __init__
    self._refresh_controller_id()
  File "/home/kgb0110l/.cache/pypoetry/virtualenvs/rif-pipeline-Xe0e8OMc-py3.11/lib/python3.11/site-packages/kafka/admin/client.py", line 278, in _refresh_controller_id
    controller_version = self._client.check_version(controller_id, timeout=(self.config['api_version_auto_timeout_ms'] / 1000))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kgb0110l/.cache/pypoetry/virtualenvs/rif-pipeline-Xe0e8OMc-py3.11/lib/python3.11/site-packages/kafka/client_async.py", line 901, in check_version
    self._maybe_connect(try_node)
  File "/home/kgb0110l/.cache/pypoetry/virtualenvs/rif-pipeline-Xe0e8OMc-py3.11/lib/python3.11/site-packages/kafka/client_async.py", line 376, in _maybe_connect
    host, port, afi = get_ip_port_afi(broker.host)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kgb0110l/.cache/pypoetry/virtualenvs/rif-pipeline-Xe0e8OMc-py3.11/lib/python3.11/site-packages/kafka/conn.py", line 1478, in get_ip_port_afi
    port = int(port)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'A.B.C.D'
```

(Note that A.B.C.D is an IPV4 address)

I don't see why this is happening in my code, so it seems to be on your end - any ideas?

Does one of the APIs modify the hostname string?

I doubt it's an issue with my kafka configuration but I'm essentially using this: https://github.com/bitnami/containers/tree/main/bitnami/kafka

**Comment by AgentK9** [comment]
This was a configuration issue on my part.
