### ISSUE TITLE
ensure_topic_exists : kafka_python-0.9.4-py2.7.egg/kafka/common.py:233: UnknownError

### ISSUE THREAD

**Issue by jamesblackburn** [dpkp/kafka-python#422]
I'm seeing an issue where ```ensure_topic_exists``` fails with an ```UnknownError```.

This occurs in integration tests which spin up a kafka, connect a kafka-python ```KafkaClient``` to it, then call ```ensure_topic_exists``` before the broker is read (I guess).

Error from kafka_python:

```
/users/is/ahlpypi/egg_cache/k/kafka_python-0.9.4-py2.7.egg/kafka/consumer/base.py:51: in __init__
    self.client.load_metadata_for_topics(topic)
/users/is/ahlpypi/egg_cache/k/kafka_python-0.9.4-py2.7.egg/kafka/client.py:378: in load_metadata_for_topics
    kafka.common.check_error(topic_metadata)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

response = TopicMetadata(topic='tests_integration_scripts_test_mkd_kafka2mongo_test_daterange_empty_queue', error=5, partitions=[])

    def check_error(response):
        if isinstance(response, Exception):
            raise response
        if response.error:
            error_class = kafka_errors.get(response.error, UnknownError)
>           raise error_class(response)
E           LeaderNotAvailableError: TopicMetadata(topic='tests_integration_scripts_test_mkd_kafka2mongo_test_daterange_empty_queue', error=5, partitions=[])

/users/is/ahlpypi/egg_cache/k/kafka_python-0.9.4-py2.7.egg/kafka/common.py:233: LeaderNotAvailableError
```

Sometimes I see the following error in kafka:

```
tests/integration/test_feed.py [2015-06-30 22:59:22,786] ERROR [KafkaApi-0] error when handling request Name: TopicMetadataRequest; Version: 0; CorrelationId: 2; ClientId: pyclient; Topics: tests_integration_test_feed_test_starts_ok_with_empty_snapshot_queue (kafka-request-handler-3 KafkaApis)
kafka.admin.AdminOperationException: replication factor: 1 larger than available brokers: 0
at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:70)
at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:171)
at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:520)
at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:503)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
at scala.collection.SetLike$class.map(SetLike.scala:92)
at scala.collection.AbstractSet.map(Set.scala:47)
at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:503)
at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:542)
at kafka.server.KafkaApis.handle(KafkaApis.scala:62)
at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:59)
at java.lang.Thread.run(Thread.java:724)
[2015-06-30 22:59:22,794] INFO [Kafka Server 0], started (main KafkaServer)
[2015-06-30 22:59:22,854] INFO New leader is 0 (ZkClient-EventThread-11-localhost:65535 ZookeeperLeaderElector$LeaderChangeListener)
[2015-06-30 22:59:22,857] INFO [BrokerChangeListener on Controller 0]: Broker change listener fired for path /brokers/ids with children 0 (ZkClient-EventThread-11-localhost:65535 ReplicaStateMachine$BrokerChangeListener)
E.INFO:root:Release zookeeper lock
```

**Comment by dpkp** [comment]
The issue here appears to be that the cluster's topic auto-creation fails because there are not enough brokers to handle the required replication. This error is external to kafka-python, though certainly error handling here was poor. The client and protocol stack has been refactored to help catch these types of errors more cleanly.
