### ISSUE TITLE
Murmur2Partitioner fails if given a bytearray key

### ISSUE THREAD

**Issue by mutability** [dpkp/kafka-python#428]
Murmur2Partitioner fails if given bytearray keys due to confusion between "key" and "data" vars:

```
Traceback (most recent call last):
[...]
  File "/usr/home/obj/.local/lib/python3.4/site-packages/kafka/producer/keyed.py", line 42, in send_messages
    partition = self._next_partition(topic, key)
  File "/usr/home/obj/.local/lib/python3.4/site-packages/kafka/producer/keyed.py", line 38, in _next_partition
    return partitioner.partition(key)
  File "/usr/home/obj/.local/lib/python3.4/site-packages/kafka/partitioner/hashed.py", line 15, in partition
    idx = (murmur2(key) & 0x7fffffff) % len(partitions)
  File "/usr/home/obj/.local/lib/python3.4/site-packages/kafka/partitioner/hashed.py", line 55, in murmur2
    length = len(data)
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by dpkp** [comment]
Fixed in PR #439
