### ISSUE TITLE
TypeError creating client

### ISSUE THREAD

**Issue by patrickmay** [dpkp/kafka-python#437]
I'm getting an error when creating a client as shown in the documentation:

Traceback (most recent call last):
  File "./profile-id-reader.py", line 40, in <module>
    consume()
  File "./profile-id-reader.py", line 27, in consume
    group_id = uuid.uuid4())
  File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/kafka.py", line 59, in __init__
    self.set_topic_partitions(*topics)
  File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/kafka.py", line 242, in set_topic_partitions
    self._get_commit_offsets()
  File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/kafka.py", line 614, in _get_commit_offsets
    kafka_bytestring(self._config['group_id']),
  File "/usr/local/lib/python2.7/dist-packages/kafka/util.py", line 101, in kafka_bytestring
    raise TypeError(s)
TypeError: 0f22f238-87e3-41f4-aa79-e026e86be155

**Comment by patrickmay** [comment]
This is on a Debian box with Python 2.7.3.

**Comment by dpkp** [comment]
Can you post your code? It looks like you are passing a UUID object as your group_id. You'll need to convert to a string (and encode to bytes if using python 3) before passing as a kafka group_id.
