### ISSUE TITLE
Problem using async=True

### ISSUE THREAD

**Issue by watchforstock** [dpkp/kafka-python#46]
Hi,

I'm having trouble using an asynchronous producer. I'm running the latest copy of the code from github.

I have a simple script which exhibits the problem:

``` python
from kafka.client import KafkaClient
from kafka.producer import SimpleProducer

if __name__ == '__main__':

    kafka = KafkaClient("192.168.15.136", 9092)
    producer = SimpleProducer(kafka, "test", async=True)

    producer.send_messages("Hello")
```

The log output is as follows:

```
Traceback (most recent call last):
  File "kafka_test.py", line 7, in <module>
    producer = SimpleProducer(kafka, "test", async=True)
  File "C:\Users\astock\envs\midmarket\lib\site-packages\kafka\producer.py", line 176, in __init__
    batch_send_every_t)
  File "C:\Users\astock\envs\midmarket\lib\site-packages\kafka\producer.py", line 72, in __init__
    self.proc.start()
  File "c:\python27\Lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "c:\python27\Lib\multiprocessing\forking.py", line 271, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "c:\python27\Lib\multiprocessing\forking.py", line 193, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "c:\python27\Lib\pickle.py", line 224, in dump
    self.save(obj)
  File "c:\python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\python27\Lib\pickle.py", line 419, in save_reduce
    save(state)
  File "c:\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "c:\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\Lib\multiprocessing\forking.py", line 66, in dispatcher
    self.save_reduce(obj=obj, *rv)
  File "c:\python27\Lib\pickle.py", line 401, in save_reduce
    save(args)
  File "c:\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\Lib\pickle.py", line 548, in save_tuple
    save(element)
  File "c:\python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\python27\Lib\pickle.py", line 419, in save_reduce
    save(state)
  File "c:\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "c:\python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\python27\Lib\pickle.py", line 419, in save_reduce
    save(state)
  File "c:\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "c:\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\python27\Lib\pickle.py", line 686, in _batch_setitems
    save(v)
  File "c:\python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\python27\Lib\pickle.py", line 419, in save_reduce
    save(state)
  File "c:\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "c:\python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\python27\Lib\pickle.py", line 419, in save_reduce
    save(state)
  File "c:\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\Lib\pickle.py", line 548, in save_tuple
    save(element)
  File "c:\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "c:\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\Lib\pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <built-in method recvfrom_into of _socket.socket object at 0x02D36F48>: it's not found as __main__.recvfrom_into
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python27\Lib\multiprocessing\forking.py", line 374, in main
    self = load(from_parent)
  File "c:\python27\Lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "c:\python27\Lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "c:\python27\Lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError

```

The same code works if I change async to False.  This is running on Python 2.7.3 on Windows against Kafka 0.8.0. Any suggestions gratefully received

**Comment by Veereshsajjan** [comment]
HI ,
I am using modified tail2kafka which is log2 kafka  when i run i get the below error
Traceback (most recent call last):
  File "log2kafka.py", line 46, in <module>
    main()
  File "log2kafka.py", line 40, in main
    producer = kafka.producer.Producer(options.topic,options.host,int(options.port))
  File "/home/nandhu/kafka/kafka-storm-cassandra-master/kafka/producer.py", line 29, in __init__
    self.connect()
  File "/home/nandhu/kafka/kafka-storm-cassandra-master/kafka/io.py", line 21, in connect
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: coercing to Unicode: need string or buffer, int found


my Producer is import atexit
import contextlib
import itertools
import struct
import threading

import kafka.io
import kafka.request_type


class Producer(kafka.io.IO):
  """Class for sending data to a `Kafka <http://sna-projects.com/kafka/>`_ broker.

    :param topic: The topic to produce to.
    :param partition: The broker partition to produce to.
    :param host: The kafka host.
    :param port: The kafka port.
    :param max_message_sz: The maximum allowed size of a produce request (in bytes). [default: 1MB]

  """

  PRODUCE_REQUEST_ID = kafka.request_type.PRODUCE

  def __init__(self, topic, partition=3, host='localhost', port=9092, max_message_sz=104):
    kafka.io.IO.__init__(self, host, port)
    self.max_message_sz = max_message_sz
    self.topic = topic
    self.partition = partition
    self.connect()

  def _pack_payload(self, messages):
    """Pack a list of messages into a sendable buffer.

      :param msgs: The packed messages to send.
      :param size: The size (in bytes) of all the `messages` to send.

    """
    payload = ''.join(messages)
    payload_sz = len(payload)
    topic_sz = len(self.topic)
    # Create the request as::
    #   <REQUEST_ID: short>
    #   <TOPIC_SIZE: short>
    #   <TOPIC: bytes>
    #   <PARTITION: int>
    #   <BUFFER_SIZE: int>
    #   <BUFFER: bytes>
    return struct.pack(
      '>HH%dsii%ds' % (topic_sz, payload_sz),
      self.PRODUCE_REQUEST_ID,
      topic_sz,
      self.topic,
      self.partition,
      payload_sz,
      payload
    )

  def _pack_kafka_message(self, payload):
    """Pack a payload in a format kafka expects."""
    return struct.pack('>i%ds' % len(payload), len(payload), payload)

  def encode_request(self, messages):
    """Encode a sequence of messages for sending to a kafka broker.

      Encoding a request can yeild multiple kafka messages if the payloads exceed
      the maximum produce size.

      :param messages: An iterable of :class:`Message <kafka.message>` objecjts.
      :rtype: A generator of packed kafka messages ready for sending.

    """
    encoded_msgs = []
    encoded_msgs_sz = 0
    for message in messages:
      encoded = message.encode()
      encoded_sz = len(encoded)
      if encoded_sz + encoded_msgs_sz > self.max_message_sz:
        yield self._pack_kafka_message(self._pack_payload(encoded_msgs))
        encoded_msgs = []
        encoded_msgs_sz = 0
      msg = struct.pack('>i%ds' % encoded_sz, encoded_sz, encoded)
      encoded_msgs.append(msg)
      encoded_msgs_sz += encoded_sz
    if encoded_msgs:
      yield self._pack_kafka_message(self._pack_payload(encoded_msgs))

  def send(self, messages):
    """Send a :class:`Message <kafka.message>` or a sequence of `Messages` to the Kafka server."""
    if isinstance(messages, kafka.message.Message):
      messages = [messages]
    for message in self.encode_request(messages):
      sent = self.write(message)
      if sent != len(message):
        raise IOError('Failed to send kafka message - sent %s/%s many bytes.' % (sent, len(message)))

  @contextlib.contextmanager
  def batch(self):
    """Send messages with an implict `send`."""
    messages = []
    yield(messages)
    self.send(messages)


class BatchProducer(Producer):
  """Class for batching messages to a `Kafka <http://sna-projects.com/kafka/>`_ broker with periodic flushing.

    :param topic: The topic to produce to.
    :param batch_interval: The amount of time (in seconds) to wait for messages before sending.
    :param partition: The broker partition to produce to.
    :param host: The kafka host.
    :param port: The kafka port.

  """

  MAX_RESPAWNS = 5
  PRODUCE_REQUEST_ID = kafka.request_type.PRODUCE

  def __init__(self, topic, batch_interval, partition=3, host='localhost', port=9092):
    Producer.__init__(self, topic, partition=partition, host=host, port=port)
    self.batch_interval = batch_interval
    self._message_queue = []
    self.event = threading.Event()
    self.lock = threading.Lock()
    self.timer = None
    atexit.register(self.close)
    self.respawns = 0

  def check_timer(self):
    """Starts the flush timer and restarts it after forks."""
    if (self.timer and self.timer.is_alive()) or self.respawns > self.MAX_RESPAWNS:
      return
    self.respawns += 1
    self.timer = threading.Thread(target=self._interval_timer)
    self.timer.daemon = True
    self.timer.start()
    self.connect()

  def _interval_timer(self):
    """Flush the message queue every `batch_interval` seconds."""
    while not self.event.is_set():
      self.flush()
      self.event.wait(self.batch_interval)

  def enqueue(self, message):
    """Enqueue a message in the queue.

      .. note:: These messages are implicitly sent every `batch_interval` seconds.

      :param message: The message to queue for sending at next send interval.

    """
    with self.lock:
      self.check_timer()
      self._message_queue.append(message)

  def flush(self):
    """Send all messages in the queue now."""
    with self.lock:
      if len(self._message_queue) > 0:
        self.send(self._message_queue)
        # Reset the queue
        del self._message_queue[:]

  def close(self):
    """Shutdown the timer thread and flush the message queue."""
    self.event.set()
    self.flush()
    if self.timer:
      self.timer.join()
