### ISSUE TITLE
KeyError exception in kafka.KafkaConsumer

### ISSUE THREAD

**Issue by CVTJNII** [dpkp/kafka-python#498]
While running a custom test program against Kafka 0.9.0.0 and Kafka Python 0.9 branch commit 9a8af14 using kafka.KafkaConsumer I'm seeing consumers die with a key error:

```
2016-01-09 05:32:14,378 cw17: Auto offset commit failed: UnknownMemberIdError - 25 - Returned from group requests (offset commits/fetches, heartbeats, etc) when the memberId is not in the current generation.
2016-01-09 05:32:14,458 cw17: OffsetCommit failed for group pytester due to group error (UnknownMemberIdError - 25 - Returned from group requests (offset commits/fetches, heartbeats, etc) when the memberId is not in the current generation.), will rejoin
2016-01-09 05:32:14,459 cw17: Offset commit failed: group membership out of date This is likely to cause duplicate message delivery.
Process Process-38:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/tester.py", line 183, in consumer_worker
    for message in consumer:
  File "/usr/lib/python2.7/dist-packages/six.py", line 530, in next
    return type(self).__next__(self)
  File "build/bdist.linux-x86_64/egg/kafka/consumer/group.py", line 654, in __next__
    return next(self._iterator)
  File "build/bdist.linux-x86_64/egg/kafka/consumer/group.py", line 636, in _message_generator
    for msg in self._fetcher:
  File "/usr/lib/python2.7/dist-packages/six.py", line 530, in next
    return type(self).__next__(self)
  File "build/bdist.linux-x86_64/egg/kafka/consumer/fetcher.py", line 387, in __next__
    return next(self._iterator)
  File "build/bdist.linux-x86_64/egg/kafka/consumer/fetcher.py", line 367, in _message_generator
    self._subscriptions.assignment[tp].consumed = msg.offset + 1
KeyError: TopicPartition(topic=u'test', partition=7)
```

The above happened after approximately 10 minutes of run time, this seems to happen when the 300 second timer from #497 fires.  I have seen it multiple times but not every time the timer fires.  Log level is only warning as I'm running many processes in the same terminal, I will need to set up per-process logging to get a debug level log.  Let me know if that is needed.  Thanks.

**Comment by dpkp** [comment]
That shouldn't happen - will investigate. Thanks!

**Comment by dpkp** [comment]
This is caused by an assignment change during iteration. PR #503 should fix.
