### ISSUE TITLE
Help: trouble with kafka 0.8.0

### ISSUE THREAD

**Issue by mortenlj** [dpkp/kafka-python#510]
I'm using kafka-python 0.9.5, on Python 2.7.9, with kafka 0.8.0. According to the documentation this should work, but I get the following error when trying to create a consumer:

```
>>> from kafka import KafkaConsumer
>>> consumer = KafkaConsumer("my-topic", group_id="my_group", bootstrap_servers=["kafka.internal:7794"])
No handlers could be found for logger "kafka.conn"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fimojoha/.virtualenvs/fiaas-deploy-daemon/lib/python2.7/site-packages/kafka/consumer/kafka.py", line 60, in __init__
    self.set_topic_partitions(*topics)
  File "/home/fimojoha/.virtualenvs/fiaas-deploy-daemon/lib/python2.7/site-packages/kafka/consumer/kafka.py", line 243, in set_topic_partitions
    self._get_commit_offsets()
  File "/home/fimojoha/.virtualenvs/fiaas-deploy-daemon/lib/python2.7/site-packages/kafka/consumer/kafka.py", line 623, in _get_commit_offsets
    check_error(resp)
  File "/home/fimojoha/.virtualenvs/fiaas-deploy-daemon/lib/python2.7/site-packages/kafka/common.py", line 252, in check_error
    raise response
kafka.common.FailedPayloadsError
```

At the same time, this error shows up in kafkas server.log:

```
[2016-01-18 10:56:20,163] ERROR Closing socket for /80.91.33.141 because of error (kafka.network.Processor)
kafka.common.KafkaException: Wrong request type 9
	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:49)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:49)
	at kafka.network.Processor.read(SocketServer.scala:346)
	at kafka.network.Processor.run(SocketServer.scala:246)
	at java.lang.Thread.run(Thread.java:745)
```

Am I doing something wrong?

**Comment by dpkp** [comment]
You'll need to disable auto-commit when creating your consumer. We've added
an automatic version check in the latest code, but it isn't released yet
(soon!).

**Comment by mortenlj** [comment]
Like this?

```
>>> consumer = KafkaConsumer("my-topic", group_id="my-group", bootstrap_servers=["kafka.internal:7794"], auto_commit_enable=False)
No handlers could be found for logger "kafka.conn"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fimojoha/.virtualenvs/fiaas-deploy-daemon/lib/python2.7/site-packages/kafka/consumer/kafka.py", line 60, in __init__
    self.set_topic_partitions(*topics)
  File "/home/fimojoha/.virtualenvs/fiaas-deploy-daemon/lib/python2.7/site-packages/kafka/consumer/kafka.py", line 243, in set_topic_partitions
    self._get_commit_offsets()
  File "/home/fimojoha/.virtualenvs/fiaas-deploy-daemon/lib/python2.7/site-packages/kafka/consumer/kafka.py", line 623, in _get_commit_offsets
    check_error(resp)
  File "/home/fimojoha/.virtualenvs/fiaas-deploy-daemon/lib/python2.7/site-packages/kafka/common.py", line 252, in check_error
    raise response
kafka.common.FailedPayloadsError
```

Same error...

**Comment by dpkp** [comment]
You also can't set a group_id. Kafka 0.8.0 does not support offset commit
tracking at all.

-Dana

**Comment by mortenlj** [comment]
Thanks, that seems to solve the problem. Some errors or warnings about unsupported parameters for the version of kafka you are using would probably be useful... especially after auto-detection is in place.
