### ISSUE TITLE
kafka-python does not work on Windows

### ISSUE THREAD

**Issue by Pehat** [dpkp/kafka-python#520]
OS: Windows 8
kafka-python version: 0.97.0-dev

Trying to run:
```
producer = KafkaProducer(bootstrap_servers=[KAFKA_ADDRESS])
```
Getting an error:
```
2016-01-26 18:10:08,252 kafka.producer.kafka DEBUG    Starting the Kafka producer
2016-01-26 18:10:08,252 kafka.client DEBUG    Attempting to bootstrap via node at 10.250.181.19:9092
2016-01-26 18:10:08,253 kafka.conn   ERROR    Connect attempt to <BrokerConnection host=10.250.181.19 port=9092> returned error 10035. Disconnecting.
2016-01-26 18:10:08,253 kafka.client ERROR    Unable to bootstrap from [('10.250.181.19', 9092)]
2016-01-26 18:10:08,253 kafka.client DEBUG    No connected nodes found. Trying disconnected nodes.
2016-01-26 18:10:08,253 kafka.client DEBUG    No luck. Trying all broker metadata
2016-01-26 18:10:08,253 kafka.client ERROR    No nodes found in metadata -- retrying bootstrap
2016-01-26 18:10:08,254 kafka.client DEBUG    Sleeping 0.0980 before bootstrapping again
2016-01-26 18:10:08,352 kafka.client DEBUG    Attempting to bootstrap via node at 10.250.181.19:9092
2016-01-26 18:10:08,352 kafka.conn   ERROR    Connect attempt to <BrokerConnection host=10.250.181.19 port=9092> returned error 10035. Disconnecting.
2016-01-26 18:10:08,352 kafka.client ERROR    Unable to bootstrap from [('10.250.181.19', 9092)]
Traceback (most recent call last):
  File "sample.py", line 5, in <module>
   producer = KafkaProducer(bootstrap_servers=[KAFKA_ADDRESS])
  File "C:\Program Files\Python35\lib\site-packages\kafka_python-0.97.0.dev0-py3.5.egg\kafka\producer\kafka.py", line 245, in __init__
  File "C:\Program Files\Python35\lib\site-packages\kafka_python-0.97.0.dev0-py3.5.egg\kafka\client_async.py", line 607, in check_version
  File "C:\Program Files\Python35\lib\site-packages\kafka_python-0.97.0.dev0-py3.5.egg\kafka\client_async.py", line 575, in connect
kafka.common.NodeNotReadyError: None
```
Found this code in the `conn.py`:
```
self._sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self._sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF,
                                  self.config['receive_buffer_bytes'])
            self._sock.setsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF,
                                  self.config['send_buffer_bytes'])
            self._sock.setblocking(False)
            ret = self._sock.connect_ex((self.host, self.port))
            self.last_attempt = time.time()

            if not ret or ret is errno.EISCONN:
                self.state = ConnectionStates.CONNECTED
            elif ret in (errno.EINPROGRESS, errno.EALREADY):
                self.state = ConnectionStates.CONNECTING
            else:
                log.error('Connect attempt to %s returned error %s.'
                          ' Disconnecting.', self, ret)
                self.close()
                self.last_failure = time.time()
```
On my machine, `ret` contains `EWOULDBLOCK`, and [this seems to be normal](http://tangentsoft.net/wskfaq/newbie.html#wouldblock). Do you need to handle `EWOULDBLOCK` in this case or my machine is merely glitchy and should not return `EWOULDBLOCK` on socket opening?

**Comment by dpkp** [comment]
Thanks for the issue report! I haven't found a windows env for automated testing (using Travis now) and don't have a windows box myself.

Do you mind running the whole test suite and letting me know if there are any other failures?

**Comment by Pehat** [comment]
Sorry, `tox` fails to install all the requirements into the Python 3.5 environment. Moreover, your integration script uses binary packages for Kafka and Zookeeper, that, I suppose, are intended to run under some Unix environment. I connect to CentOS on my virtual machine, so maybe I should use install binary packages on it?

**Comment by dpkp** [comment]
Integration only uses jar archives for Kafka and zookeeper. I would expect
them to run on any platform w java 7?

**Comment by Pehat** [comment]
I would expect `build_integration.sh` not to run on Windows. I have no `wget` on Windows. Maybe there is another way?

**Comment by dpkp** [comment]
Ah ok. I'll find a windows compatible way to do that. Thanks!

**Comment by Nof888** [comment]
I'm using version 1.0.1 and having the same issue - is there any workaround or fix?

**Comment by Pehat** [comment]
@Nof888 I use rather clumsy workaround - a virtual Linux machine on my Win8 host.

**Comment by fcfangcc** [comment]
I'm using version 1.0.1,i have the same issue in windows7.

**Comment by dpkp** [comment]
Re-posting comments from additional logs in #586:

The logs show an unrecognized socket errno (returned error 10035). Fixing this will require modifying the kafka/conn.py socket code and possibly also kafka/client_async.py select calls. Unfortunately I do not have a windows machine to test on, so I cannot help here. But PRs welcome!

also, some helpful links:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx
http://itamarst.org/writings/win32sockets.html

**Comment by dpkp** [comment]
We might be able to do automated win testing via http://www.appveyor.com/

**Comment by dpkp** [comment]
Should be fixed on master. Please reopen if not!

**Comment by szmcdull** [comment]
if I construct the producer with bootstrap_servers='host:port', it fails. If I parse bootstrap_servers='host', it works. Tested master in both windows and linux, same result.

**Comment by N0ciple** [comment]
Same thing for me, I had to remove the port !

**Comment by dpkp** [comment]
Please open a new issue w/ specific code to reproduce. thanks!
