### ISSUE TITLE
Consumer timeout is not handled apropriately

### ISSUE THREAD

**Issue by Pehat** [dpkp/kafka-python#526]
Hi,
I've got two consumers on a single partition of the same topic. Obviously, when everything is OK, the first consumer gets all the messages and the second is idle. But my first consumer is glitchy and fails after 10 seconds after start. So that the second one waits for `metadata_max_age_ms` milliseconds and then asks `GroupCoordinator` to get some partitions if any. At this point I've got marvelous error:
```
2016-01-29 10:56:03,630 kafka.conn   DEBUG    <BrokerConnection host=10.20.30.40 port=9092> Response 7: MetadataResponse(brokers=[(node_id=0, host='10.20.30.40', port=9092)], topics=[(error_code=0, topic='TestTopic', partitions=[(error_code=0, partition=0, leader=0, replicas=[0], isr=[0])])])
2016-01-29 10:56:03,630 kafka.cluster DEBUG    Updated cluster metadata version 3 to Cluster(brokers: 1, topics: 1, groups: 1)
2016-01-29 10:56:03,630 kafka.consumer.group DEBUG    No partitions assigned; sleeping for -299.999883890152
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    for message in consumer:
  File "/home/renat/searchenv/lib/python3.4/site-packages/kafka_python-0.97.0.dev0-py3.4.egg/kafka/consumer/group.py", line 684, in __next__
  File "/home/renat/searchenv/lib/python3.4/site-packages/kafka_python-0.97.0.dev0-py3.4.egg/kafka/consumer/group.py", line 648, in _message_generator
ValueError: sleep length must be non-negative

```
So I go to the source file and see:
```
while time.time() < self._consumer_timeout:
           ...
            timeout_at = min(self._consumer_timeout,
                             self._client._delayed_tasks.next_at() + time.time(),
                             self._client.cluster.ttl() / 1000.0 + time.time())

            if self.config['api_version'] >= (0, 9):
                if self.config['group_id'] is not None and not self.assignment():
                    sleep_time = time.time() - timeout_at
                    log.debug('No partitions assigned; sleeping for %s', sleep_time)
                    time.sleep(sleep_time)
                    continue
```
(By the way, when you call `time.time()` several times, results may vary. However, that's not the case — value `-300` is way too big)
I've added some debug output and got that:
```
...
2016-01-29 11:24:50,707 kafka.consumer.group DEBUG    Consumer timeout: inf
2016-01-29 11:24:50,707 kafka.consumer.group DEBUG    Next task at: 0
2016-01-29 11:24:50,707 kafka.consumer.group DEBUG    Cluster TTL: 0.16259765625
2016-01-29 11:24:50,707 kafka.consumer.group DEBUG    No partitions assigned; sleeping for 5.0067901611328125e-06
2016-01-29 11:24:50,707 kafka.client DEBUG    Sending metadata request MetadataRequest(topics=['TestTopic']) to node 0
2016-01-29 11:24:50,708 kafka.conn   DEBUG    <BrokerConnection host=10.20.30.40 port=9092> Request 7: MetadataRequest(topics=['TestTopic'])
2016-01-29 11:24:50,708 kafka.coordinator DEBUG    Skipping heartbeat: no auto-assignment or waiting on rebalance
2016-01-29 11:24:50,708 kafka.conn   DEBUG    <BrokerConnection host=10.20.30.40 port=9092> Response 7: MetadataResponse(brokers=[(node_id=0, host='10.20.30.40', port=9092)], topics=[(error_code=0, topic='TestTopic', partitions=[(error_code=0, partition=0, leader=0, replicas=[0], isr=[0])])])
2016-01-29 11:24:50,708 kafka.cluster DEBUG    Updated cluster metadata version 3 to Cluster(brokers: 1, topics: 1, groups: 1)
2016-01-29 11:24:50,708 kafka.consumer.group DEBUG    Consumer timeout: inf
2016-01-29 11:24:50,708 kafka.consumer.group DEBUG    Next task at: 9999999999
2016-01-29 11:24:50,708 kafka.consumer.group DEBUG    Cluster TTL: 299999.8330078125
2016-01-29 11:24:50,709 kafka.consumer.group DEBUG    No partitions assigned; sleeping for -299.9997878074646
...
```
Any ideas how can I fix this?

**Comment by dpkp** [comment]
Excellent bug report, thank you! Will investigate.
