### ISSUE TITLE
I'm getting an ImportError: cannot import name has_lz4

### ISSUE THREAD

**Issue by johnjullies** [dpkp/kafka-python#554]
```
Traceback (most recent call last):
  File "mychat/app.py", line 29, in <module>
    from kafka import KafkaConsumer
  File "/home/ayannah/.local/lib/python2.7/site-packages/kafka/__init__.py", line 7, in <module>
    from kafka.client import KafkaClient
  File "/home/ayannah/.local/lib/python2.7/site-packages/kafka/client.py", line 16, in <module>
    from kafka.protocol import KafkaProtocol
  File "/home/ayannah/.local/lib/python2.7/site-packages/kafka/protocol/__init__.py", line 1, in <module>
    from .legacy import (
  File "/home/ayannah/.local/lib/python2.7/site-packages/kafka/protocol/legacy.py", line 12, in <module>
    import kafka.protocol.fetch
  File "/home/ayannah/.local/lib/python2.7/site-packages/kafka/protocol/fetch.py", line 1, in <module>
    from .message import MessageSet
  File "/home/ayannah/.local/lib/python2.7/site-packages/kafka/protocol/message.py", line 3, in <module>
    from ..codec import (has_gzip, has_snappy, has_lz4,
ImportError: cannot import name has_lz4
```

**Comment by dpkp** [comment]
Looks like you have a broken install. The `kafka/__init__.py` and `kafka/client.py` lines are from v0.9.5, but the rest of the stacktrace is from 1.0.0. I recommend deleting your current install:
`rm -rf /home/ayannah/.local/lib/python2.7/site-packages/kafka/` and reinstalling
