### ISSUE TITLE
Disabling batching (batch_size = 0) does not work

### ISSUE THREAD

**Issue by shichao-an** [dpkp/kafka-python#556]
I'm using the v1.0.0 release. If I set `batch_size = 0` to `KafkaProducer` (to disable batching, as the documentation suggests), then I will get this error:

```
Traceback (most recent call last):
  File "kafka-producer.py", line 66, in <module>
    io_loop.run_sync(main)
  File "/home/shichao/env/local/lib/python2.7/site-packages/tornado/ioloop.py", line 453, in run_sync
    return future_cell[0].result()
  File "/home/shichao/env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/shichao/env/local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "kafka-producer.py", line 49, in main
    producer = KafkaProducerClient(**PRODUCER_CONFIGS)
  File "kafka-producer.py", line 39, in __init__
    self.producer = AsyncKafkaProducer(**configs)
  File "/home/shichao/env/local/lib/python2.7/site-packages/kafka/producer/kafka.py", line 256, in __init__
    self._accumulator = RecordAccumulator(**self.config)
  File "/home/shichao/env/local/lib/python2.7/site-packages/kafka/producer/record_accumulator.py", line 152, in __init__
    self.config['batch_size'])
  File "/home/shichao/env/local/lib/python2.7/site-packages/kafka/producer/buffer.py", line 124, in __init__
    buffers = int(memory / poolable_size)
ZeroDivisionError: integer division or modulo by zero
```

I also noticed [this assertion](https://github.com/dpkp/kafka-python/blob/0d5899020a75e22fec14d3e3d7aec8f043d60a31/kafka/producer/buffer.py#L33) which blocks  setting `batch_size` to zero.

**Comment by dpkp** [comment]
fixed in master
