### ISSUE TITLE
kafka-python not compatible with Cloudera's Kafka 0.8.2.0? 

### ISSUE THREAD

**Issue by movermeyer** [dpkp/kafka-python#562]
I'm trying to use kafka-python 1.0.1 to talk to a 0.8.2.0 broker ([Clodera's KAFKA-0.8.2.0-1.kafka1.4.0.p0.56](https://www.cloudera.com/documentation/kafka/1-4-x/topics/kafka_packaging.html), technically).

According to the [Compatibility page](https://kafka-python.readthedocs.org/en/master/compatibility.html), this should be fine.

Here is my code:

```
from kafka import KafkaConsumer
consumer = KafkaConsumer("my_topic", bootstrap_servers="mykafkabroker.example.com:9092")
```
However, I always get:

```
Traceback (most recent call last):
  File "sample.py", line 2, in <module>
    consumer = KafkaConsumer("vtevi_store", bootstrap_servers="mykafkabroker.example.com:9092")
  File "/my_example_project/env/lib/python2.7/site-packages/kafka/consumer/group.py", line 186, in __init__
    self.config['api_version'] = self._client.check_version()
  File "/my_example_project/env/lib/python2.7/site-packages/kafka/client_async.py", line 634, in check_version
    connect(node_id)
  File "/my_example_project/env/lib/python2.7/site-packages/kafka/client_async.py", line 597, in connect
    raise Errors.NodeNotReadyError(node_id)
kafka.common.NodeNotReadyError: 111
```
 
Looking at the code, I see this comment:

```
# brokers < 0.9 do not return any broker metadata if there are no topics
# so we're left with a single bootstrap connection
```

But there are many topics in the broker when I use 
```kafka-topics --zookeeper myzk.example.com --list```
and I have been using these topics with kafka-python 0.9.5.

I'm not sure what my next steps in debugging this should be. 

* Would you expect that using kafka-python 1.0.1 would work with this broker?
* What was the issue that [prevents 0.8.2-beta](https://kafka-python.readthedocs.org/en/master/compatibility.html) from working? Perhaps Cloudera didn't fix this in their fork. Is there a way to test this?

--------------------------------

Client details:
* kafka-python 1.0.1
* CentOS 7
* Python 2.7.5

Broker details:
* Cloudera's KAFKA-0.8.2.0-1.kafka1.4.0.p0.56 (Kafka 0.8.2.0)
* CentOS 2.6
* Java 1.8

**Comment by movermeyer** [comment]
Sorry, it seems I have some other issue with my broker configuration is confounding me. It's not kafka-python that is the problem.
