### ISSUE TITLE
kafka.common.ConnectionError on big messages + gevent

### ISSUE THREAD

**Issue by dribler** [dpkp/kafka-python#610]
i'm getting kafka.common.ConnectionError trying to send big message. Code below

```python
from gevent.monkey import patch_all; patch_all()
from kafka import KafkaProducer

producer = KafkaProducer(bootstrap_servers=xxxxxxxx,
                         buffer_memory=10 * 1024 * 1024,
                         max_request_size=10 * 1024 * 1024,)

producer.send('test', 'a' * 1024 * 1024 * 3, ).get(timeout=60)
producer.flush()
```

causing this

```
2016-03-23 11:50:58,147 - kafka.conn - ERROR - Error sending ProduceRequest(required_acks=1, timeout=30000, topics=[(topic='test2', partitions=[(1, <_io.BytesIO object at 0x7fe64edc2950>)])]) to <BrokerConnection host=127.0.0.1 port=9093>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kafka/conn.py", line 187, in send
    assert sent_bytes == len(message)
AssertionError
2016-03-23 11:50:58,150 - kafka.producer.sender - DEBUG - Error sending produce request to node 2: 
2016-03-23 11:50:58,150 - kafka.producer.record_accumulator - DEBUG - Produced messages to topic-partition TopicPartition(topic='test2', partition=1) with base offset -1 and error .
2016-03-23 11:50:58,150 - kafka.client - DEBUG - Initializing connection to node 2 for metadata request
Traceback (most recent call last):
  File "test_producer.py", line 15, in <module>
    producer.send('test2', 'a' * 1024 * 1024 * 3, ).get(timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/kafka/producer/future.py", line 50, in get
    raise self.exception # pylint: disable-msg=raising-bad-type
kafka.common.ConnectionError

```
this works well if i comment out **patch_all()** line

Fixing kafka.conn.BrokerConnection.send() method solved it, but i'm not sure about side effects.

```python
def send()
.....
.....
        size = Int32.encode(len(message))
        try:
            self._sock.setblocking(True)
            sent_bytes = self._sock.send(size)
            assert sent_bytes == len(size)
            total_sent = 0
            while total_sent < len(message):  # sending in loop
                sent_bytes = self._sock.send(message[total_sent:])
                assert sent_bytes
                total_sent += sent_bytes
            self._sock.setblocking(False)
        except (AssertionError, ConnectionError) as e:
            log.exception("Error sending %s to %s", request, self)
....
```
Any chances to have similar fix in master branch?

**Comment by dpkp** [comment]
I'm fine with that change. The send code isn't optimal as it is (it blocks, unlike recv). As an aside - how are you using kafka-python w/ gevent?

**Comment by dribler** [comment]
Great, thanks!

We are implementing some new features in our web application. Web app is kafka producer there. It's already uses gevent, so we have to run kafka-python in gevent-patched environment.
