### ISSUE TITLE
help: filedescriptor out of range in select

### ISSUE THREAD

**Issue by abc100m** [dpkp/kafka-python#622]
we got an exception "ValueError: filedescriptor out of range in select()"  which cause a lot of Logs.
```shell
[localhost log]$ ll -h
total 72G
-rw-rw-r-- 1 user user 72G Apr  2 10:53 thelog.log.2016-04-02
```

we use kafka-python-1.0.2.  bellow is the detail messae:

```shell
[2016-04-02 01:25:13,466] [ERROR] [kafka-python-producer-1-network-thread] Uncaught error in kafka producer I/O thread
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/kafka/producer/sender.py", line 56, in run
    self.run_once()
  File "build/bdist.linux-x86_64/egg/kafka/producer/sender.py", line 146, in run_once
    self._client.poll(poll_timeout_ms, sleep=True)
  File "build/bdist.linux-x86_64/egg/kafka/client_async.py", line 367, in poll
    responses.extend(self._poll(timeout, sleep=sleep))
  File "build/bdist.linux-x86_64/egg/kafka/client_async.py", line 386, in _poll
    select.select([self._wake_r], sockets, [], timeout)
ValueError: filedescriptor out of range in select()

[2016-04-02 01:25:13,516] [ERROR] [kafka-python-producer-1-network-thread] Uncaught error in kafka producer I/O thread
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/kafka/producer/sender.py", line 56, in run
    self.run_once()
  File "build/bdist.linux-x86_64/egg/kafka/producer/sender.py", line 146, in run_once
    self._client.poll(poll_timeout_ms, sleep=True)
  File "build/bdist.linux-x86_64/egg/kafka/client_async.py", line 367, in poll
    responses.extend(self._poll(timeout, sleep=sleep))
  File "build/bdist.linux-x86_64/egg/kafka/client_async.py", line 402, in _poll
    ready, _, _ = select.select(fds, [], [], timeout)
ValueError: filedescriptor out of range in select()

[2016-04-02 01:25:13,517] [ERROR] [kafka-python-producer-1-network-thread] Uncaught error in kafka producer I/O thread
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/kafka/producer/sender.py", line 56, in run
    self.run_once()
  File "build/bdist.linux-x86_64/egg/kafka/producer/sender.py", line 146, in run_once
    self._client.poll(poll_timeout_ms, sleep=True)
  File "build/bdist.linux-x86_64/egg/kafka/client_async.py", line 367, in poll
    responses.extend(self._poll(timeout, sleep=sleep))
  File "build/bdist.linux-x86_64/egg/kafka/client_async.py", line 402, in _poll
    ready, _, _ = select.select(fds, [], [], timeout)
ValueError: filedescriptor out of range in select()

.... (a lot of message)
```

**Comment by dpkp** [comment]
closing as duplicate. see #613
