### ISSUE TITLE
Frequently raise FailedPayloadsError 

### ISSUE THREAD

**Issue by kittdotech** [dpkp/kafka-python#758]
File "/root/scrapycluster/pycluster/local/lib/python2.7/site-packages/kafka/conn.py", line 103, in _read_bytes
    raise socket.error("Not enough data to read message -- did server kill socket?")
error: Not enough data to read message -- did server kill socket?
2016-07-14 15:36:00 [kafka.conn] DEBUG: Closing socket connection for x.x.x.x:9092
2016-07-14 15:36:00 [kafka.client] WARNING: ConnectionError attempting to receive a response to request 12 from server BrokerMetadata(nodeId=0, host='x.x.x.x', port=9092): Kafka @ x.x.x.x:9092 went away
2016-07-14 15:36:00 [kafka.producer] ERROR: Unable to send messages
Traceback (most recent call last):
  File "/root/scrapycluster/pycluster/local/lib/python2.7/site-packages/kafka/producer/base.py", line 411, in _send_messages
    fail_on_error=self.sync_fail_on_error
  File "/root/scrapycluster/pycluster/local/lib/python2.7/site-packages/kafka/client.py", line 614, in send_produce_request
    (not fail_on_error or not self._raise_on_response_error(resp))]
  File "/root/scrapycluster/pycluster/local/lib/python2.7/site-packages/kafka/client.py", line 374, in _raise_on_response_error
    raise resp
FailedPayloadsError

**Comment by dpkp** [comment]
(1) please upgrade to KafkaProducer. SimpleProducer is deprecated and not actively maintained.

(2) These are network errors. Have you checked your server logs? How reliable is your network?

**Comment by kittdotech** [comment]
Thanks. I am using scrapy cluster. Also using 4 host(Linode) with stable network connectivity.
