### ISSUE TITLE
Help: kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1

### ISSUE THREAD

**Issue by fillest** [dpkp/kafka-python#784]
Hello.
Yesterday I got my kafka broker killed by OOM killer and after its start I'm seeing series of strange errors in the log:
```
[2016-07-31 23:50:47,402] INFO [Kafka Server 0], started (kafka.server.KafkaServer)
[2016-07-31 23:50:48,022] ERROR [KafkaApi-0] Error when handling request {group_id=kafka-python-default-group} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
        at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
        at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
        at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
        at kafka.server.KafkaApis.kafka$server$KafkaApis$$createGroupMetadataTopic(KafkaApis.scala:651)
        at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
        at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
        at scala.Option.getOrElse(Option.scala:121)
        at kafka.server.KafkaApis.getOrCreateGroupMetadataTopic(KafkaApis.scala:657)
        at kafka.server.KafkaApis.handleGroupCoordinatorRequest(KafkaApis.scala:818)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:86)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
        at java.lang.Thread.run(Thread.java:745)
```
"group_id=kafka-python-default-group" looks like a strong indication that the request came from python client. Why could this possibly happen at all and why does it use replication factor 3?
I'm using kafka-python==1.2.1, a single kafka 0.10 broker with replication factor 1 with a single local producer and a single remote (different host) consumer. Automatic topic creation is disabled on the broker. All topics were created in advance during a deploy long ago.

**Comment by brynmathias** [comment]
This often happens to me when the kafka server has the wrong broker number in zookeeper, which can happen when kafka doesn't shut down gracefully and the kafka instance that you bring back up has a broker number that already exists.

I think I have fixed it before with:
shut down kafka broker.
Shut down zookeeper,
Start zookeeperm
Start kafka.

**Comment by alexeybaj** [comment]
Value of 3 is hardcoded in OffsetManager.scala 
```
val DefaultOffsetsTopicReplicationFactor = 3.toShort
```
and is applied during special offsets topic creation *if* number of alive brokers is zero.

**Comment by dpkp** [comment]
This is definitely a broker configuration issue, unrelated to kafka-python. The topic that is failing to create is `__consumer_offsets` . Try setting `offsets.topic.replication.factor` to 1 on your single broker.
