### ISSUE TITLE
Help: not able to connect to server

### ISSUE THREAD

**Issue by parag4code** [dpkp/kafka-python#789]
`Traceback (most recent call last):
  File "producer.py", line 3, in <module>
    client=KafkaClient('localhost:9000')
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/__init__.py", line 41, in __init__
    super(KafkaClient, self).__init__(*args, **kwargs)
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/client.py", line 53, in __init__
    self.load_metadata_for_topics()  # bootstrap with all metadata
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/client.py", line 523, in load_metadata_for_topics
    resp = self.send_metadata_request(topics)
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/client.py", line 588, in send_metadata_request
    return self._send_broker_unaware_request(payloads, encoder, decoder)
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/client.py", line 182, in _send_broker_unaware_request
    raise KafkaUnavailableError('All servers failed to process request: %s' % hosts)
kafka.errors.KafkaUnavailableError: All servers failed to process request: [('localhost', 9000, 0)]
`

Can someone help?

**Comment by dpkp** [comment]
It looks like you are using the old SimpleProducer. That interface is deprecated. Have you tried KafkaProducer?

**Comment by parag4code** [comment]
Yes i did try, but with no luck

**Comment by parag4code** [comment]
Here is the simple code

`from kafka import KafkaProducer, KafkaClient

client=KafkaClient('localhost:9000')
producer=KafkaProducer(client)`

**Comment by dpkp** [comment]
The interface changed between SimpleProducer and KafkaProducer (you are trying to use the SimpleProducer interface w/ KafkaProducer class...). Try this:

```
producer = KafkaProducer(bootstrap_servers='localhost:9000')
```

**Comment by parag4code** [comment]
Thanks for pointing that out, however I end up with this now
`Traceback (most recent call last):
  File "producer.py", line 4, in <module>
    producer=KafkaProducer(bootstrap_servers='localhost:9000')
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/producer/kafka.py", line 281, in __init__
    self.config['api_version'] = client.check_version(timeout=(self.config['api_version_auto_timeout_ms']/1000))
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/client_async.py", line 701, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable`

**Comment by dpkp** [comment]
is there a broker actually running on localhost:9000 ? you might check with `netstat -lntp | grep 9000`

**Comment by parag4code** [comment]
No.This is my first time with kafka. Only thing i have done so far is 
`pip install kafka-python`
and this small startup code .
Could you point out what I should be going here?

**Comment by dpkp** [comment]
kafka-python is just a client. You will need a cluster running somewhere to connect to.

**Comment by parag4code** [comment]
Thanks, i'll look into it!
