### ISSUE TITLE
Producer unable to recover during leader shutdown

### ISSUE THREAD

**Issue by ottomata** [dpkp/kafka-python#801]
I'm using kafka-python 1.3.0.  I'm testing producer behavior when I stop a broker that is a leader for the partition I'm producing to.  Under low volume, things usually work fine.  Under higher volume, > 80 messages / sec, I see exceptions and an eventual failure of the producer.

```
2016-08-09 16:14:20,732 [18797] (eventlogging-3d1e80f0-5e4c-11e6-83d5-fa163e2d5256-deployment-eventlogging04.deployment-prep.eqiad.wmflabs.18797-network-thread) <BrokerConnection host=deployment-kafka04.deployment-prep.eqiad.wmflabs/10.68.17.9 port=9092>: creating new socket
2016-08-09 16:14:20,732 [18797] (eventlogging-3d1e80f0-5e4c-11e6-83d5-fa163e2d5256-deployment-eventlogging04.deployment-prep.eqiad.wmflabs.18797-network-thread) Node 4 not ready; delaying produce of accumulated batch

...
2016-08-09 16:14:20,803 [18797] (eventlogging-3d1e80f0-5e4c-11e6-83d5-fa163e2d5256-deployment-eventlogging04.deployment-prep.eqiad.wmflabs.18797-network-thread) <BrokerConnection host=deployment-kafka05.deployment-prep.eqiad.wmflabs/deployment-kafka05.deployment-prep.eqiad.wmflabs port=9092>: creating new socket
2016-08-09 16:14:20,803 [18797] (eventlogging-3d1e80f0-5e4c-11e6-83d5-fa163e2d5256-deployment-eventlogging04.deployment-prep.eqiad.wmflabs.18797-network-thread) <BrokerConnection host=deployment-kafka05.deployment-prep.eqiad.wmflabs/10.68.21.106 port=9092>: established TCP connection
2016-08-09 16:14:20,804 [18797] (eventlogging-3d1e80f0-5e4c-11e6-83d5-fa163e2d5256-deployment-eventlogging04.deployment-prep.eqiad.wmflabs.18797-network-thread) Node bootstrap connected
2016-08-09 16:14:20,804 [18797] (eventlogging-3d1e80f0-5e4c-11e6-83d5-fa163e2d5256-deployment-eventlogging04.deployment-prep.eqiad.wmflabs.18797-network-thread) Uncaught error in kafka producer I/O thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kafka/producer/sender.py", line 60, in run
    self.run_once()
  File "/usr/lib/python2.7/dist-packages/kafka/producer/sender.py", line 159, in run_once
    self._client.poll(poll_timeout_ms, sleep=True)
  File "/usr/lib/python2.7/dist-packages/kafka/client_async.py", line 486, in poll
    metadata_timeout_ms = self._maybe_refresh_metadata()
  File "/usr/lib/python2.7/dist-packages/kafka/client_async.py", line 694, in _maybe_refresh_metadata
    node_id = self.least_loaded_node()
  File "/usr/lib/python2.7/dist-packages/kafka/client_async.py", line 646, in least_loaded_node
    self._bootstrap(collect_hosts(self.config['bootstrap_servers']))
  File "/usr/lib/python2.7/dist-packages/kafka/client_async.py", line 233, in _bootstrap
    future = bootstrap.send(metadata_request)
  File "/usr/lib/python2.7/dist-packages/kafka/conn.py", line 512, in send
    return self._send(request, expect_response=expect_response)
  File "/usr/lib/python2.7/dist-packages/kafka/conn.py", line 534, in _send
    self._sensors.bytes_sent.record(total_sent)
AttributeError: 'BrokerConnectionMetrics' object has no attribute 'bytes_sent'
...
```

This repeats many times, with what looks like to me too many attempts to try to reconnect to the stopped broker.  Perhaps the bootstrap_servers list should be randomly selected from?

Eventually, I see:

```
2016-08-09 16:14:22,737 [18797] (MainThread) Failed processing event: Failed sending event <Event 12345678-1234-5678-1234-567812345678 of schema (u'test_event', 1)>. KafkaTimeoutError: Timeout after waiting for 2.0 secs.
2016-08-09 16:14:22,740 [18797] (MainThread) Closing the Kafka producer with 0 secs timeout.
2016-08-09 16:14:22,740 [18797] (MainThread) Proceeding to force close the producer since pending requests could not be completed within timeout 0.
2016-08-09 16:14:22,741 [18797] (eventlogging-3d1e80f0-5e4c-11e6-83d5-fa163e2d5256-deployment-eventlogging04.deployment-prep.eqiad.wmflabs.18797-network-thread) Beginning shutdown of Kafka producer I/O thread, sending remaining records.
2016-08-09 16:14:22,741 [18797] (eventlogging-3d1e80f0-5e4c-11e6-83d5-fa163e2d5256-deployment-eventlogging04.deployment-prep.eqiad.wmflabs.18797-network-thread) Produced messages to topic-partition TopicPartition(topic='eqiad.test.event', partition=0) with base offset None and error IllegalStateError: Producer is closed forcefully..
2016-08-09 16:14:22,742 [18797] (eventlogging-3d1e80f0-5e4c-11e6-83d5-fa163e2d5256-deployment-eventlogging04.deployment-prep.eqiad.wmflabs.18797-network-thread) Shutdown of Kafka producer I/O thread has completed.
2016-08-09 16:14:22,743 [18797] (MainThread) The Kafka producer has closed.
```

Full debug logs here:
https://gist.github.com/ottomata/8cd48f016ad9060315aed9876c862c28

**Comment by dpkp** [comment]
Apologies -- test suite did not catch that bug. It occurs only on reconnections. The fix was released yesterday as 1.3.1.
