### ISSUE TITLE
Help: What causes InvalidSessionTimeoutError?

### ISSUE THREAD

**Issue by gjaldon** [dpkp/kafka-python#837]
Hi there! Hope it's ok that I post my question here. I tried asking at #apache-kafka channel on IRC but was unable to get help.

I'm trying to set up kafka in prod, but running my python app returns the ff error: 
```bash
2016-09-30 13:14:51,876.876.533985138:kafka.coordinator:140088372619072:ERROR:7654:Attempt to join group kafka-python-default-group failed due to fatal error: [Error 26] InvalidSessionTimeoutError: JoinGroupResponse_v0(error_code=26, generation_id=0, group_protocol=u'', leader_id=u'', member_id=u'', members=[])
Traceback (most recent call last):
  File "sightline_maps_lambda/main.py", line 50, in <module>
    main()
  File "sightline_maps_lambda/main.py", line 19, in main
    for message in consumer:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/vendor/six.py", line 559, in next
    return type(self).__next__(self)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/consumer/group.py", line 915, in __next__
    return next(self._iterator)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/consumer/group.py", line 841, in _message_generator
    self._coordinator.ensure_active_group()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/coordinator/base.py", line 270, in ensure_active_group
    raise exception # pylint: disable-msg=raising-bad-type
kafka.errors.InvalidSessionTimeoutError: [Error 26] InvalidSessionTimeoutError: JoinGroupResponse_v0(error_code=26, generation_id=0, group_protocol=u'', leader_id=u'', member_id=u'', members=[])
2016-09-30 13:14:51,877.877.21991539:kafka.producer.kafka:140088372619072:INFO:7654:Closing the Kafka producer with 999999999 secs timeout.
2016-09-30 13:14:51,894.894.371032715:kafka.producer.kafka:140088372619072:INFO:7654:Kafka producer closed
```
Any idea what's causing the error? Here is a gist of my server.properties config file:
https://gist.github.com/gjaldon/3b858ab6bb932138f97e01a087eeb12d

The python app works fine when running locally (OSX). I'm using kafka 0.10 and zookeeper locally that's installed via brew. 

In prod, I'm using kafka 0.9 kafka-python 1.3.1. Kafka and zookeeper are running in prod in the default ports (9091 and 2181) in localhost. My prod OS is Ubuntu 14.04. I tried creating a topic and producing messages for a topic in prod using the console commands and they work.

**Comment by dpkp** [comment]
The error happens when you have a consumer attempt to use a group session timeout that is larger than the maximum allowed by the broker. You should check your consumer and broker settings. If you are relying on broker defaults, I believe that there was a change from 30secs in 0.9 to 300 secs in 0.10. Perhaps your consumer is asking for a timeout > 30secs ?

**Comment by gjaldon** [comment]
The only timeout that was set was:
```
zookeeper.connection.timeout.ms=1000000
```

Could this possibly lead to the error? I did not set a value for `group.max.session.timeout.ms` or `group.min.session.timeout.ms`. I also passed `session_timeout_ms=300000` to `KafkaConsumer`. Could that have led to this?

**Comment by gjaldon** [comment]
Ok just tested it out. It turns out `session_timeout_ms` should be within the range of `group.min.session.timeout.ms` and `group.max.session.timeout.ms`.

**Comment by dpkp** [comment]
exactly

**Comment by gjaldon** [comment]
Btw, thanks a lot for the help, @dpkp!
