### ISSUE TITLE
error: Not enough data to read message -- did server kill socket?

### ISSUE THREAD

**Issue by dalejin2014** [dpkp/kafka-python#845]
we are getting the following stacktrace in batches in our log:
kafka-python version: 0.9.5
kafka broker version: 0.10.0.1

---
2016-10-11 18:30:45,585 ERROR [kafka.conn:106][Thread-7][request=22aaa940-26ce-4aa5-92a6-546da22d4385] Unable to receive data from Kafka
Traceback (most recent call last):
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/kafka/conn.py", line 103, in _read_bytes(self=<KafkaConnection host=10.128.64.105 port=9092>, num_bytes=4)
    raise socket.error("Not enough data to read message -- did server kill socket?")
error: Not enough data to read message -- did server kill socket?
    local variables:
    - bytes_left: 4
    - data: ''
    - num_bytes: 4
    - responses: []
    - self: <KafkaConnection host=10.128.64.105 port=9092>
2016-10-11 18:30:45,586 WARNI [kafka.client:252][Thread-7][request=22aaa940-26ce-4aa5-92a6-546da22d4385] ConnectionError attempting to receive a response to request 239228 from server BrokerMetadata(nodeId=100, host='10.128.64.105', port=9092): Kafka @ 10.128.64.105:9092 went away
2016-10-11 18:30:45,586 ERROR [kafka.producer:414][Thread-7][request=22aaa940-26ce-4aa5-92a6-546da22d4385] Unable to send messages
Traceback (most recent call last):
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/kafka/producer/base.py", line 411, in _send_messages
    fail_on_error=self.sync_fail_on_error
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/kafka/client.py", line 614, in send_produce_request
    (not fail_on_error or not self._raise_on_response_error(resp))]
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/kafka/client.py", line 374, in _raise_on_response_error(self=<KafkaClient client_id=kafka-python>, resp=FailedPayloadsError())
    raise resp
FailedPayloadsError:
    local variables:
    - resp: FailedPayloadsError()
    - self: <KafkaClient client_id=kafka-python>
2016-10-11 18:30:45,587 ERROR [...:171][Thread-7][request=22aaa940-26ce-4aa5-92a6-546da22d4385] Kafka Failure: ...
Traceback (most recent call last):
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/xxx/v2/lib/kafka.py", line 169, in publish_create_responses
    request.publisher.post('respondents', int(survey_id), data)
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/smsdk/kafka/publisher.py", line 61, in __call__
    return self._func(*args, **kwargs)
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/smsdk/kafka/publisher.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/smsdk/kafka/publisher.py", line 136, in post
    topic, object_id, message
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/kafka/producer/keyed.py", line 43, in send_messages
    return self._send_messages(topic, partition, *msg, key=key)
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/kafka/producer/base.py", line 411, in _send_messages
    fail_on_error=self.sync_fail_on_error
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/kafka/client.py", line 614, in send_produce_request
    (not fail_on_error or not self._raise_on_response_error(resp))]
  File "/opt/deploys/xxx/releases/662/local/lib/python2.7/site-packages/kafka/client.py", line 374, in _raise_on_response_error(self=<KafkaClient client_id=kafka-python>, resp=FailedPayloadsError())
    raise resp
FailedPayloadsError:
    local variables:
    - resp: FailedPayloadsError()
    - self: <KafkaClient client_id=kafka-python>

**Comment by dalejin2014** [comment]
cc: @dpkp

**Comment by dpkp** [comment]
Not enough in your post to know what is causing the error. But I'd suggest upgrading to the most recent kafka-python and use KafkaConsumer / KafkaProducer. The interfaces you are using are deprecated.

**Comment by jianbin-wei** [comment]
@dalejin2014 We also have this issue.  It traces down to the broker closes idle connection in 0.10.0.1 after connections.max.idle.ms.  In kafka-python 0.9.5 a request is sent out without checking the connection state and hence the error.

**Comment by jeffwidman** [comment]
See also https://github.com/dpkp/kafka-python/issues/849#issuecomment-261415353
