### ISSUE TITLE
kafka server  wedged at 100% CPU with no traffic!

### ISSUE THREAD

**Issue by ZiCog** [dpkp/kafka-python#852]
I was just trying my first tentative experiments with kafka. Which ended up with it wedged at 100% CPU load for ten minutes while no traffic was flowing.

I have kafka_2.11-0.10.0.0 running on a headless Debian Jessie PC and set it running as per the starter instructions:

```
$ nohup  bin/zookeeper-server-start.sh config/zookeeper.properties &
$ nohup bin/kafka-server-start.sh config/server.properties &

```
I create a couple of topics:

```
$bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --zookeeper localhost:2181   --topic topic1 --from-beginning
$ bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --zookeeper localhost:2181   --topic topic2 --from-beginning

```
Then on another machine I start experimenting with node.js and kafka-node.

Firstly a producer that puts a few hundred thousand messages into the topics. Then a consumer to get them back again. Which both worked.

The code which triggered the server blow up was only a little test of getting latest offsets:

```
// Fetch first or last offsets or from a given time.
const offset = new kafka.Offset(client);
offset.fetch([
    { topic: 'topic1', partition: 0, time: -2, maxNum: 10 },   // First available offset
    { topic: 'topic2', partition: 0, time: -1, maxNum: 10 }    // Latest offset
], function(err, data) {
    if (err) {
        return console.log("Error: offset.fetch:", err);
    }
    console.log(data);
    var firstOffsetTopic1 = data['topic1']['0'][0];
    var latestOffsetTopic2 = data['topic2']['0'][0];

    console.log('First offset topic 1', firstOffsetTopic1);
    console.log('Latest offset topic2', latestOffsetTopic2);
});

let partition = 0;
let topic = 'topic1';
offset.fetchLatestOffsets([topic], function (error, offsets) {
    if (error) {
        return console.log('Error: error: offset.fetchLatestOffsets', err);
    }
    console.log(offsets[topic][partition]);
});

```
Which I notice sometimes fails with: 

```
$ node kafka-node-test.js

events.js:160
      throw er; // Unhandled 'error' event
      ^
BrokerNotAvailableError: Could not find a broker
    at new BrokerNotAvailableError (C:\cygwin64\home\michael\fits-view-webgl\node_modules\kafka-node\lib\errors\BrokerNotAvailableError.js:11:9)
    at Client.brokerForLeader (C:\cygwin64\home\michael\fits-view-webgl\node_modules\kafka-node\lib\client.js:609:26)
    at Client.loadMetadataForTopics (C:\cygwin64\home\michael\fits-view-webgl\node_modules\kafka-node\lib\client.js:341:21)
    at Client.send (C:\cygwin64\home\michael\fits-view-webgl\node_modules\kafka-node\lib\client.js:498:10)
    at Client.sendOffsetRequest (C:\cygwin64\home\michael\fits-view-webgl\node_modules\kafka-node\lib\client.js:270:8)
    at Offset.fetch (C:\cygwin64\home\michael\fits-view-webgl\node_modules\kafka-node\lib\offset.js:31:15)
    at .<anonymous> (C:\cygwin64\home\michael\fits-view-webgl\node_modules\kafka-node\lib\offset.js:27:12)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

```
Sorry if this is not a very helpful issue report. I the are any logs or such that I can dig out that might give more info I will do so.

Meanwhile I notice some exceptions in my nohup file:

```
essed session termination for sessionid: 0x157ec4b8b500078 (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:28:48,005] INFO Closed socket connection for client /192.168.1.244:50752 which had sessionid 0x157ec4b8b500078 (org.apache.zookeeper.server.NIOServerCnxn)
[2016-10-23 03:29:06,000] INFO Expiring session 0x157ec4b8b500079, timeout of 30000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:29:06,000] INFO Processed session termination for sessionid: 0x157ec4b8b500079 (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:29:06,048] INFO Got user-level KeeperException when processing sessionid:0x157ec4b8b50007a type:create cxid:0x19 zxid:0x2ab txntype:-1 reqpath:n/a Error Path:/consumers/kafka-node-group Error:KeeperErrorCode = NodeExists for /consumers/kafka-node-group (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:29:06,059] INFO Got user-level KeeperException when processing sessionid:0x157ec4b8b50007a type:create cxid:0x1a zxid:0x2ac txntype:-1 reqpath:n/a Error Path:/consumers/kafka-node-group/owners Error:KeeperErrorCode = NodeExists for /consumers/kafka-node-group/owners (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:29:06,078] INFO Got user-level KeeperException when processing sessionid:0x157ec4b8b50007a type:create cxid:0x1b zxid:0x2ad txntype:-1 reqpath:n/a Error Path:/consumers/kafka-node-group/owners/topic2 Error:KeeperErrorCode = NodeExists for /consumers/kafka-node-group/owners/topic2 (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:29:08,002] WARN Exception causing close of session 0x157ec4b8b50007a due to java.io.IOException: Connection reset by peer (org.apache.zookeeper.server.NIOServerCnxn)
[2016-10-23 03:29:08,003] INFO Closed socket connection for client /192.168.1.244:50757 which had sessionid 0x157ec4b8b50007a (org.apache.zookeeper.server.NIOServerCnxn)
[2016-10-23 03:29:09,477] INFO Accepted socket connection from /192.168.1.244:50763 (org.apache.zookeeper.server.NIOServerCnxnFactory)
[2016-10-23 03:29:09,480] WARN Connection request from old client /192.168.1.244:50763; will be dropped if server is in r-o mode (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:29:09,480] INFO Client attempting to establish new session at /192.168.1.244:50763 (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:29:09,484] INFO Established session 0x157ec4b8b50007b with negotiated timeout 30000 for client /192.168.1.244:50763 (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:29:09,507] INFO Got user-level KeeperException when processing sessionid:0x157ec4b8b50007b type:create cxid:0x2 zxid:0x2b0 txntype:-1 reqpath:n/a Error Path:/consumers/kafka-node-group Error:KeeperErrorCode = NodeExists for /consumers/kafka-node-group (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:29:09,513] INFO Got user-level KeeperException when processing sessionid:0x157ec4b8b50007b type:create cxid:0x4 zxid:0x2b1 txntype:-1 reqpath:n/a Error Path:/consumers/kafka-node-group/ids Error:KeeperErrorCode = NodeExists for /consumers/kafka-node-group/ids (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:29:19,497] WARN Exception causing close of session 0x157ec4b8b50007b due to java.io.IOException: Connection reset by peer (org.apache.zookeeper.server.NIOServerCnxn)
[2016-10-23 03:29:19,498] INFO Closed socket connection for client /192.168.1.244:50763 which had sessionid 0x157ec4b8b50007b (org.apache.zookeeper.server.NIOServerCnxn)
[2016-10-23 03:29:39,000] INFO Expiring session 0x157ec4b8b50007a, timeout of 30000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:29:39,000] INFO Processed session termination for sessionid: 0x157ec4b8b50007a (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:29:42,000] INFO Expiring session 0x157ec4b8b50007b, timeout of 30000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:29:42,001] INFO Processed session termination for sessionid: 0x157ec4b8b50007b (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:30:00,451] INFO Accepted socket connection from /192.168.1.244:50768 (org.apache.zookeeper.server.NIOServerCnxnFactory)
[2016-10-23 03:30:00,456] WARN Connection request from old client /192.168.1.244:50768; will be dropped if server is in r-o mode (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:30:00,456] INFO Client attempting to establish new session at /192.168.1.244:50768 (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:30:00,460] INFO Established session 0x157ec4b8b50007c with negotiated timeout 30000 for client /192.168.1.244:50768 (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:30:00,605] WARN Exception causing close of session 0x157ec4b8b50007c due to java.io.IOException: Connection reset by peer (org.apache.zookeeper.server.NIOServerCnxn)
[2016-10-23 03:30:00,606] INFO Closed socket connection for client /192.168.1.244:50768 which had sessionid 0x157ec4b8b50007c (org.apache.zookeeper.server.NIOServerCnxn)
[2016-10-23 03:30:08,655] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-10-23 03:30:21,105] INFO Accepted socket connection from /192.168.1.244:50772 (org.apache.zookeeper.server.NIOServerCnxnFactory)
[2016-10-23 03:30:21,110] WARN Connection request from old client /192.168.1.244:50772; will be dropped if server is in r-o mode (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:30:21,111] INFO Client attempting to establish new session at /192.168.1.244:50772 (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:30:21,114] INFO Established session 0x157ec4b8b50007d with negotiated timeout 30000 for client /192.168.1.244:50772 (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:30:33,000] INFO Expiring session 0x157ec4b8b50007c, timeout of 30000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:30:33,000] INFO Processed session termination for sessionid: 0x157ec4b8b50007c (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:30:55,518] WARN Exception causing close of session 0x157ec4b8b50007d due to java.io.IOException: Connection reset by peer (org.apache.zookeeper.server.NIOServerCnxn)
[2016-10-23 03:30:55,519] INFO Closed socket connection for client /192.168.1.244:50772 which had sessionid 0x157ec4b8b50007d (org.apache.zookeeper.server.NIOServerCnxn)
[2016-10-23 03:31:24,000] INFO Expiring session 0x157ec4b8b50007d, timeout of 30000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:31:24,000] INFO Processed session termination for sessionid: 0x157ec4b8b50007d (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-23 03:37:57,657] INFO [Kafka Server 0], shutting down (kafka.server.KafkaServer)
[2016-10-23 03:37:57,660] INFO [Kafka Server 0], Starting controlled shutdown (kafka.server.KafkaServer)
[2016-10-23 03:37:57,705] INFO [Kafka Server 0], Controlled shutdown succeeded (kafka.server.KafkaServer)
[2016-10-23 03:37:57,708] INFO [Socket Server on Broker 0], Shutting down (kafka.network.SocketServer)
[2016-10-23 03:38:36,538] WARN caught end of stream exception (org.apache.zookeeper.server.NIOServerCnxn)
EndOfStreamException: Unable to read additional data from client sessionid 0x157ec4b8b500000, likely client has closed socket
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
        at java.lang.Thread.run(Thread.java:745)
[2016-10-23 03:38:36,539] INFO Closed socket connection for client /127.0.0.1:47189 which had sessionid 0x157ec4b8b500000 (org.apache.zookeeper.server.NIOServerCnxn)
[2016-10-23 03:38:42,000] INFO Expiring session 0x157ec4b8b500000, timeout of 6000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2016-10-23 03:38:42,000] INFO Processed session termination for sessionid: 0x157ec4b8b500000 (org.apache.zookeeper.server.PrepRequestProcessor)


```

**Comment by dpkp** [comment]
This sounds like a server question -- have you tried asking on the server mailing lists?

**Comment by ZiCog** [comment]
Oops. So sorry. I have no idea how I ended up punching all that into here. I'm not even using Python!

Must have been getting over tired fighting with the things.
