### ISSUE TITLE
Unable to bootstrap from [('localhost', 9092, 0)] on Windows: socket issues?

### ISSUE THREAD

**Issue by ZmeiGorynych** [dpkp/kafka-python#862]
I've just installed kafka and zookeeper on Windows 10 Home based on instructions at https://dzone.com/articles/running-apache-kafka-on-windows-os, and as per that page tested it using
`kafka-console-producer.bat --broker-list localhost:9092 --topic test`
and
`kafka-console-consumer.bat --zookeeper localhost:2181 --topic test`
which work fine. 

Unfortunately, when I try to use kafka-python from jupyter, I run into problems:

First, trying to call 

```
from kafka import KafkaConsumer
consumer = KafkaConsumer(api_version=(0,10))
```

gave an error

```
ERROR:kafka.conn:Connection attempt to <BrokerConnection host=localhost/::1 port=9092> timed out
ERROR:kafka.client:Unable to bootstrap from [('localhost', 9092, 0)]
```

Thinking it was an IPv6 issue (kafka itself uses ipv4 in its terminal output), I tracked down in the code debugger the place where the ::1 appeared and hard-wired it to use 127.0.0.1 instead. 

That merely switched the error to 

```
ERROR:kafka.conn:Connection attempt to <BrokerConnection host=localhost/127.0.0.1 port=9092> timed out
ERROR:kafka.client:Unable to bootstrap from [('localhost', 9092, 0)]
```

Stepping through the code, I tracked the failure down to line 289 of conn.py
`elif ret not in (errno.EINPROGRESS, errno.EALREADY, errno.EWOULDBLOCK, 10022)
`
In the original version (IPV6), the value of ret there is 10035 once and then alternates between 10035 (EWOULDBLOCK) and 10022 (WSAEINVAL), so 10035,10035,10022,10035,10022,10035,etc; if I force the address to 127.0.0.1, it is 10035 once, and then keeps repeating 10022.

Finally, if I try calling 
`producer = KafkaProducer(bootstrap_servers=['localhost:9092'],api_version=(0,10))`
then in addition to the above error, I get
`WARNING:kafka.conn:socket.inet_pton not available on this platform. consider pip install win_inet_pton
`
When I run pip install win_inet_pton and restart jupyter, that message doesn't go away.

Any idea what the matter could be?
Thanks a lot!

**Comment by ZmeiGorynych** [comment]
Update: adding `import win_inet_pton ` to the top of conn.py fixed the last issue, but it's still unable to boostrap

**Comment by lateRunnr** [comment]
Any update on this issue? I am still facing it.

**Comment by siva5055** [comment]
I'm facing similar issue, when trying to produce from a cloud VM to a broker in private Network, ports 9092 and 2181 are made accessible to the VM and can check connection established.

But it throws

[Error 7] RequestTimedOutError: Request timed out after 30000 ms
ERROR:kafka.client:Unable to bootstrap from []

**Comment by scy245** [comment]
The problem seems to persist. I've installed kafka and zookeeper on Windows 10 Pro based on instructions at https://dzone.com/articles/running-apache-kafka-on-windows-os too and when I try to consume from a docker container, this error occurs:

```
Unable connect to "localhost:9092": Multiple exceptions: [Errno 111] Connection refused, [Errno 99] Address not available
Task exception was never retrieved
future: <Task finished coro=<task() done, defined at /app/rs_consumer/main.py:32> exception=ConnectionError("Unable to bootstrap from [('localhost', 9092, <AddressFamily.AF_UNSPEC: 0>)]")>
Traceback (most recent call last):
  File "/app/rs_consumer/main.py", line 34, in task
    await consumer.start()
  File "/usr/local/lib/python3.7/site-packages/aiokafka/consumer/consumer.py", line 336, in start
    yield from self._client.bootstrap()
  File "/usr/local/lib/python3.7/site-packages/aiokafka/client.py", line 228, in bootstrap
    'Unable to bootstrap from {}'.format(self.hosts))
kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('localhost', 9092, <AddressFamily.AF_UNSPEC: 0>)]
```

Any idea of what happens?
