### ISSUE TITLE
Connected once and never again

### ISSUE THREAD

**Issue by alvarodecastro74** [dpkp/kafka-python#938]
Trying to run a simple program from a raspberry wheezy to connect to a kafka server version 2.11-0.9 running under cloudera
============
from kafka import SimpleProducer, SimpleClient
client = SimpleClient('x.x.x.x:9092')
print ('Connected')
producer = SimpleProducer(client, async=False)
print ('Created producer')
producer.send_messages('test', b'test')
====================

I can ping the kafka server, map the 9092 port, but I get
===========================================
Connected to x.x.x.x
Created producer
Traceback (most recent call last):
  File "lixo.py", line 7, in <module>
    producer.send_messages('test', b'test')
  File "/usr/local/lib/python2.7/dist-packages/kafka/producer/simple.py", line 50, in send_messages
    topic, partition, *msg
  File "/usr/local/lib/python2.7/dist-packages/kafka/producer/base.py", line 379, in send_messages
    return self._send_messages(topic, partition, *msg)
  File "/usr/local/lib/python2.7/dist-packages/kafka/producer/base.py", line 422, in _send_messages
    fail_on_error=self.sync_fail_on_error
  File "/usr/local/lib/python2.7/dist-packages/kafka/client.py", line 644, in send_produce_request
    resps = self._send_broker_aware_request(payloads, encoder, decoder)
  File "/usr/local/lib/python2.7/dist-packages/kafka/client.py", line 253, in _send_broker_aware_request
    conn = self._get_conn(host, broker.port, afi)
  File "/usr/local/lib/python2.7/dist-packages/kafka/client.py", line 73, in _get_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/kafka/conn.py", line 230, in connect
    self._init_host, self._init_port, ex
socket.gaierror: getaddrinfo failed for x.x.x.x:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (calledadvertised.host.name before Kafka 9) correct and resolvable?

The funny thing is that once I was able to connect it and send messages for like 15 minutes, but after that never again.

And yes I know that method is deprecated, but the right one never worked

**Comment by abdesslem** [comment]
try to define env variables ADVERTISED_HOST and ADVERTISED_PORT

**Comment by dpkp** [comment]
This is a configuration issue. Fixing the advertised host / port on your brokers should fix.
