### ISSUE TITLE
disable independency with SSL

### ISSUE THREAD

**Issue by minagawa-sho** [dpkp/kafka-python#939]
Kafka-python seems to need the SSL implement on Python interepreter where it be running.
But I think that it should be comfortable to be able to disable its dependency because ssl module is optional (be able to disable on building) for Python.

Please tell me a known workaround for this topic, if exists.
Or is there this feature on the future plan of the product ?

**Comment by dpkp** [comment]
Can you provide an example of the issue you're seeing specifically?

**Comment by minagawa-sho** [comment]
This error occurs on my enviroment.
With the Python interpreter built on the machine where openssl is not installed, ssl module importing is unsuccessful.

```
$ ./python 
Python 2.7.12 (default, Jan 13 2017, 15:26:28) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import kafka
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/service/mx/krb/sqr/pkg.v0.1.0/python/lib/python2.7/site-packages/kafka_python-1.3.2-py2.7.egg/kafka/__init__.py", line 21, in <module>
    from kafka.consumer import KafkaConsumer
  File "/var/service/mx/krb/sqr/pkg.v0.1.0/python/lib/python2.7/site-packages/kafka_python-1.3.2-py2.7.egg/kafka/consumer/__init__.py", line 5, in <module>
    from .group import KafkaConsumer
  File "/var/service/mx/krb/sqr/pkg.v0.1.0/python/lib/python2.7/site-packages/kafka_python-1.3.2-py2.7.egg/kafka/consumer/group.py", line 11, in <module>
    from kafka.client_async import KafkaClient, selectors
  File "/var/service/mx/krb/sqr/pkg.v0.1.0/python/lib/python2.7/site-packages/kafka_python-1.3.2-py2.7.egg/kafka/client_async.py", line 24, in <module>
    from .conn import BrokerConnection, ConnectionStates, collect_hosts, get_ip_port_afi
  File "/var/service/mx/krb/sqr/pkg.v0.1.0/python/lib/python2.7/site-packages/kafka_python-1.3.2-py2.7.egg/kafka/conn.py", line 10, in <module>
    import ssl
  File "/var/tmp/minagawa/kurobe-sqr/build/work/Python-2.7.12/Lib/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
```

**Comment by minagawa-sho** [comment]
This error occurs on my enviroment.
With the Python interpreter built on the machine where openssl is not installed, ssl module importing is unsuccessful.

```
$ ./python
Python 2.7.12 (default, Jan 13 2017, 15:26:28) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import kafka
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/python_home/lib/python2.7/site-packages/kafka_python-1.3.2-py2.7.egg/kafka/__init__.py", line 21, in <module>
    from kafka.consumer import KafkaConsumer
  File "/path/to/python_home/lib/python2.7/site-packages/kafka_python-1.3.2-py2.7.egg/kafka/consumer/__init__.py", line 5, in <module>
    from .group import KafkaConsumer
  File "/path/to/python_home/lib/python2.7/site-packages/kafka_python-1.3.2-py2.7.egg/kafka/consumer/group.py", line 11, in <module>
    from kafka.client_async import KafkaClient, selectors
  File "/path/to/python_home/lib/python2.7/site-packages/kafka_python-1.3.2-py2.7.egg/kafka/client_async.py", line 24, in <module>
    from .conn import BrokerConnection, ConnectionStates, collect_hosts, get_ip_port_afi
  File "/path/to/python_home/lib/python2.7/site-packages/kafka_python-1.3.2-py2.7.egg/kafka/conn.py", line 10, in <module>
    import ssl
  File "/path/to/python_home/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
```

**Comment by dpkp** [comment]
Great - thanks for the stack trace. I think we can fix this.

**Comment by jeffwidman** [comment]
If this were fixed by only requiring the SSL dependency when using SSL connections (rather than `PLAINTEXT`) would also fix https://github.com/dpkp/kafka-python/issues/925.

**Comment by minagawa-sho** [comment]
I'm starting to fix this in anticipation of PR.
If anyone of the kafka-python developer team already started, please tell me.

**Comment by dpkp** [comment]
PR merged to master
