### ISSUE TITLE
Meet Error getting request for apiKey: 18 and apiVersion: 0 using python concurrent

### ISSUE THREAD

**Issue by yaoyaminaco0571** [dpkp/kafka-python#945]
dear all
I meet Error getting request for apiKey: 18 and apiVersion: 0, using python concurrent. my kafka version is cdh: 0.9.0.0+kafka2.0.1+283, my python is 2.7.5
my code as below:

```
import getopt
import logging
import sys
from concurrent import futures
import time


def work(producer, idx):
    for id in range(100000):
        mess = "id:{},type:{}".format(id, idx)
        try:
            producer.send('test', mess)
            logging.info('success:%s', mess)
        except:
            logging.exception('fail:%s', mess)
        time.sleep(1)


def main():
    opt_names=''
    long_opt_names=['workers=']
    optlist, args = getopt.getopt(sys.argv[1:], opt_names, long_opt_names)
    workers = 10

    for o,a in optlist:
        if o == '--workers':
            workers = int(a)
    e = futures.ThreadPoolExecutor(max_workers=workers)

    producer = KafkaProducer(bootstrap_servers='s001.net:s002.net:s003.net:s004.net:s005.net:s006.net:s007.net:s008.net',acks='all',retries=10)

    for i in range(workers):
        e.submit(work, producer, i)
        time.sleep(0.1)



if __name__ == '__main__':
    main()
```

and my error log is:
```
Closing socket for 172.15.1.76:9092-172.15.8.1:45251 because of error
kafka.network.InvalidRequestException: Error getting request for apiKey: 18 and apiVersion: 0
	at kafka.network.RequestChannel$Request.liftedTree2$1(RequestChannel.scala:93)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:90)
	at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:426)
	at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:421)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at kafka.network.Processor.run(SocketServer.scala:421)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unexpected ApiKeys id `18`, it should be between `0` and `16` (inclusive)
	at org.apache.kafka.common.protocol.ApiKeys.forId(ApiKeys.java:69)
	at org.apache.kafka.common.requests.AbstractRequest.getRequest(AbstractRequest.java:39)
	at kafka.network.RequestChannel$Request.liftedTree2$1(RequestChannel.scala:90)
```

thank you!

**Comment by dpkp** [comment]
The server error is expected and can be ignored. It is a side-effect of the client probing the server to determine what api version is supported. If you know the broker version you are connecting to, pass `api_verison` to your KafkaProducer (and/or KafkaConsumer). This will disable the initial version-probe and therefore avoid causing odd error logs on your server. Also you should consider upgrading to a more recent server version.

**Comment by yaoyaminaco0571** [comment]
Thanks dpkp, I've sent api_version=(0,9), and meet the same error.
To bypass this issue, I try  python threading module and it works.
I don't know why and how to troubleshooting.
